# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Appium-Python-Client" = super.buildPythonPackage rec {
    pname = "Appium-Python-Client";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/72/e5771537b5509d94cf8b269b2a1ebec9943c322c528b39e5ee577f05c26a/Appium-Python-Client-2.2.0.tar.gz";
      sha256 = "13j6qkx716n09kwzimjr59vvz73vsyr2svf17gq5iknwsw9k50mw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."selenium"
    ];
  };
  "GenSON" = super.buildPythonPackage rec {
    pname = "GenSON";
    version = "1.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/71/fbd2f1ad9695c92ad756b91f5a570f809c4959d3bd82266788cf222e5c5c/genson-1.2.2.tar.gz";
      sha256 = "05ka6j256qrqykgcw1jz01p6kx01d38d2l8k387fwymg22m6kbwc";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/97/2288fe498044284f39ab8950703e88abbac2abbdf65524d576157af70556/MarkupSafe-2.1.1.tar.gz";
      sha256 = "0jqxp5sfrc0byp6bk0gwdmildi4mck2gprp42afri3z4r5y1k4bz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "RESTinstance" = super.buildPythonPackage rec {
    pname = "RESTinstance";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/b3/72eb94687c4597009858d5b5185bf3bf48dc01d122f5f76edf2219f68534/RESTinstance-1.3.0-py2.py3-none-any.whl";
      sha256 = "1lh88xc82rmfpws6wsgcgq4w14vc5bsfmyg6l3rra15jm8rac0iz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."GenSON"
      self."docutils"
      self."flex"
      self."jsonpath-ng"
      self."jsonschema"
      self."pygments"
      self."pytz"
      self."requests"
      self."robotframework"
      self."tzlocal"
    ];
  };
  "Send2Trash" = super.buildPythonPackage rec {
    pname = "Send2Trash";
    version = "1.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/26/3435896d757335ea53dce5abf8d658ca80757a7a06258451b358f10232be/Send2Trash-1.8.0-py3-none-any.whl";
      sha256 = "027s97ylfm2a583hysjs72c2cz8w4v5l0xh7rsjsqzjivggsl3pj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "alabaster" = super.buildPythonPackage rec {
    pname = "alabaster";
    version = "0.7.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl";
      sha256 = "0nfkvlqp1mwjj0jjqk0mm7hk5c6rq5l1dpm2bva5pq50rjykhr24";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "anyio" = super.buildPythonPackage rec {
    pname = "anyio";
    version = "3.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/ae/9a8af72d6f0c551943903eefcf93c3a29898fb7b594603c0d70679c199b1/anyio-3.5.0-py3-none-any.whl";
      sha256 = "0biwikx39fkdh411v9ndsqa3akdd5pzvpdgfy9311ylkzz2idymm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."sniffio"
    ];
  };
  "argon2-cffi" = super.buildPythonPackage rec {
    pname = "argon2-cffi";
    version = "21.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/07/946d5a9431bae05a776a59746ec385fbb79b526738d25e4202d3e0bbf7f4/argon2_cffi-21.3.0-py3-none-any.whl";
      sha256 = "103zv9vpw5q1ikcgjay7n4gxikq6g4cdxrhr140fbh65ya36k5wc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argon2-cffi-bindings"
    ];
  };
  "argon2-cffi-bindings" = super.buildPythonPackage rec {
    pname = "argon2-cffi-bindings";
    version = "21.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/e9/184b8ccce6683b0aa2fbb7ba5683ea4b9c5763f1356347f1312c32e3c66e/argon2-cffi-bindings-21.2.0.tar.gz";
      sha256 = "1qrrzi8rcif6c5bcbllik14smidcpxyvgkh52dyq14f7lvzwx2dv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "astroid" = super.buildPythonPackage rec {
    pname = "astroid";
    version = "2.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4f/5c/42befbb2d6eafa25bf1dcbc50dbae2e8482745eaa99cd83fc45b83ae4b07/astroid-2.11.2-py3-none-any.whl";
      sha256 = "1n8ichm3451llx1byxhr121s0ms519amfv27gh52vi0nv79c136c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."lazy-object-proxy"
      self."setuptools"
      self."typing-extensions"
      self."wrapt"
    ];
  };
  "asttokens" = super.buildPythonPackage rec {
    pname = "asttokens";
    version = "2.0.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/d5/b0ad240c22bba2f4591693b0ca43aae94fbd77fb1e2b107d54fff1462b6f/asttokens-2.0.5-py2.py3-none-any.whl";
      sha256 = "0p3hfvdvpd05bqpaikjcr92xvf3rgygila54yjk9a9ami0g6ji08";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "async-generator" = super.buildPythonPackage rec {
    pname = "async-generator";
    version = "1.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/52/39d20e03abd0ac9159c162ec24b93fbcaa111e8400308f2465432495ca2b/async_generator-1.10-py3-none-any.whl";
      sha256 = "0nsqss59xyvjhk5zzjwqw056mwaa5v60006s5iyrdd2rcdkbziq1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "21.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/be/7abce643bfdf8ca01c48afa2ddf8308c2308b0c3b239a44e57d020afa0ef/attrs-21.4.0-py2.py3-none-any.whl";
      sha256 = "1d185347kgm169c8fs1i8rmcvv65hx4fj7w5mcv5smks9mwf69rd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "babel" = super.buildPythonPackage rec {
    pname = "babel";
    version = "2.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/96/4ba93c5f40459dc850d25f9ba93f869a623e77aaecc7a9344e19c01942cf/Babel-2.9.1-py2.py3-none-any.whl";
      sha256 = "1yfyn32hlv60sr0knymcb4msvd3slmcv4z5ny08wsdyrj4my2jdb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
  };
  "backcall" = super.buildPythonPackage rec {
    pname = "backcall";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/1c/ff6546b6c12603d8dd1070aa3c3d273ad4c07f5771689a7b69a550e8c951/backcall-0.2.0-py2.py3-none-any.whl";
      sha256 = "0mfj5d1bgpy1clfgwrkmjqm2pv70pm01jp4iyyhphc96kyifdg7v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "beautifulsoup4" = super.buildPythonPackage rec {
    pname = "beautifulsoup4";
    version = "4.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/bf/f0f194d3379d3f3347478bd267f754fc68c11cbf2fe302a6ab69447b1417/beautifulsoup4-4.10.0-py3-none-any.whl";
      sha256 = "1gs9w76lzb85ha2zqdhxa90cj06p9fy5ah1aayj0x4j903kmqccs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."soupsieve"
    ];
  };
  "black" = super.buildPythonPackage rec {
    pname = "black";
    version = "22.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/1f/b29c7371958ab41a800f8718f5d285bf4333b8d0b5a5a8650234463ee644/black-22.3.0.tar.gz";
      sha256 = "0yfahlqc7dsdp1js0cbv706apldnfnlbal9b53cww8n0hs40n0im";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."mypy-extensions"
      self."pathspec"
      self."platformdirs"
      self."tomli"
      self."typing-extensions"
    ];
  };
  "bleach" = super.buildPythonPackage rec {
    pname = "bleach";
    version = "4.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/cc/74d634e1e5659742973a23bb441404c53a7bedb6cd3962109ca5efb703e8/bleach-4.1.0-py2.py3-none-any.whl";
      sha256 = "152rl5349b0ylp20j6br3f5cqra5aagngg4wmhli2797jfmm29jd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
      self."six"
      self."webencodings"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2021.10.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl";
      sha256 = "0scm6gbbk4gfwb1flivxihnim9wragvvvcia0jn488scxdih2ann";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/9e/92de7e1217ccc3d5f352ba21e52398372525765b2e0c4530e6eb2ba9282a/cffi-1.15.0.tar.gz";
      sha256 = "0m3rz2pqfmyfagx0bhj2jlbr2h58j3wr3cyv1agxkhlnm1k0s3wj";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "2.0.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/b3/24afc8868eba069a7f03650ac750a778862dc34941a4bebeb58706715726/charset_normalizer-2.0.12-py3-none-any.whl";
      sha256 = "1pxim0sfz7gq157k9kv88kxxzvgnid1ip0maxas3jyxipnzfv0b8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/48/58/c8aa6a8e62cc75f39fee1092c45d6b6ba684122697d7ce7d53f64f98a129/click-8.0.3-py3-none-any.whl";
      sha256 = "1wwfa6j4490kd2qawk68a4ikf8nbj6gjynazdc5v9bmdjmj4cgrm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "coverage" = super.buildPythonPackage rec {
    pname = "coverage";
    version = "6.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/fb/f481628033d42f6f6021af8a9a13d913707221e139567f39b09b337421b9/coverage-6.3.2.tar.gz";
      sha256 = "1s9ccmp9g8cgxxhp0lfdkj1scizwx4p7867z8prixfc6c21agqh3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "coveralls" = super.buildPythonPackage rec {
    pname = "coveralls";
    version = "3.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/d6/e95db3c56afd1eff815db7dda01908f5e57770e47042209db448ab496197/coveralls-3.3.1-py2.py3-none-any.whl";
      sha256 = "09k0n4khxd64irfbybw3b1q20wz1g8w9nf1688fkasrq3pria87l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."coverage"
      self."docopt"
      self."requests"
    ];
  };
  "debugpy" = super.buildPythonPackage rec {
    pname = "debugpy";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/45/8e3384e99b8bf79f8ba937aa3e726331789bdfb65ab03aedaedda9e2d30b/debugpy-1.6.0.zip";
      sha256 = "0xcjiba4paz2c6favygl6wf76ssz1znlan567rn7n7wra84c8ybv";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    propagatedBuildInputs = [];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "5.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl";
      sha256 = "11kisc16y8lmka9khfvnm4gzwaa7x6n5lg4i4lr45p5r01czihxq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "defusedxml" = super.buildPythonPackage rec {
    pname = "defusedxml";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl";
      sha256 = "0qca37v5iv0304hrl9pzad4jpnxfrnv449cyi768c0kp53jfflm3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "dill" = super.buildPythonPackage rec {
    pname = "dill";
    version = "0.3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/c3/973676ceb86b60835bb3978c6db67a5dc06be6cfdbd14ef0f5a13e3fc9fd/dill-0.3.4-py2.py3-none-any.whl";
      sha256 = "0ksdr8yqvz4sxkvwg3mkfskw9ncihzjkcpakngm9rz840fky8h3y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docopt" = super.buildPythonPackage rec {
    pname = "docopt";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz";
      sha256 = "14f4hn6d1j4b99svwbaji8n2zj58qicyz19mm0x6pmhb50jsics9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docutils" = super.buildPythonPackage rec {
    pname = "docutils";
    version = "0.17.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/5e/6003a0d1f37725ec2ebd4046b657abb9372202655f96e76795dca8c0063c/docutils-0.17.1-py2.py3-none-any.whl";
      sha256 = "0qgw95skhxi8xi1bm7vsldsgkb02cr7qfmibnwia0dx7f21nqcfg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "entrypoints" = super.buildPythonPackage rec {
    pname = "entrypoints";
    version = "0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/35/a8/365059bbcd4572cbc41de17fd5b682be5868b218c3c5479071865cab9078/entrypoints-0.4-py3-none-any.whl";
      sha256 = "17rgshlq8b00xzrvvr6770azb4rnkxjgihvwv4ygs13mhbzvax7i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "executing" = super.buildPythonPackage rec {
    pname = "executing";
    version = "0.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/d8/ad89910dc1da01a24135cb3dce702c72a8172f7b8f896ac0c4c34bcaf323/executing-0.8.3-py2.py3-none-any.whl";
      sha256 = "1ja6fl9wy28sibjsfydciipsqwbzi7c6vjh576d690qvvcrg3vni";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "faker" = super.buildPythonPackage rec {
    pname = "faker";
    version = "13.3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/e7/686e97c677037102e0b6f88c63e08ba252b736b3c13260a7f1dbfaef9c24/Faker-13.3.4-py3-none-any.whl";
      sha256 = "09il9yd8650f7xpifgkq7zq4l7y3jdrx5cvx27dh7riwb7ifqn3p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."python-dateutil"
    ];
  };
  "fancycompleter" = super.buildPythonPackage rec {
    pname = "fancycompleter";
    version = "0.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/ef/c08926112034d017633f693d3afc8343393a035134a29dfc12dcd71b0375/fancycompleter-0.9.1-py3-none-any.whl";
      sha256 = "103hmm2b1s957m6yyvglkvpzz22kz5gg7j2yyb3lqllxgp56n1yx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyrepl"
    ];
  };
  "fastjsonschema" = super.buildPythonPackage rec {
    pname = "fastjsonschema";
    version = "2.15.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/0b/24795939622d60f4b453aa7040f23c6a6f8b44c7c026c3b42d9842e6cc31/fastjsonschema-2.15.3-py3-none-any.whl";
      sha256 = "185n03x32j24j3ai4a9l75sapx49g924xl9bhaxklviy4kcb3c6x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "flex" = super.buildPythonPackage rec {
    pname = "flex";
    version = "6.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/51/f3bf1779a12e92c3bf9f2d0ee242298775ef625adb596951090bdd24854f/flex-6.14.1.tar.gz";
      sha256 = "1sr91f5sqywj4040jm3cq4333fp8hbmmr7v6v05a3h0sgyixcbi9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."jsonpointer"
      self."pyyaml"
      self."requests"
      self."rfc3987"
      self."six"
      self."strict-rfc3339"
      self."validate-email"
    ];
  };
  "furl" = super.buildPythonPackage rec {
    pname = "furl";
    version = "2.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/ef/a572e03144d18842c480bd25165ec50ddc20b1744b2aeaaae4408a281f6f/furl-2.1.3-py2.py3-none-any.whl";
      sha256 = "1h36jqq660w5y41b5i1s4wj47rc39bmmzr084n0gj5s25h32bd4s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."orderedmultidict"
      self."six"
    ];
  };
  "h11" = super.buildPythonPackage rec {
    pname = "h11";
    version = "0.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/d2/32a15a4955be1b8114a1c570999eefd31279c7f9aa2d2a43d492a79b53c5/h11-0.13.0-py3-none-any.whl";
      sha256 = "0hklkqvhmrvcnkzvwa0qjdwkqzgj1bn43kf88r9sag337db7ipcd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/a2/d918dcd22354d8958fe113e1a3630137e0fc8b44859ade3063982eacd2a4/idna-3.3-py3-none-any.whl";
      sha256 = "1zrm4xnjas13byafi11ma2q8h5rr1fmjwvi41xp5k07sgw2dvnc4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "imagesize" = super.buildPythonPackage rec {
    pname = "imagesize";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/d6/5e803b17f4d42e085c365b44fda34deb0d8675a1a910635930b831c43f07/imagesize-1.3.0-py2.py3-none-any.whl";
      sha256 = "135avlpiphvyqrch6n0cpp885aimjbxa29l9ks93wg7554jzichx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "4.11.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/f2/c48787ca7d1e20daa185e1b6b2d4e16acd2fb5e0320bc50ffc89b91fa4d7/importlib_metadata-4.11.3-py3-none-any.whl";
      sha256 = "1ipdc8h4npfrrvfzdkniwmsdp8n1afxr3wwadcdcm30am4f4620j";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "iniconfig" = super.buildPythonPackage rec {
    pname = "iniconfig";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9b/dd/b3c12c6d707058fa947864b67f0c4e0c39ef8610988d7baea9578f3c48f3/iniconfig-1.1.1-py2.py3-none-any.whl";
      sha256 = "1cx8kpp3akxwadzsmv2cdnifkyzj8fki5frmv3mzcivz9g3287h1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "iplantuml" = super.buildPythonPackage rec {
    pname = "iplantuml";
    version = "0.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/b9/4db9b9ce81184d1d67f82284ca6131258b32f3f69376ee88aab5f7ff60a4/IPlantUML-0.1.1.tar.gz";
      sha256 = "0p1w48iik5cl137b4xy3g5x52wl5b9fayxlr97bzd5v65dqxz1hg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."plantweb"
    ];
  };
  "ipykernel" = super.buildPythonPackage rec {
    pname = "ipykernel";
    version = "6.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/43/2ab8ba68d5e2c19e16d3c85685be1b28c2e57f1e2908732e9a76bf1bb5d9/ipykernel-6.12.1-py3-none-any.whl";
      sha256 = "0fidjxzkr351hk0f25qxwii6k7wwcfpcv3gp75lvy8sb3jzy6h6q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."debugpy"
      self."ipython"
      self."jupyter-client"
      self."matplotlib-inline"
      self."nest-asyncio"
      self."packaging"
      self."psutil"
      self."tornado"
      self."traitlets"
    ];
  };
  "ipython" = super.buildPythonPackage rec {
    pname = "ipython";
    version = "8.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/51/d281fd3995507e01dab71af946c659e4ef80d07cd53e8bb17e6d23f8dd60/ipython-8.2.0-py3-none-any.whl";
      sha256 = "0mr8lczbcby28ya1w2dlcr2ll5xhlckqgbyr0fr7mn28gbyjnrqv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."matplotlib-inline"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."stack-data"
      self."traitlets"
    ];
  };
  "ipython-genutils" = super.buildPythonPackage rec {
    pname = "ipython-genutils";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl";
      sha256 = "1f7sc4ydjj33gadcgfz8fcx02d1wm2frlqwzdik1krlr6wikgpbj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ipywidgets" = super.buildPythonPackage rec {
    pname = "ipywidgets";
    version = "7.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/7d/06b48ec5fd605775c7e85b3ea397d8f0294f66d570bcee59496eb5195fc5/ipywidgets-7.7.0-py2.py3-none-any.whl";
      sha256 = "0f6zjd2s431xc1ay0dg1mnwbd1vap5f3mqdnxj8iwj2dr65zb3z5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."ipython-genutils"
      self."jupyterlab-widgets"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
  };
  "isort" = super.buildPythonPackage rec {
    pname = "isort";
    version = "5.10.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b8/5b/f18e227df38b94b4ee30d2502fd531bebac23946a2497e5595067a561274/isort-5.10.1-py3-none-any.whl";
      sha256 = "19qv6lgilj8c79fgf9vz49ad4345j0baiqqg105m1d495y7dfqkg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/0e/836f12ec50075161e365131f13f5758451645af75c2becf61c6351ecec39/jedi-0.18.1-py2.py3-none-any.whl";
      sha256 = "13dss7gynvyba2dfkwynvr0faysa4chg7mqwp774ayglzhsrcz33";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/02/af4045156cde8feeefa30cb1c051e10321d4960c418bd52346a497feb302/Jinja2-3.1.1-py3-none-any.whl";
      sha256 = "06gibyqlfag2lzcy40dnlch4yny3pmfn9aa8p10rz9kl3bskb62k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "json5" = super.buildPythonPackage rec {
    pname = "json5";
    version = "0.9.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/8e/ebde0a31c71e7098b3014faf46c80bdbcadb3c23b0ac7c7646b2af7d302e/json5-0.9.6-py2.py3-none-any.whl";
      sha256 = "1hl18k5a5mlqarnhdxnsz5mdqm94d0nkw7vyh7nrp52mnc752gl2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonpath-ng" = super.buildPythonPackage rec {
    pname = "jsonpath-ng";
    version = "1.5.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/b7/3627068d9aa6b2d49af117eb3897770a5dbc6bb3f4c09ed56a9eb749438e/jsonpath_ng-1.5.3-py3-none-any.whl";
      sha256 = "0rdz8z59im51bwb9l496vyr1f3pw60v3vp62bakrn0klkmb96ai9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
  };
  "jsonpointer" = super.buildPythonPackage rec {
    pname = "jsonpointer";
    version = "2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/38/6d04fe1f9bc0b5769cd2bb35868c862b59edbd2efcdb296671c9c982ef0f/jsonpointer-2.2-py2.py3-none-any.whl";
      sha256 = "1di3735m7arffx02bkb405l3rmxg6ba6qk1cwwx3xp6lf9xa9n96";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/b2/2c4af6a97c3f12c6d5a72b41d328c3996e14e1e46701df3fac1ed65119c9/jsonschema-4.4.0-py3-none-any.whl";
      sha256 = "08w8kjfz5hxv6hj2g29pjxkrfhb2n5qq6j1xigp56jb8f4gila3p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
    ];
  };
  "jupyter" = super.buildPythonPackage rec {
    pname = "jupyter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
  };
  "jupyter-client" = super.buildPythonPackage rec {
    pname = "jupyter-client";
    version = "7.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/11/3595856d4e7bfb5fb9929d966cb8791f4d9a79b5dfcdd316b440b43b66e5/jupyter_client-7.2.2-py3-none-any.whl";
      sha256 = "0lxs8m53m6pb2jdvpbcqfs9d244xvjqmx5lxh4ylj4nwx9458124";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."entrypoints"
      self."jupyter-core"
      self."nest-asyncio"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-console" = super.buildPythonPackage rec {
    pname = "jupyter-console";
    version = "6.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/e9/5d4e1e616f7d7a8a9d7f313ac14bf43d1ea33cae6859eeb761b8cac364c2/jupyter_console-6.4.3-py3-none-any.whl";
      sha256 = "0ha88b83xl6f6sq4qjfgi9f84jjd8b1dg2k88pd8s260havbqc76";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
  };
  "jupyter-contrib-core" = super.buildPythonPackage rec {
    pname = "jupyter-contrib-core";
    version = "0.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/8f/04a752a8b66a66e7092c035e5d87d2502ac7ec07f9fb6059059b6c0dc272/jupyter_contrib_core-0.3.3-py2.py3-none-any.whl";
      sha256 = "03z5vly0qqhwwmznbf01a28qxaimagc6qk0cdgamhn4gb8kixj0y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-core"
      self."notebook"
      self."setuptools"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-contrib-nbextensions" = super.buildPythonPackage rec {
    pname = "jupyter-contrib-nbextensions";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/33/f0/6e2c00afda860f655fbf0f795f7310bdbf12122846344dfdc803fc7455d5/jupyter_contrib_nbextensions-0.5.1-py2.py3-none-any.whl";
      sha256 = "0h7z608b239mnrnz81lzry9s8v4hcq7xqsv5dxk6ki88l851y1rc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jupyter-contrib-core"
      self."jupyter-core"
      self."jupyter-highlight-selected-word"
      self."jupyter-latex-envs"
      self."jupyter-nbextensions-configurator"
      self."lxml"
      self."nbconvert"
      self."notebook"
      self."pyyaml"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-core" = super.buildPythonPackage rec {
    pname = "jupyter-core";
    version = "4.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/7d/bee50351fe3ff6979e949b9c4c00c556a7a9732ba39b547d07d93450de23/jupyter_core-4.9.2-py3-none-any.whl";
      sha256 = "0vd4nj6k2kmyra5c3l0b940z4xf5j1gsb3s63lqr0990gv9f8xgq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "jupyter-highlight-selected-word" = super.buildPythonPackage rec {
    pname = "jupyter-highlight-selected-word";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/50/d7/19ab7cfd60bf268d2abbacc52d4295a40f52d74dfc0d938e4761ee5e598b/jupyter_highlight_selected_word-0.2.0-py2.py3-none-any.whl";
      sha256 = "0n1wj2sw2rqb3bv57r9phshlwad5sgf08mkrlpiynzh5rflxyicm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jupyter-latex-envs" = super.buildPythonPackage rec {
    pname = "jupyter-latex-envs";
    version = "1.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/15/55805de080d5542f76920364635e96e64d3b37f678befdfe3b16aa154205/jupyter_latex_envs-1.4.6.tar.gz";
      sha256 = "0wiq6jssjdnvicwrnrivbjzlg4lkqakpjn4ihflvp2645pmk22h7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-core"
      self."nbconvert"
      self."notebook"
      self."traitlets"
    ];
  };
  "jupyter-nbextensions-configurator" = super.buildPythonPackage rec {
    pname = "jupyter-nbextensions-configurator";
    version = "0.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/a3/d72d5f2dc10c5ccf5a6f4c79f636bf071a5ce462dedd07af2f70384db6cb/jupyter_nbextensions_configurator-0.4.1.tar.gz";
      sha256 = "10sfdq3rkffpc8rgzwzyk3vrjsb9v158xc7b63xiz3l9kmfnps75";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-contrib-core"
      self."jupyter-core"
      self."notebook"
      self."pyyaml"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-server" = super.buildPythonPackage rec {
    pname = "jupyter-server";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/f0/1bea1cd0f5269ceccac7c721cd52c757e1ec5482ed44d1a493d12877fb92/jupyter_server-1.16.0-py3-none-any.whl";
      sha256 = "0lrklxif1whabd5z9df5029cq175jx1vlch6x2afyb9x6zsizpbj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Send2Trash"
      self."anyio"
      self."argon2-cffi"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."packaging"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
      self."websocket-client"
    ];
  };
  "jupyter-starters" = super.buildPythonPackage rec {
    pname = "jupyter-starters";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/54/3f1fc07f60d63c81a6e102bbda67aeced208416c11d2e6e6d188f584d589/jupyter_starters-1.1.0-py3-none-any.whl";
      sha256 = "1s62y3srcaqcc1dw4yma83s46bcp352czngwsphfz640xmspba4r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-client"
      self."jupyterlab"
    ];
  };
  "jupyterlab" = super.buildPythonPackage rec {
    pname = "jupyterlab";
    version = "3.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/c2/09511d202fe6db96be3b74a7ce9225b0163cc3221182fd0e9fee24cf50a5/jupyterlab-3.3.3-py3-none-any.whl";
      sha256 = "0hfq56xzly16wsghnkgb0fw6vnnzk7qzz0nay96086v22ghd5f30";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jinja2"
      self."jupyter-core"
      self."jupyter-server"
      self."jupyterlab-server"
      self."nbclassic"
      self."packaging"
      self."tornado"
    ];
  };
  "jupyterlab-pygments" = super.buildPythonPackage rec {
    pname = "jupyterlab-pygments";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/6f/c34288766797193b512c6508f5994b830fb06134fdc4ca8214daba0aa443/jupyterlab_pygments-0.1.2-py2.py3-none-any.whl";
      sha256 = "0200ccpy61p8bdnqgc9r05fjlp8lfnnd5cpwmvpqf6ans47qiyxb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pygments"
    ];
  };
  "jupyterlab-server" = super.buildPythonPackage rec {
    pname = "jupyterlab-server";
    version = "2.12.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/dc/970513d333b25cfc0eae1831d0315e9969ce1db3bda64fe47dcad0002ff4/jupyterlab_server-2.12.0-py3-none-any.whl";
      sha256 = "0wk4knq362s23g1xiw1ivzvsqwgh29bk8r50fx7nihn5am4j6pfv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."babel"
      self."entrypoints"
      self."jinja2"
      self."json5"
      self."jsonschema"
      self."jupyter-server"
      self."packaging"
      self."requests"
    ];
  };
  "jupyterlab-widgets" = super.buildPythonPackage rec {
    pname = "jupyterlab-widgets";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/2c/7331aa9c5041e8b107d712d853268e137f55014b858407816b5487289d11/jupyterlab_widgets-1.1.0-py3-none-any.whl";
      sha256 = "0gxdxfsffhywbjz1g8nxq5mwa05hsdp0d316fd6zc87ii4vvvaf2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jupytext" = super.buildPythonPackage rec {
    pname = "jupytext";
    version = "1.13.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/e3/538509410372acd6d41f12c028dfc75ebddfbc4f7544f933bff7b5cc3e97/jupytext-1.13.8-py3-none-any.whl";
      sha256 = "18naa8mamray1jnm6kw924n49v3ca61h7mhd7xywhg3n28h2spb2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markdown-it-py"
      self."mdit-py-plugins"
      self."nbformat"
      self."pyyaml"
      self."toml"
    ];
  };
  "lazy-object-proxy" = super.buildPythonPackage rec {
    pname = "lazy-object-proxy";
    version = "1.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/93/3fc1cc28f71dd10b87a53b9d809602d7730e84cc4705a062def286232a9c/lazy-object-proxy-1.7.1.tar.gz";
      sha256 = "1958nnbg6gh1frnzcpwwvahsbx2kfpjfbsyd8dkp1vvdk1dwf2fn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "lunr" = super.buildPythonPackage rec {
    pname = "lunr";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/1b/a0d16741a4a3734b7de64ec092a911e122c92251c6c435211383ae487658/lunr-0.6.2-py2.py3-none-any.whl";
      sha256 = "01ms1iklbpmyxxcjb33hn2gx98395p1hzblwiwcwd5zz0yg63gvg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/94/e2b1b3bad91d15526c7e38918795883cee18b93f6785ea8ecf13f8ffa01e/lxml-4.8.0.tar.gz";
      sha256 = "08vf1kaqi1l2zcfks0bmwqybvq9miwi2ibmbm568l8p6c3y64gzn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "markdown-it-py" = super.buildPythonPackage rec {
    pname = "markdown-it-py";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/76/8e186ed000240e4ed46fc51637e00b30c08490ac9f5e5ed43c0713c68b45/markdown_it_py-2.0.1-py3-none-any.whl";
      sha256 = "1gdqzn6rpx9kj9r88i9ng07986sp555rgx0k4avbrbwcr8w435ri";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."mdurl"
    ];
  };
  "matplotlib-inline" = super.buildPythonPackage rec {
    pname = "matplotlib-inline";
    version = "0.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/2d/2230afd570c70074e80fd06857ba2bdc5f10c055bd9125665fe276fadb67/matplotlib_inline-0.1.3-py3-none-any.whl";
      sha256 = "0p5aspzrjaix21cip8vl9yfa207ljs91m8kmsij2sikj7fx0bmmf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "mccabe" = super.buildPythonPackage rec {
    pname = "mccabe";
    version = "0.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl";
      sha256 = "0hhdp0srgrv4bmzlzvmk67zrqr9cvkjjzgd4gmkvd90dhrc652mb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mdit-py-plugins" = super.buildPythonPackage rec {
    pname = "mdit-py-plugins";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5b/c4/1cf60e11b55197fa2e5e8d2f732a229690f5a08b018ae1cf4c00585ca834/mdit_py_plugins-0.3.0-py3-none-any.whl";
      sha256 = "0ws07flim7bbgkjrpyfd7387i3gf3zssagcd307gbnz2rq0rf9xi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markdown-it-py"
    ];
  };
  "mdurl" = super.buildPythonPackage rec {
    pname = "mdurl";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/9f/cb94cab8c28f644360bdc96ab8813ec91d5de8090220c223fea350c2c0f0/mdurl-0.1.0-py3-none-any.whl";
      sha256 = "1nng5sy3xrjskq131gmqrq3zyhpwsq5wq89ws4g508cdrdnlsra0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mistune" = super.buildPythonPackage rec {
    pname = "mistune";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl";
      sha256 = "1m5qdckapi46npn36jqljlj2dqgzdm3qslz8xs4a5381fcc0b8c8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mypy-extensions" = super.buildPythonPackage rec {
    pname = "mypy-extensions";
    version = "0.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/eb/975c7c080f3223a5cdaff09612f3a5221e4ba534f7039db34c35d95fa6a5/mypy_extensions-0.4.3-py2.py3-none-any.whl";
      sha256 = "0pgi8sl514i9iamzdli8l3sxla7l4ic3nc713klrm9j5b7bys3q9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nbclassic" = super.buildPythonPackage rec {
    pname = "nbclassic";
    version = "0.3.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/11/70/89828c7016e6bdac1ac761327f7253c9db292cca94ad6a01292cb8fe0ca7/nbclassic-0.3.7-py3-none-any.whl";
      sha256 = "17a7y8c7qzc97vxs446laj4i8d3gy6y7rx9xilyarf365nm4n649";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-server"
      self."notebook"
      self."notebook-shim"
    ];
  };
  "nbclient" = super.buildPythonPackage rec {
    pname = "nbclient";
    version = "0.5.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/f7/436bb1add1814911efec4a4a5a358c7559e9b1fd19f4ef89a2a71d707c2b/nbclient-0.5.13-py3-none-any.whl";
      sha256 = "1c0q2lc2nw4cw75m71f5ip7m60amsac10m4g3wy92yckymd91b27";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-client"
      self."nbformat"
      self."nest-asyncio"
      self."traitlets"
    ];
  };
  "nbconvert" = super.buildPythonPackage rec {
    pname = "nbconvert";
    version = "6.4.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/32/31c8101dadc1716198f569f6b77abe8406fc3c283b2974d0c15c802c811b/nbconvert-6.4.5-py3-none-any.whl";
      sha256 = "056fd3rkffcqwd13jp9l4mbz7b53i9g60kc33iqgjyfcangj27g0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
      self."beautifulsoup4"
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."jupyterlab-pygments"
      self."mistune"
      self."nbclient"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
  };
  "nbformat" = super.buildPythonPackage rec {
    pname = "nbformat";
    version = "5.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/19/ae7286d58c4aa5f95d99a3eaa19ee5f6a334254b5a78ec88006b62f81476/nbformat-5.3.0-py3-none-any.whl";
      sha256 = "0f05niq1hlgl192ms1vyv2zjmw16kmg5k3sx5lp2ks29vsbnv19q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."fastjsonschema"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
  };
  "nbimporter" = super.buildPythonPackage rec {
    pname = "nbimporter";
    version = "0.3.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/fe/a85b96f9b362f206203be7aa7d811ada4abdfbba8892102c356d43ee90aa/nbimporter-0.3.4-py3-none-any.whl";
      sha256 = "18v7mdcz57mvh9k067qwwggq7d265r7xa9m7zgaqmqd3sizw790l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nbsphinx" = super.buildPythonPackage rec {
    pname = "nbsphinx";
    version = "0.8.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/ec/13038168ecd191aded1de0443817ce6574ec9434d5b7eca7acd16719d610/nbsphinx-0.8.8-py3-none-any.whl";
      sha256 = "134kfx7fxbg0ahf6c45d7ihslbal83iag0azsrbymf9mhxgqghy6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."jinja2"
      self."nbconvert"
      self."nbformat"
      self."sphinx"
      self."traitlets"
    ];
  };
  "nest-asyncio" = super.buildPythonPackage rec {
    pname = "nest-asyncio";
    version = "1.5.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/1e/a83058de46b40a392bdefcaac44d1d42db4bf8562cb68c95d6bae4b93276/nest_asyncio-1.5.5-py3-none-any.whl";
      sha256 = "1chkb0h6hbb15jlidy1gr09ap8r3didgmvzc8935w4s6nb0kx3mr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "notebook" = super.buildPythonPackage rec {
    pname = "notebook";
    version = "6.4.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/b7/7e602dc8b868bba8a542269205237b400be3427d8489b5851de5f7587996/notebook-6.4.10-py3-none-any.whl";
      sha256 = "1pyldrjhljra23cc6gax2yn751j1b695f1zfnby4a2gz9f0svkj9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Send2Trash"
      self."argon2-cffi"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."nest-asyncio"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
  };
  "notebook-shim" = super.buildPythonPackage rec {
    pname = "notebook-shim";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/12/00c739649e40ec9dacd961c3198d87fd2dea2776f1df85e664d3e62ebe71/notebook_shim-0.1.0-py3-none-any.whl";
      sha256 = "092kwj3m62plf5za4wzc1ir19ijn5fm8h20hw8baqf8il1ajshq2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-server"
    ];
  };
  "orderedmultidict" = super.buildPythonPackage rec {
    pname = "orderedmultidict";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/16/5e95c70bda8fe6ea715005c0db8e602400bdba50ae3c72cb380eba551289/orderedmultidict-1.0.1-py2.py3-none-any.whl";
      sha256 = "1wyv9bw7rj4iywxqlryhl4n3z2jhm2hyqzf46hiddkg3gshkkj23";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "outcome" = super.buildPythonPackage rec {
    pname = "outcome";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/bb/f60ce97b304b1979d1fef96b6517af47b9bb026770b1f198b6e921b5edf5/outcome-1.1.0-py2.py3-none-any.whl";
      sha256 = "0n6ri1r5i0132l9lqv4rm9hs5c6lccxhl20xh2wjvhfkrxsr7pf7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "21.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl";
      sha256 = "08nmbgmf38nnxr99d5nlnacrr2jh1wp4xsi4ms1wgk8ryl2kw47g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
    ];
  };
  "pandocfilters" = super.buildPythonPackage rec {
    pname = "pandocfilters";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/a8/878258cffd53202a6cc1903c226cf09e58ae3df6b09f8ddfa98033286637/pandocfilters-1.5.0-py2.py3-none-any.whl";
      sha256 = "0kzidvgwpzdsc8hjhs9l7f0f1w4n4kavs9sxkw3jd86ibzrf7aik";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/63/8011bd08a4111858f79d2b09aad86638490d62fbf881c44e434a6dfca87b/parso-0.8.3-py2.py3-none-any.whl";
      sha256 = "0xcyw5sw2xjmxxw6fmaclzi4n2cvnpmhmd6b6fpwvbnkdiix80f0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pathspec" = super.buildPythonPackage rec {
    pname = "pathspec";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/ba/a9d64c7bcbc7e3e8e5f93a52721b377e994c22d16196e2b0f1236774353a/pathspec-0.9.0-py2.py3-none-any.whl";
      sha256 = "0flr3kf030h936favs62ackfln153bn1gi7gc78h5j5mn3fw85bx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pdbpp" = super.buildPythonPackage rec {
    pname = "pdbpp";
    version = "0.10.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/ee/491e63a57fffa78b9de1c337b06c97d0cd0753e88c00571c7b011680332a/pdbpp-0.10.3-py2.py3-none-any.whl";
      sha256 = "1lb5jv7y50cibi4k2zcgagjdh371adziicb2nkvddcrywdl0an3r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."fancycompleter"
      self."pygments"
      self."wmctrl"
    ];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl";
      sha256 = "0dq9f7irmml1nm9a2rx8dd6m2dqmzjj1x40mk0rg619wrdfsaj0b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "pickleshare" = super.buildPythonPackage rec {
    pname = "pickleshare";
    version = "0.7.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl";
      sha256 = "0mnzcb714ynl1qlv9dwnh50rv75mmj18ywaxbl8xzm3l9m0syjcn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "9.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4b/83/090146d7871d90a2643d469c319c1d014e41b315ab5cf0f8b4b6a764ef31/Pillow-9.1.0.tar.gz";
      sha256 = "15zvfl6yji2s4g8zfy6ksc4ijv2g3bdn7k0c2pg1lphmpcmys0gl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "plantweb" = super.buildPythonPackage rec {
    pname = "plantweb";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/6f/9ab1a1c3e33aaa0c0931983578c09336b092c75dce777ea666d3032f756e/plantweb-1.2.1-py3-none-any.whl";
      sha256 = "04va2k8fngzayr95753a6qy5h3qb7yx0br04jyyvqml3mghrqknj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."requests"
      self."six"
    ];
  };
  "platformdirs" = super.buildPythonPackage rec {
    pname = "platformdirs";
    version = "2.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/de/d8b9da351517c3dece273224522d4714cfdb9a89e2e6f7f7f054a340cc2b/platformdirs-2.5.1-py3-none-any.whl";
      sha256 = "09z2f5s522rjxrvfg3azwvmlycwkzd7b4w0vf4532b9wi6mprbmw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/01/f38e2ff29715251cf25532b9082a1589ab7e4f571ced434f98d0139336dc/pluggy-1.0.0-py2.py3-none-any.whl";
      sha256 = "1lvvnc39v43v5jawq2wz0765rg9lkx8f25l4sqv1l0vz8nzln4vl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ply" = super.buildPythonPackage rec {
    pname = "ply";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl";
      sha256 = "1kh7m0i2ghjhrbzi6a28yw3rcnzy5r2i4srls4pvspmna21rnvq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prometheus-client" = super.buildPythonPackage rec {
    pname = "prometheus-client";
    version = "0.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f7/81/bad2d4def4d010535c08459d4882c927968af12a9651d995aa4534f892b1/prometheus_client-0.14.0-py3-none-any.whl";
      sha256 = "1wh13lmali9g9p61w9vgnxx9n5bpn451yz2kkw254n3ks7ys7azl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "3.0.29";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/2d/dcb44d69f388ca2ee1a4a4d3c204ab66b36975c0d5166781eaeeff76b882/prompt_toolkit-3.0.29-py3-none-any.whl";
      sha256 = "0ll7qzjmglwk116hkx5hmy3215b95hs4x0fs1g55yrjy96nisab2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wcwidth"
    ];
  };
  "psutil" = super.buildPythonPackage rec {
    pname = "psutil";
    version = "5.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/47/b6/ea8a7728f096a597f0032564e8013b705aa992a0990becd773dcc4d7b4a7/psutil-5.9.0.tar.gz";
      sha256 = "09fa4vfhansixvxd3lv664xcrbnfdyfn53hm2wr0rf3bsvdl5646";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl";
      sha256 = "0dgg5x4nvdpfiz552diy11xg72y14s38hjz9qxygafnfgybg6hab";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pure-eval" = super.buildPythonPackage rec {
    pname = "pure-eval";
    version = "0.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/27/77f9d5684e6bce929f5cfe18d6cfbe5133013c06cb2fbf5933670e60761d/pure_eval-0.2.2-py3-none-any.whl";
      sha256 = "0l4k53n8rjxkgnx0jvayji5c97mkfjkf1sw0c32lp5406lsapsh1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py" = super.buildPythonPackage rec {
    pname = "py";
    version = "1.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/f0/10642828a8dfb741e5f3fbaac830550a518a775c7fff6f04a007259b0548/py-1.11.0-py2.py3-none-any.whl";
      sha256 = "0y5k0mjcr85i9xrd2wifc7gww596nq6dbz6d9bzpsr1jhwhm6z30";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycodestyle" = super.buildPythonPackage rec {
    pname = "pycodestyle";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/94/bc43a2efb7b8615e38acde2b6624cae8c9ec86faf718ff5676c5179a7714/pycodestyle-2.8.0-py2.py3-none-any.whl";
      sha256 = "084aaiv0p8n9rc6l8kyv0r014xrhbx3jrw3zbs197cp8vlwqn3vj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.21";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl";
      sha256 = "1agwca0hgbpwmr9snhxafqjhfd52mq083rw5n7vf25amallm9r4f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pydocstyle" = super.buildPythonPackage rec {
    pname = "pydocstyle";
    version = "6.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/67/4df10786068766000518c6ad9c4a614e77585a12ab8f0654c776757ac9dc/pydocstyle-6.1.1-py3-none-any.whl";
      sha256 = "1i2d2iq7ywiniss4jcfnf4ypxk08bkpvwh80jhwnh1bmcxnq51v9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."snowballstemmer"
    ];
  };
  "pyflakes" = super.buildPythonPackage rec {
    pname = "pyflakes";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/43/fb/38848eb494af7df9aeb2d7673ace8b213313eb7e391691a79dbaeb6a838f/pyflakes-2.4.0-py2.py3-none-any.whl";
      sha256 = "0bpf4ra3flqhlv6rscqjvxmy9p07zzj831vqkj69ddzlavra7crv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/17/ed4d2df187995561b28f1073df24137cb750e12f9879d291cc8ab67c65d2/Pygments-2.11.2-py3-none-any.whl";
      sha256 = "0r8wwjd08qwbvnlfcpr63h0swakh57j8wlm0iky7hvd7c0dqy8s4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pylama" = super.buildPythonPackage rec {
    pname = "pylama";
    version = "8.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/33/0b/c94dfa049b637f3032b64ff82b4d78c8e989b5e52563fc07bb35d8792596/pylama-8.3.8-py3-none-any.whl";
      sha256 = "0yrsbzfbi70xcq9x81nz7cz8g9c3z8vzkirqyq9qf4fyywir9y5g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pydocstyle"
      self."pyflakes"
    ];
  };
  "pylint" = super.buildPythonPackage rec {
    pname = "pylint";
    version = "2.13.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/53/e1d8da0d381e4a303cc812238e733073abdd9099525c42cb100b20faf8b9/pylint-2.13.5-py3-none-any.whl";
      sha256 = "07jdfrj73gk6jkh96vjysnkq3a479jwalvjy8si1mvpazm66jjf1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."astroid"
      self."dill"
      self."isort"
      self."mccabe"
      self."platformdirs"
      self."tomli"
      self."typing-extensions"
    ];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "3.0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/c1/23fd82ad3121656b585351aba6c19761926bb0db2ebed9e4ff09a43a3fcc/pyparsing-3.0.7-py3-none-any.whl";
      sha256 = "1164cc6c66qw9i9f1v7spm8kn88nid0qzbszyqic7rjjya46mh56";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrepl" = super.buildPythonPackage rec {
    pname = "pyrepl";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/1b/ea40363be0056080454cdbabe880773c3c5bd66d7b13f0c8b8b8c8da1e0c/pyrepl-0.9.0.tar.gz";
      sha256 = "0xd7h7k5cg9gd8nkqdykzkxmfasg8wwxcrmrpdqyh0jm9grp0999";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrsistent" = super.buildPythonPackage rec {
    pname = "pyrsistent";
    version = "0.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz";
      sha256 = "15pb8ry525h9z1670kzqi5915y004yjsrwsdf6x5awisk65izmnl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "7.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/ac/556e4410326ce77eeb1d1ec35a3e3ec847fb3e5cb30673729d2eeeffc970/pytest-7.1.1-py3-none-any.whl";
      sha256 = "1sk931m80zrypc1qx5knbj5c997c9y3q6r5hns073pcgk9w27xwj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."iniconfig"
      self."packaging"
      self."pluggy"
      self."py"
      self."tomli"
    ];
  };
  "pytest-runner" = super.buildPythonPackage rec {
    pname = "pytest-runner";
    version = "6.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/7b/1cec26caae4bf44bb9911e1119d5d1a35171571e100b728a2ccd8719a3b1/pytest_runner-6.0.0-py3-none-any.whl";
      sha256 = "0syad9jl8w00bzmivx3hsgx353xg3qyp13qgkhv6wc7l3kqrq1ac";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl";
      sha256 = "1aaxjfp4lrz8c6qls3vdhw554lan3khy9afyvdcvrssk6kf067cn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2022.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/2e/dec1cc18c51b8df33c7c4d0a321b084cf38e1733b98f9d15018880fb4970/pytz-2022.1-py2.py3-none-any.whl";
      sha256 = "0p3amik3hqpyi9y1x22a552n490614xikcqyi1madncnaac8b2g6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytz-deprecation-shim" = super.buildPythonPackage rec {
    pname = "pytz-deprecation-shim";
    version = "0.1.0.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/73/3eaab547ca809754e67e06871cff0fc962bafd4b604e15f31896a0f94431/pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl";
      sha256 = "19n1znh7a5n3h07fg0xf4crfjl7337qvjyd8pnrqwv3359lwj543";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."tzdata"
    ];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz";
      sha256 = "18imkjacvpxfgg1lbpraqywx3j7hr5dv99d242byqvrh2jf53yv8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "22.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/95/d37e7db364d7f569e71068882b1848800f221c58026670e93a4c6d50efe7/pyzmq-22.3.0.tar.gz";
      sha256 = "0737kizh53n4rjq1xbm6nhr0bq65xflg04i1d8fcky0nwwrw1pcf";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qtconsole" = super.buildPythonPackage rec {
    pname = "qtconsole";
    version = "5.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/93/ec753e8960dfb0342508cdcb26f9ff8d9fb1bdb320d2a348fc92c83865ee/qtconsole-5.3.0-py3-none-any.whl";
      sha256 = "03svj0q2ix9xgimi2lsa7bdm6fz394hjclssrgnm8i24fvcdxwkm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."pyzmq"
      self."qtpy"
      self."traitlets"
    ];
  };
  "qtpy" = super.buildPythonPackage rec {
    pname = "qtpy";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/b0/56e602873b05108f0ef9189a237fefcfbcd2fa3d84130b59e50c84fc90e8/QtPy-2.0.1-py3-none-any.whl";
      sha256 = "04j8scxagndsvz2z9yfqp5dc3dpm59vhkm93sv4zr1vkx6c2qgyr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.27.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/61/08076519c80041bc0ffa1a8af0cbd3bf3e2b62af10435d269a9d0f40564d/requests-2.27.1-py2.py3-none-any.whl";
      sha256 = "0bg7c13nfm400gx7wn5kjbjfjyz1b6bwf6p4wqbgvpf9akjs2bzj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "rfc3987" = super.buildPythonPackage rec {
    pname = "rfc3987";
    version = "1.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/d4/f7407c3d15d5ac779c3dd34fbbc6ea2090f77bd7dd12f207ccf881551208/rfc3987-1.3.8-py2.py3-none-any.whl";
      sha256 = "0lyf5pysj3hv249nywgz9k7x4rh3bhc9n60b8r1qhrg5a4g2nw0h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "rise" = super.buildPythonPackage rec {
    pname = "rise";
    version = "5.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/e7/91ddb742829723d9746dc12c5c5d0511d34d6c8e378fa2bdf1e17c68a3d7/rise-5.7.1-py2.py3-none-any.whl";
      sha256 = "0fmfivwymkl526w8p1cm95xrz3f7lj8iy2plgyr39lvmwpqfk36z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "robotframework" = super.buildPythonPackage rec {
    pname = "robotframework";
    version = "5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/c6/f5e03282969db2fb8a15fd56df1b04e6191eb32af767f00ac0fdf05441fc/robotframework-5.0-py3-none-any.whl";
      sha256 = "0lwgzxv6bbflkcb4mpzyzjnirf55q8x5n7gcyjyc8bayi0v2d4gf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robotframework-faker" = super.buildPythonPackage rec {
    pname = "robotframework-faker";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/53/27/e51e1ab454b0d207a86cd6395b663da0f524f5aba54a4126fee342cd8e47/robotframework_faker-5.0.0-py3-none-any.whl";
      sha256 = "1qrjg6sp4cl1dajvvrq81v0k74lg0qhzzb6cd72rl3dgihwvqw9l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."faker"
      self."robotframework"
      self."wrapt"
    ];
  };
  "robotframework-jupyterlibrary" = super.buildPythonPackage rec {
    pname = "robotframework-jupyterlibrary";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/71/6e153f435688c0871e6329161846360bdc12e3bfdcb0a5afa82392e774e1/robotframework_jupyterlibrary-0.4.0-py3-none-any.whl";
      sha256 = "1vgnrmdw4c2j0ppirab16z4dmilmix5n1rh64hqkawsvhb99krw0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework"
      self."robotframework-seleniumlibrary"
    ];
  };
  "robotframework-pythonlibcore" = super.buildPythonPackage rec {
    pname = "robotframework-pythonlibcore";
    version = "3.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/eb/0c4896a33fe1209a28e82a41fed1b605e76b87629a880cb526fa4073c3fb/robotframework_pythonlibcore-3.0.0-py2.py3-none-any.whl";
      sha256 = "1i5pb5y3fhyl6vwfqffds95v3yf6dvxqzrjcijc3926k7i0c445g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumlibrary";
    version = "6.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/ef/54451370c8629236db9bc0b9294f91818da16670dc70d973cea07cbe8c8d/robotframework_seleniumlibrary-6.0.0-py2.py3-none-any.whl";
      sha256 = "07g3k066p279byq04zds07pk1dmzg0fz2nq079fm40bginyal9c8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework"
      self."robotframework-pythonlibcore"
      self."selenium"
    ];
  };
  "robotframework-seleniumscreenshots" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumscreenshots";
    version = "0.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/74/bc74ab673111c889055f2b91d99c23092ce24edd4c92f674500ddf0744c9/robotframework_seleniumscreenshots-0.9.5-py3-none-any.whl";
      sha256 = "1kay5j7mhflbv1pnvzcq5s7b88hbxa8bk6gx4dxvlhngxrcnsm39";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework"
      self."robotframework-seleniumlibrary"
      self."setuptools"
    ];
  };
  "robotframework-seleniumtestability" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumtestability";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/9b/0af1de2d761021f42b18265060e9ed998ae4e2fbd01e9970e86c32e50afc/robotframework_seleniumtestability-2.0.0-py3-none-any.whl";
      sha256 = "1x9d45dp5zb5307yaldraw0gk23n2la6q7gk7azdppka1zgm8fhd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."furl"
      self."robotframework-seleniumlibrary"
      self."wrapt"
    ];
  };
  "selenium" = super.buildPythonPackage rec {
    pname = "selenium";
    version = "4.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/58/76/705b5c776f783d1ba7c630347463d4ae323282bbd859a8e9420c7ff79581/selenium-4.1.0-py3-none-any.whl";
      sha256 = "0fd9q47bjbrkkvng4f6h4azbnfhjvyhcldvjsprhkmk1z56vdrr7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."trio"
      self."trio-websocket"
      self."urllib3"
    ];
  };
  "setuptools-scm" = super.buildPythonPackage rec {
    pname = "setuptools-scm";
    version = "6.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/e5/c28b544051340e63e0d507eb893c9513d3a300e5e9183e2990518acbfe36/setuptools_scm-6.4.2-py3-none-any.whl";
      sha256 = "1m7nvndi74vsxzlwwl1lg1kp1plbzghzj6mirkkrv14ka0ji7smc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."packaging"
      self."setuptools"
      self."tomli"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sniffio" = super.buildPythonPackage rec {
    pname = "sniffio";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/b0/7b2e028b63d092804b6794595871f936aafa5e9322dcaaad50ebf67445b3/sniffio-1.2.0-py3-none-any.whl";
      sha256 = "0qznm5f0zg3n6vnkwjm54968397ln8mpbqhclh92275cirlp26s7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "snowballstemmer" = super.buildPythonPackage rec {
    pname = "snowballstemmer";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/dc/c02e01294f7265e63a7315fe086dd1df7dacb9f840a804da846b96d01b96/snowballstemmer-2.2.0-py2.py3-none-any.whl";
      sha256 = "06msxjb0qpqgj07zp1drqv19y3afw0m5gr94d3hqlffchdp73qf8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sortedcontainers" = super.buildPythonPackage rec {
    pname = "sortedcontainers";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl";
      sha256 = "1q3y4gdrb1d3595sxqlpk0j783hr8n9a6mz9hla0470gvspdqqx1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "soupsieve" = super.buildPythonPackage rec {
    pname = "soupsieve";
    version = "2.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/1e/294d3cb3fc81212914043beba5eeb38882c0b449402353c549745e823fcf/soupsieve-2.3.2-py3-none-any.whl";
      sha256 = "198qzzk4sz8flahqkhijhcvqnm80fc0b2ip3bg71gv1162fi4557";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinx" = super.buildPythonPackage rec {
    pname = "sphinx";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/91/96/9cbbc7103fb482d5809fe4976ecb9b627058210d02817fcbfeebeaa8f762/Sphinx-4.5.0-py3-none-any.whl";
      sha256 = "09k278ykiismhbv317axszyydva4rsvsj9wn6pscig1q69ji5xpb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."alabaster"
      self."babel"
      self."docutils"
      self."imagesize"
      self."importlib-metadata"
      self."jinja2"
      self."packaging"
      self."pygments"
      self."requests"
      self."snowballstemmer"
      self."sphinxcontrib-applehelp"
      self."sphinxcontrib-devhelp"
      self."sphinxcontrib-htmlhelp"
      self."sphinxcontrib-jsmath"
      self."sphinxcontrib-qthelp"
      self."sphinxcontrib-serializinghtml"
    ];
  };
  "sphinx-rtd-theme" = super.buildPythonPackage rec {
    pname = "sphinx-rtd-theme";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/d2/3818e4730e314719e27f639c44164419e40eed826d63753dc480262036e8/sphinx_rtd_theme-1.0.0-py2.py3-none-any.whl";
      sha256 = "1n6vdx4w7xcy80zm67bk0siy5skgvqz3f15n9x6fxkq88mpsadad";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."sphinx"
    ];
  };
  "sphinxcontrib-applehelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-applehelp";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/47/86022665a9433d89a66f5911b558ddff69861766807ba685de2e324bd6ed/sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl";
      sha256 = "0nl8mw0kxd0544ws9c9gcplikzbv4zzfghf4kv19ggk2x7ji2qc0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-devhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-devhelp";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/09/5de5ed43a521387f18bdf5f5af31d099605c992fd25372b2b9b825ce48ee/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl";
      sha256 = "0bjafgjc3lbw9h6bq8q49hjjbwvi50fx67pygypw2p1kk8zj4rc1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-htmlhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-htmlhelp";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/40/c854ef09500e25f6432dcbad0f37df87fd7046d376272292d8654cc71c95/sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl";
      sha256 = "01zdqq30si8yhvmy9w0v4idff4mc5pjs1v2r5gnf6ykrzcyj84nl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-jsmath" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-jsmath";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl";
      sha256 = "0y1i21qwi5p5f98jxds8r1n12yj12la6nrkkiq3z5wvqzgmymhif";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-qthelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-qthelp";
    version = "1.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/14/05f9206cf4e9cfca1afb5fd224c7cd434dcc3a433d6d9e4e0264d29c6cdb/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl";
      sha256 = "1dps9m29ay339v0shix314qac2imh7kavjjfzm8qv2klrd5w57xx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-serializinghtml" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-serializinghtml";
    version = "1.1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/77/5464ec50dd0f1c1037e3c93249b040c8fc8078fdda97530eeb02424b6eea/sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl";
      sha256 = "1zcjkfcjisxrgs3fk59zidzbbh2zkzbxgn7alz9p2i46mq09laim";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "stack-data" = super.buildPythonPackage rec {
    pname = "stack-data";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6b/25/9a454b432df53ffbbb4f03198c3347f393c34f4de07fb652563bdbdf91e8/stack_data-0.2.0-py3-none-any.whl";
      sha256 = "13l5xl188pa89lgqa4c3yxxr9gmvf693x87zk9w0h8qkqgwn55wr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."asttokens"
      self."executing"
      self."pure-eval"
    ];
  };
  "strict-rfc3339" = super.buildPythonPackage rec {
    pname = "strict-rfc3339";
    version = "0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "terminado" = super.buildPythonPackage rec {
    pname = "terminado";
    version = "0.13.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/87/a6f72009fa1c6528fd016a199f5f0199841e82e72d726f55a6a96fcc6b30/terminado-0.13.3-py3-none-any.whl";
      sha256 = "1n0bfv475jfb54q66lqxxvjz837g889wkiqk5mwc2dim32ilwkc7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
  };
  "testpath" = super.buildPythonPackage rec {
    pname = "testpath";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/43/1ebfb29c2ca1df2bdb33dbcb2b526b77ee96873ba7b9e25650ddd4ae7156/testpath-0.6.0-py3-none-any.whl";
      sha256 = "0fd6dzz71rfxfhzsivckyqlq9yhws6kv3kd738wv0vxcla09znla";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "text-unidecode" = super.buildPythonPackage rec {
    pname = "text-unidecode";
    version = "1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/a5/c0b6468d3824fe3fde30dbb5e1f687b291608f9473681bbf7dabbf5a87d7/text_unidecode-1.3-py2.py3-none-any.whl";
      sha256 = "1s12m0s73djhjcc1i2w8hx94ak2glqmiqwr32qj3anc9ic7g248k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "toml" = super.buildPythonPackage rec {
    pname = "toml";
    version = "0.10.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl";
      sha256 = "16sgpg57kxx5jh467d9qwc2hwshfvdbl0xkafdp3qspvbfp46qc0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl";
      sha256 = "1k0fqfdylinb57s2aqwprahwbrsk3babg4gghz4g06hnlvky77ck";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/44/cc9590db23758ee7906d40cacff06c02a21c2a6166602e095a56cbf2f6f6/tornado-6.1.tar.gz";
      sha256 = "14cpzdv6p6qvk6vn02krdh5rcfdi174ifdbr5s6lcnymgcfyiiik";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "traitlets" = super.buildPythonPackage rec {
    pname = "traitlets";
    version = "5.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/37/46/be8a3c030bd3673f4800fa7f46eda972dfa2990089a51ec5dd0a26ed33e9/traitlets-5.1.1-py3-none-any.whl";
      sha256 = "0cq0gqknc6kvmrk8gxqmqai0dpgyszachzbxgqknrka21b2kqc9d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "trio" = super.buildPythonPackage rec {
    pname = "trio";
    version = "0.20.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/b3/c6fc163c9343e95432d60a2b681bc14d78fda70dff50210687314d94143d/trio-0.20.0-py3-none-any.whl";
      sha256 = "06kwsxsslgfrp80c6fr0bd2f6wfwm9553kbjlj3bgpxhxbj4hbgv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-generator"
      self."attrs"
      self."idna"
      self."outcome"
      self."sniffio"
      self."sortedcontainers"
    ];
  };
  "trio-websocket" = super.buildPythonPackage rec {
    pname = "trio-websocket";
    version = "0.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/c5/b5e8bc1f40568a354f2a9cc296b8892605a9d2f22e725290fc33836dd2a3/trio_websocket-0.9.2-py3-none-any.whl";
      sha256 = "1g6jgvikf0sf6r1mbmkvypfilp99qmv288317dya686chdp8ymav";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-generator"
      self."trio"
      self."wsproto"
    ];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl";
      sha256 = "1qlcz26kwq9hnpccn336b7iygp0wfjnv0c4lg785b8drwh7mxj11";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tzdata" = super.buildPythonPackage rec {
    pname = "tzdata";
    version = "2022.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/2d/49329ebec33b14dae61ecc8c85abe596341832fa36c4bcd3d99fddda018b/tzdata-2022.1-py2.py3-none-any.whl";
      sha256 = "1f9a1ri0gi4qh6mqdr9vmgnp4f71wnqgm878nkbqw4ql88ip13i3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tzlocal" = super.buildPythonPackage rec {
    pname = "tzlocal";
    version = "4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/b7/3bc2c1868f27677139b772e4fde95265b93151912fd90eb874827943bfcf/tzlocal-4.2-py3-none-any.whl";
      sha256 = "0i9p0km67i3pbhid7kg5kdbpmj5g09ss4yn5j68rv4jcd2a59249";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz-deprecation-shim"
    ];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/03/062e6444ce4baf1eac17a6a0ebfe36bb1ad05e1df0e20b110de59c278498/urllib3-1.26.9-py2.py3-none-any.whl";
      sha256 = "051c8x2xchkhcrvagwzw4p4jx6j6ym4cdlcvgik6yw5i7zay9v24";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "validate-email" = super.buildPythonPackage rec {
    pname = "validate-email";
    version = "1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/a0/cb53fb64b52123513d04f9b913b905f3eb6fda7264e639b4573cc715c29f/validate_email-1.3.tar.gz";
      sha256 = "1bxffaf5yz2cph8ki55vdvdypbwkvn2xr1firlcy62vqbzf1jivq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.2.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl";
      sha256 = "1177pfa343r378020a85l3b16ak479qgyvh8k5719fgbkhm81d5y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "webencodings" = super.buildPythonPackage rec {
    pname = "webencodings";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl";
      sha256 = "0y2aa53jkkcszhbbx59z817ywjvy3ah3lavym6bn88n2yc9i5bx0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "websocket-client" = super.buildPythonPackage rec {
    pname = "websocket-client";
    version = "1.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/9e/8ddb04ef21ea3dfe3924b884dc11fa785df662af23e049ec2d62eaba707d/websocket_client-1.3.2-py3-none-any.whl";
      sha256 = "1vyhcl9lwalpkks8znmiininqlva2i9jnbzvskhr0aqgw0difavj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "widgetsnbextension" = super.buildPythonPackage rec {
    pname = "widgetsnbextension";
    version = "3.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4e/69/273f584c28805939c6cb45717638cb8edbd78147f02c564b8c7763e1872e/widgetsnbextension-3.6.0-py2.py3-none-any.whl";
      sha256 = "1gga9kay0wzhc0zxvmcfivd7m4a25lh5g9j8walgip4zsg523lsg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "wmctrl" = super.buildPythonPackage rec {
    pname = "wmctrl";
    version = "0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/48/bd9b5c4c0d865e5d143f91020600f921c37f9755c8101336d292e1de1252/wmctrl-0.4.tar.gz";
      sha256 = "1q0l1sqnj5wma87k3dsgmsyph464syjc6fl8qcpa41nan1rgzjv6";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/b4/3a937c7f8ee4751b38274c8542e02f42ebf3e080f1344c4a2aff6416630e/wrapt-1.14.0.tar.gz";
      sha256 = "048k4rl7xi8mi3z7pqi0z1z0w28hzz4lrrsbgnxn47y9v4xs88w3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wsproto" = super.buildPythonPackage rec {
    pname = "wsproto";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4b/6e/5f8c3e8418966f50d028e336f0c2c568f8522577183678923609d4d24924/wsproto-1.1.0-py3-none-any.whl";
      sha256 = "06sjgbjf4j7h2w50n1yqiwzakgf313xxrh15lgybk41djmbwn612";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."h11"
    ];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/0e/16a7ee38617aab6a624e95948d314097cc2669edae9b02ded53309941cfc/zipp-3.8.0-py3-none-any.whl";
      sha256 = "16ghbifm4cl9s5jdamw92zjhlazl1x4b1ibwisizfx4fyjxybxn4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
