# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Appium-Python-Client" = super.buildPythonPackage {
    name = "Appium-Python-Client-0.28";
    doCheck = false;
    propagatedBuildInputs = [
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/f4/b31229c97ecd03015f2e2abd79ee998f0b91977062d559270abda9f1f3fe/Appium-Python-Client-0.28.tar.gz";
      sha256 = "1v7zyibj1nb92wj39gmyxqkgqsnxnxq0485s8rh3846v1id953qd";
    };
  };
  "GenSON" = super.buildPythonPackage {
    name = "GenSON-1.0.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/ed/4b249d723b330e5856ab1c2f09dfa298f997630fa2bc5cfb50247cf1d8d2/genson-1.0.1.tar.gz";
      sha256 = "1p22pks22rkc7wdl2xpki1s0s4drp4km4z0nihkd40p8dmiihch0";
    };
  };
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz";
      sha256 = "0rdn1s8x9ni7ss8rfiacj7x1085lx8mh2zdwqslnw8xc3l4nkgm6";
    };
  };
  "PyYAML" = super.buildPythonPackage {
    name = "PyYAML-3.13";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz";
      sha256 = "1gx603g484z46cb74j9rzr6sjlh2vndxayicvlyhxdz98lhhkwry";
    };
  };
  "RESTinstance" = super.buildPythonPackage {
    name = "RESTinstance-1.0.0b35";
    doCheck = false;
    propagatedBuildInputs = [
      self."GenSON"
      self."flex"
      self."jsonpath-ng"
      self."jsonschema"
      self."pygments"
      self."pytz"
      self."requests"
      self."rfc3987"
      self."robotframework"
      self."strict-rfc3339"
      self."tzlocal"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/4e/554ff115a5e6ecabc69720bb55ad1d47c753179cc21fbbc5ef71715b4f15/RESTinstance-1.0.0b35.tar.gz";
      sha256 = "0xwcbll1c0dd3s9hd60l7z9qz9zjby5754d8w1fjxjj3bfi05hd6";
    };
  };
  "Send2Trash" = super.buildPythonPackage {
    name = "Send2Trash-1.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/2e/ea40de0304bb1dc4eb309de90aeec39871b9b7c4bd30f1a3cdcb3496f5c0/Send2Trash-1.5.0.tar.gz";
      sha256 = "1ci8vcwjmjlp11ljj1ckrfmml9fkq1mclx2gr53y4zvhgp01q030";
    };
  };
  "alabaster" = super.buildPythonPackage {
    name = "alabaster-0.7.12";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/b4/ed8dcb0d67d5cfb7f83c4d5463a7614cb1d078ad7ae890c9143edebbf072/alabaster-0.7.12.tar.gz";
      sha256 = "00nwwjj2d2ym4s2kk217x7jkx1hnczc3fvm8yxbqmsp6b0nxfqd6";
    };
  };
  "atomicwrites" = super.buildPythonPackage {
    name = "atomicwrites-1.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/ed/a311712ef6b4355035489f665e63e1a73f9eb371929e3c98e5efd451069e/atomicwrites-1.2.1.tar.gz";
      sha256 = "1vmkbw9j0qammwxbxycrs39gvdg4lc2d4lk98kwf8ag2manyi6pc";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-18.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0f/9e/26b1d194aab960063b266170e53c39f73ea0d0d3f5ce23313e0ec8ee9bdf/attrs-18.2.0.tar.gz";
      sha256 = "0s9ydh058wmmf5v391pym877x4ahxg45dw6a0w4c7s5wgpigdjqh";
    };
  };
  "babel" = super.buildPythonPackage {
    name = "babel-2.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/cc/9c981b249a455fa0c76338966325fc70b7265521bad641bf2932f77712f4/Babel-2.6.0.tar.gz";
      sha256 = "08rxmbx2s4irp0w0gmn498vns5xy0fagm0fg33xa772jiks51flc";
    };
  };
  "backcall" = super.buildPythonPackage {
    name = "backcall-0.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-2.1.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."html5lib"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/b7/fa555afb61462b030abaf9ed1479b8ea031510f58c7706b06113be9f82ea/bleach-2.1.4.tar.gz";
      sha256 = "1n337zbdml6z6zia0b1qgv6xiddx3qlwmcg9vk2mk60jcxhmzs8f";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2018.8.24";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/0f/f8d5e939184547b3bdc6128551b831a62832713aa98c2ccdf8c47ecc7f17/certifi-2018.8.24.tar.gz";
      sha256 = "0f0nhrj9mlrf79iway4578wrsgmjh0fmacl9zv8zjckdy7b90rip";
    };
  };
  "cffi" = super.buildPythonPackage {
    name = "cffi-1.11.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."pycparser"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz";
      sha256 = "1x3lrj928dcxx1k8k9gf3s4s3jwvzv8mc3kkyg1g7c3a1sc1f3z9";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "check-manifest" = super.buildPythonPackage {
    name = "check-manifest-0.37";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/ac/67d065556adcad8144cb51e9d8848006dc3a9f5da7491faaf7db6374e301/check-manifest-0.37.tar.gz";
      sha256 = "0lk45ifdv2cpkl6ayfyix7jwmnxa1rha7xvb0ih5999k115wzqs4";
    };
  };
  "click" = super.buildPythonPackage {
    name = "click-6.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/d9/c3336b6b5711c3ab9d1d3a80f1a3e2afeb9d8c02a7166462f6cc96570897/click-6.7.tar.gz";
      sha256 = "02qkfpykbq35id8glfgwc38yc430427yd05z1wc5cnld8zgicmgi";
    };
  };
  "cmarkgfm" = super.buildPythonPackage {
    name = "cmarkgfm-0.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."cffi"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e2/a3/4021fbc17c5afe7f307d14eba0d6899a8e66b351ab65649b1c89c50a836d/cmarkgfm-0.4.2.tar.gz";
      sha256 = "0350y5z5qggp7lyiqn9rhj0301f89g9li4xfhfbi1wkpcgqh02gj";
    };
  };
  "colorama" = super.buildPythonPackage {
    name = "colorama-0.3.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/76/257b53926889e2835355d74fec73d82662100135293e17d382e2b74d1669/colorama-0.3.9.tar.gz";
      sha256 = "1wd1szk0z3073ghx26ynw43gnc140ibln1safgsis6s6z3s25ss8";
    };
  };
  "coverage" = super.buildPythonPackage {
    name = "coverage-4.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/35/fe/e7df7289d717426093c68d156e0fd9117c8f4872b6588e8a8928a0f68424/coverage-4.5.1.tar.gz";
      sha256 = "1wbrzpxka3xd4nmmkc6q0ir343d91kymwsm8pbmwa0d2a7q4ir2n";
    };
  };
  "decorator" = super.buildPythonPackage {
    name = "decorator-4.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/24/15a229626c775aae5806312f6bf1e2a73785be3402c0acdec5dbddd8c11e/decorator-4.3.0.tar.gz";
      sha256 = "0308djallnh00v112y5b7nadl657ysmkp6vc8xn51d6yzc9zm7n3";
    };
  };
  "defusedxml" = super.buildPythonPackage {
    name = "defusedxml-0.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/ba/4ba4e89e21b5a2e267d80736ea674609a0a33cc4435a6d748ef04f1f9374/defusedxml-0.5.0.tar.gz";
      sha256 = "1x54n0h8hl92vvwyymx883fbqpqjwn2mc8fb383bcg3z9zwz5mr4";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "entrypoints" = super.buildPythonPackage {
    name = "entrypoints-0.2.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/e8/607697e6ab8a961fc0b141a97ea4ce72cd9c9e264adeb0669f6d194aa626/entrypoints-0.2.3.tar.gz";
      sha256 = "17q21k8igjb47b73jn4w6lgzza1nscn3sf1sn5gm96bgw3fqgmfj";
    };
  };
  "faker" = super.buildPythonPackage {
    name = "faker-0.9.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."python-dateutil"
      self."six"
      self."text-unidecode"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/87/3dc0e705e72f6e414067fb114347c5295525847d7c745521491691ecc699/Faker-0.9.1.tar.gz";
      sha256 = "0n3pznvh0hjq15khica2hqy4cqi5adbxf1k04y9d7rk1hgfl5kn2";
    };
  };
  "flake8" = super.buildPythonPackage {
    name = "flake8-3.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pyflakes"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/ab/7730f6d6cdf73a3b7f98a2fe3b2cdf68e9e760a4a133e083607497d4c3a6/flake8-3.5.0.tar.gz";
      sha256 = "184b33grvvjmiwlv9kyd7yng9qv5ld24154j70z332xxg9gjclvj";
    };
  };
  "flake8-blind-except" = super.buildPythonPackage {
    name = "flake8-blind-except-0.1.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/f2/ab635e6e420e78c94eab50cd3f53abd3ec27e411793e50b14f29edbb9f0b/flake8-blind-except-0.1.1.tar.gz";
      sha256 = "16g58mkr3fcn2vlfhp3rlahj93qswc7jd5qrqp748mc26dk3b8xc";
    };
  };
  "flake8-coding" = super.buildPythonPackage {
    name = "flake8-coding-1.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/d7/889f7961ed549f15a280fa36edfc9b9016df38cd25cd0a8a7e4edc06efcf/flake8-coding-1.3.1.tar.gz";
      sha256 = "0i7qh5wmwh5bgf1lgi82nq2n6qks2jgv8pvr27dgw4c7q0i2p72l";
    };
  };
  "flake8-commas" = super.buildPythonPackage {
    name = "flake8-commas-2.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/6b/a64cb3469543ec48f55287c4736c5430801e49ca4810c3e2124755bd9e5c/flake8-commas-2.0.0.tar.gz";
      sha256 = "1ds41zg7bfcmi5m2qjjg1xm6dv5gb7xm2wfzhw1khlbg8scmh06k";
    };
  };
  "flake8-debugger" = super.buildPythonPackage {
    name = "flake8-debugger-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
      self."pycodestyle"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/4b/90548607282483dd15f9ce1f4434d735ae756e16e1faf60621b0f8877fcc/flake8-debugger-3.1.0.tar.gz";
      sha256 = "15qxrb2d7sr0pf024fkknsx58aqa5iz38b9s0panv3zfwf6vhkxy";
    };
  };
  "flake8-polyfill" = super.buildPythonPackage {
    name = "flake8-polyfill-1.0.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/67/1c26634a770db5c442e361311bee73cb3a177adb2eb3f7af8953cfd9f553/flake8-polyfill-1.0.2.tar.gz";
      sha256 = "1nlf1mkqw856vi6782qcglqhaacb23khk9wkcgn55npnjxshhjz4";
    };
  };
  "flake8-quotes" = super.buildPythonPackage {
    name = "flake8-quotes-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/ff/0461010959158bb7d197691c696f1a85b20f2d3eea7aa23f73a8d07f30f3/flake8-quotes-1.0.0.tar.gz";
      sha256 = "09ib440hrf5bbsmdbqzbcpkkqqnqdwkaawbqz93bbwxwifnjg4gx";
    };
  };
  "flex" = super.buildPythonPackage {
    name = "flex-6.12.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."PyYAML"
      self."click"
      self."jsonpointer"
      self."requests"
      self."rfc3987"
      self."six"
      self."strict-rfc3339"
      self."validate-email"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/03/d9d4bd3852bc259b31519ff939c3758b488136dfa65a6b02472c97a930a7/flex-6.12.0.tar.gz";
      sha256 = "17hh61ri7lspkq49rqpjy5djrpxmj2an7nwk3kwaw1yaxxakqwf7";
    };
  };
  "future" = super.buildPythonPackage {
    name = "future-0.16.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz";
      sha256 = "1nzy1k4m9966sikp0qka7lirh8sqrsyainyf8rk97db7nwdfv773";
    };
  };
  "html5lib" = super.buildPythonPackage {
    name = "html5lib-1.0.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/3e/cf449cf1b5004e87510b9368e7a5f1acd8831c2d6691edd3c62a0823f98f/html5lib-1.0.1.tar.gz";
      sha256 = "0dipzfrycv6j1jw82v9b7d8lzggx3x8xngx6l4xrqkxwvg7hvjv6";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/bd/0467d62790828c23c47fc1dfa1b1f052b24efdf5290f071c7a91d0d82fd3/idna-2.6.tar.gz";
      sha256 = "13qaab6d0s15gknz8v3zbcfmbj6v86hn9pjxgkdf62ch13imssic";
    };
  };
  "imagesize" = super.buildPythonPackage {
    name = "imagesize-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/f5/3cf63735d54aa9974e544aa25858d8f9670ac5b4da51020bbfc6aaade741/imagesize-1.1.0.tar.gz";
      sha256 = "1dg3wn7qpwmhgqc0r9na2ding1wif9q5spz3j9zn2riwphc2k0zk";
    };
  };
  "ipykernel" = super.buildPythonPackage {
    name = "ipykernel-4.9.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/2d/1e9860d470725ef22a2c06c15d082ca06d425e91eba1a1292bb0165af128/ipykernel-4.9.0.tar.gz";
      sha256 = "1ym5izryjcxpzd68w8g0yjzgamwh0qxr9kwp6d7w6rbp1z3ri965";
    };
  };
  "ipython" = super.buildPythonPackage {
    name = "ipython-6.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."simplegeneric"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/76/0b51dc7dd3a801477d00e6db065f50cce9fe5bdbea3c911fce62c9f02c23/ipython-6.5.0.tar.gz";
      sha256 = "196m8y4wjll0bwk29zahbh1l1j1m9zg6s2z17vv8x9m4mngfzwmh";
    };
  };
  "ipython-genutils" = super.buildPythonPackage {
    name = "ipython-genutils-0.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz";
      sha256 = "1a4bc9y8hnvq6cp08qs4mckgm6i6ajpndp4g496rvvzcfmp12bpb";
    };
  };
  "ipywidgets" = super.buildPythonPackage {
    name = "ipywidgets-7.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/8d/c5d3ac1bdcd74c7327c733c9d02354ff12d7d72744f262ed1e26560962b2/ipywidgets-7.4.2.tar.gz";
      sha256 = "18qbvygzii06ygwnrgjbqaqcmnssqlph96mb8xq7cgqn63s29qm3";
    };
  };
  "isort" = super.buildPythonPackage {
    name = "isort-4.3.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/de/a628d16fdba0d38cafb3d7e34d4830f2c9cb3881384ce5c08c44762e1846/isort-4.3.4.tar.gz";
      sha256 = "1y0yfv56cqyh9wyg7kxxv9y5wmfgcq18n7a49mp7xmzka2bhxi5r";
    };
  };
  "jedi" = super.buildPythonPackage {
    name = "jedi-0.12.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."parso"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/2f/cdfb8adc8cfc9fc2e5673e724d9b9098619dc1a2772cc6b8af34c6b7bef9/jedi-0.12.1.tar.gz";
      sha256 = "1h8ypnjisn57kiv1zqrkj1im6sbfnhxllqaa8znh39qkd47ys2dl";
    };
  };
  "jinja2" = super.buildPythonPackage {
    name = "jinja2-2.10";
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e6/332789f295cf22308386cf5bbd1f4e00ed11484299c5d7383378cf48ba47/Jinja2-2.10.tar.gz";
      sha256 = "190l36hfw3wb2n3n68yacjabxyb1pnxwn7vjx96cmjj002xy2jzq";
    };
  };
  "jsonpath-ng" = super.buildPythonPackage {
    name = "jsonpath-ng-1.4.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/f3/cd8f8a0bb345985b83e76721e6f64222f92f34a217a4e9720f70427a1b4c/jsonpath-ng-1.4.3.tar.gz";
      sha256 = "1gphkq565nq2bms9mha5gir9q38gzgfgnmd48mlg9cp9fyw7bz5i";
    };
  };
  "jsonpointer" = super.buildPythonPackage {
    name = "jsonpointer-2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/e7/246d9ef2366d430f0ce7bdc494ea2df8b49d7a2a41ba51f5655f68cfe85f/jsonpointer-2.0.tar.gz";
      sha256 = "0qjkjy1qlyc1nl3k95wd03ssxac0a717x8889ypgs1cfcj3bm4n1";
    };
  };
  "jsonschema" = super.buildPythonPackage {
    name = "jsonschema-2.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/58/b9/171dbb07e18c6346090a37f03c7e74410a1a56123f847efed59af260a298/jsonschema-2.6.0.tar.gz";
      sha256 = "00kf3zmpp9ya4sydffpifn0j0mzm342a2vzh82p6r0vh10cg7xbg";
    };
  };
  "jupyter" = super.buildPythonPackage {
    name = "jupyter-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
  };
  "jupyter-client" = super.buildPythonPackage {
    name = "jupyter-client-5.2.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/df/1e8df7f4de63cc667a7a9aa234539c0419513bf94ac57d36d73b3b434786/jupyter_client-5.2.3.tar.gz";
      sha256 = "0qdpcqs7r8fw38mjbqllgxyss0fi5n86lk81afcf40bb8kqgrgi7";
    };
  };
  "jupyter-console" = super.buildPythonPackage {
    name = "jupyter-console-5.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/bb/fa8901715c009a00ea4c42897da8585189d4781c64f4617a8bd65ca01a3a/jupyter_console-5.2.0.tar.gz";
      sha256 = "1kam1qzgwr7srhm5r6aj90di5sws4bq0jmiw15452ddamb9yspal";
    };
  };
  "jupyter-core" = super.buildPythonPackage {
    name = "jupyter-core-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b6/2d/2804f4de3a95583f65e5dcb4d7c8c7183124882323758996e867f47e72af/jupyter_core-4.4.0.tar.gz";
      sha256 = "1dy083rarba8prn9f9srxq3c7n7vyql02ycrqq306c40lr57aw5s";
    };
  };
  "jupyterlab" = super.buildPythonPackage {
    name = "jupyterlab-0.34.12";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyterlab-launcher"
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/cb/1b3fe08b58765e11abbbfaa9acfaa8629404236bf9c0f43c1e7b17b56fb4/jupyterlab-0.34.12.tar.gz";
      sha256 = "11ygiqb8cd0m3ai6smgfnw8b8a3qqfbbjga93blp7q8akb8pi0vx";
    };
  };
  "jupyterlab-launcher" = super.buildPythonPackage {
    name = "jupyterlab-launcher-0.13.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."jsonschema"
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/30/96dd5c4caaacbc0c41754cb72547717ac8de67bb48a393b5d8b74080fbd9/jupyterlab_launcher-0.13.1.tar.gz";
      sha256 = "1w65d7fylnzvfmyj92pwjyc1cfyiw356zp2ib56m47wb1gdfm07q";
    };
  };
  "kitchen" = super.buildPythonPackage {
    name = "kitchen-1.2.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/3c/eb027400d34ed066d882d4cbbcb9b84eb7e91a7be770dd6fecebc37ba91f/kitchen-1.2.5.tar.gz";
      sha256 = "1zakh6l0yjvwic9p0nkvmbidpnkygkxbigh2skmb5gccyrhbp7xg";
    };
  };
  "lunr" = super.buildPythonPackage {
    name = "lunr-0.5.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."future"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/5a/b737c000e49419c27315a75ea05d7212318e09d8824afe58a979c86f9f17/lunr-0.5.3.tar.gz";
      sha256 = "0m32ni1kr5ylvkaw5s35va73ny3b7hkyq8967rxi9ybshmzkq523";
    };
  };
  "mccabe" = super.buildPythonPackage {
    name = "mccabe-0.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz";
      sha256 = "07w3p1qm44hgxf3vvwz84kswpsx6s7kvaibzrsx5dzm0hli1i3fx";
    };
  };
  "mistune" = super.buildPythonPackage {
    name = "mistune-0.8.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/be/e06d4346cc608a01dec6bf770d7d0303a4fd6db588b318ced18f5f257145/mistune-0.8.3.tar.gz";
      sha256 = "06b662p6kf46wh2jsabaqhaq4bz1srh2zxkrnx4yg96azlxw645w";
    };
  };
  "more-itertools" = super.buildPythonPackage {
    name = "more-itertools-4.3.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/88/ff/6d485d7362f39880810278bdc906c13300db05485d9c65971dec1142da6a/more-itertools-4.3.0.tar.gz";
      sha256 = "17h3na0rdh8xq30w4b9pizgkdxmm51896bxw600x84jflg9vaxn4";
    };
  };
  "nbconvert" = super.buildPythonPackage {
    name = "nbconvert-5.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."bleach"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/a4/d0a0938ad6f5eeb4dea4e73d255c617ef94b0b2849d51194c9bbdb838412/nbconvert-5.3.1.tar.gz";
      sha256 = "1f9dkvpx186xjm4xab0qbph588mncp4vqk3fmxrsnqs43mks9c8j";
    };
  };
  "nbformat" = super.buildPythonPackage {
    name = "nbformat-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/0e/160754f7ae3e984863f585a3743b0ed1702043a81245907c8fae2d537155/nbformat-4.4.0.tar.gz";
      sha256 = "00nlf08h8yc4q73nphfvfhxrcnilaqanb8z0mdy6nxk0vzq4wjgp";
    };
  };
  "nbsphinx" = super.buildPythonPackage {
    name = "nbsphinx-0.3.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."jinja2"
      self."nbconvert"
      self."nbformat"
      self."sphinx"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3a/2b/9f73582f546c5b2dd37c43f6bd496ca356dc0e480919459fe64575538779/nbsphinx-0.3.5.tar.gz";
      sha256 = "06j7b60jiczjr1bh3va885rywx4jj79pc6cpk2mnjgx9ipvfga9i";
    };
  };
  "notebook" = super.buildPythonPackage {
    name = "notebook-5.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."Send2Trash"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/41/b04ddb3020bdb55431f2a06c87ff98bf68fb27cd0c165ae6421c17d3b5cb/notebook-5.7.0.tar.gz";
      sha256 = "19xia16kgdjg1p6504njrpadsjfb1jc5llfhw57z3x2cspilspmq";
    };
  };
  "packaging" = super.buildPythonPackage {
    name = "packaging-18.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pyparsing"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cf/50/1f10d2626df0aa97ce6b62cf6ebe14f605f4e101234f7748b8da4138a8ed/packaging-18.0.tar.gz";
      sha256 = "01wq9c53ix5rz6qg2c98gy8n4ff768rmanifm8m5jpjiaizj51h8";
    };
  };
  "pandocfilters" = super.buildPythonPackage {
    name = "pandocfilters-1.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz";
      sha256 = "1a8d9b7s48gmq9zj0pmbyv2sivn5i7m6mybgpkk4jm5vd7hp1pdk";
    };
  };
  "parso" = super.buildPythonPackage {
    name = "parso-0.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/31/60de7c9cbb97cac56b193a5b61a1fd4d21df84843a570b370ec34781316b/parso-0.3.1.tar.gz";
      sha256 = "18p89iwcm8mnf380f92g9w0bhx5km8wxp392vvjcq4y1ld1llw1m";
    };
  };
  "pep8-naming" = super.buildPythonPackage {
    name = "pep8-naming-0.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."flake8-polyfill"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3e/4a/125425d6b1e017f48dfc9c961f4bb9510168db7a090618906c750184ed03/pep8-naming-0.7.0.tar.gz";
      sha256 = "09j8qg9wvrgp05drq81kfbd18wzz4p4nrhzkvalk5vq6vph5hhk2";
    };
  };
  "pexpect" = super.buildPythonPackage {
    name = "pexpect-4.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/43/07d07654ee3e25235d8cea4164cdee0ec39d1fda8e9203156ebe403ffda4/pexpect-4.6.0.tar.gz";
      sha256 = "1fla85g47iaxxpjhp9vkxdnv4pgc7rplfy6ja491smrrk0jqi3ia";
    };
  };
  "pickleshare" = super.buildPythonPackage {
    name = "pickleshare-0.7.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/fe/dd137d84daa0fd13a709e448138e310d9ea93070620c9db5454e234af525/pickleshare-0.7.4.tar.gz";
      sha256 = "0yvk14dzxk7g6qpr7iw23vzqbsr0dh4ij4xynkhnzpfz4xr2bac4";
    };
  };
  "pillow" = super.buildPythonPackage {
    name = "pillow-5.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d3/c4/b45b9c0d549f482dd072055e2d3ced88f3b977f7b87c7a990228b20e7da1/Pillow-5.2.0.tar.gz";
      sha256 = "1ary9mj2ddllq3lkxgn6aac7qxqiwbcg2pacrl94py58ql9x9czq";
    };
  };
  "pkginfo" = super.buildPythonPackage {
    name = "pkginfo-1.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/c9/111ececbeed8e69cd1b6bec79a32a0b0f6074038a4244e58e285ad278248/pkginfo-1.4.2.tar.gz";
      sha256 = "0x6lm17p1ks031mj6pajyp4rkq74vpqq8qwjb7ikgwmkli1day2q";
    };
  };
  "pluggy" = super.buildPythonPackage {
    name = "pluggy-0.7.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/83/ef7d976c12d67a5c7a5bc2a47f0501c926cabae9d9fcfdc26d72abc9ba15/pluggy-0.7.1.tar.gz";
      sha256 = "1qbn70mksmr03hac6jgp6fiqc4l7859z8dchx2x950vhlij87swm";
    };
  };
  "ply" = super.buildPythonPackage {
    name = "ply-3.11";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/69/882ee5c9d017149285cab114ebeab373308ef0f874fcdac9beb90e0ac4da/ply-3.11.tar.gz";
      sha256 = "18qx113g9bi1ac4indd5phma82zcdq601lxncp3vjn43m2mc3iq0";
    };
  };
  "prometheus-client" = super.buildPythonPackage {
    name = "prometheus-client-0.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/b1/08de091b392fec31da9bd3f5edd9214ec1c6931dd81641610ac20f3ff934/prometheus_client-0.3.1.tar.gz";
      sha256 = "093yhvz7lxl7irnmsfdnf2030lkj4gsfkg6pcmy4yr1ijk029g0p";
    };
  };
  "prompt-toolkit" = super.buildPythonPackage {
    name = "prompt-toolkit-1.0.15";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/ad/cf6b128866e78ad6d7f1dc5b7f99885fb813393d9860778b2984582e81b5/prompt_toolkit-1.0.15.tar.gz";
      sha256 = "05v9h5nydljwpj5nm8n804ms0glajwfy1zagrzqrg91wk3qqi1c5";
    };
  };
  "ptyprocess" = super.buildPythonPackage {
    name = "ptyprocess-0.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/2d/e4b8733cf79b7309d84c9081a4ab558c89d8c89da5961bf4ddb050ca1ce0/ptyprocess-0.6.0.tar.gz";
      sha256 = "1h4lcd3w5nrxnsk436ar7fwkiy5rfn5wj2xwy9l0r4mdqnf2jgwj";
    };
  };
  "py" = super.buildPythonPackage {
    name = "py-1.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4f/38/5f427d1eedae73063ce4da680d2bae72014995f9fdeaa57809df61c968cd/py-1.6.0.tar.gz";
      sha256 = "1wcs3zv9wl5m5x7p16avqj2gsrviyb23yvc3pr330isqs0sh98q6";
    };
  };
  "pycodestyle" = super.buildPythonPackage {
    name = "pycodestyle-2.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/28/ad/cae9654d7fd64eb3d2ab2c44c9bf8dc5bd4fb759625beab99532239aa6e8/pycodestyle-2.4.0.tar.gz";
      sha256 = "0fhy4vnlgpjq4qd1wdnl6pvdw7rah0ypmn8c9mkhz8clsndskz6b";
    };
  };
  "pycparser" = super.buildPythonPackage {
    name = "pycparser-2.19";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz";
      sha256 = "1cr5dcj9628lkz1qlwq3fv97c25363qppkmcayqvd05dpy573259";
    };
  };
  "pyflakes" = super.buildPythonPackage {
    name = "pyflakes-2.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/9e/386c0d9deef14996eb90d9deebbcb9d3ceb70296840b09615cb61b2ae231/pyflakes-2.0.0.tar.gz";
      sha256 = "0jba28czyvimdc72llms3f17swp3i8jdcabf5w0j00adfbn64xls";
    };
  };
  "pygments" = super.buildPythonPackage {
    name = "pygments-2.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/2a/2e4e77803a8bd6408a2903340ac498cb0a2181811af7c9ec92cb70b0308a/Pygments-2.2.0.tar.gz";
      sha256 = "1k78qdvir1yb1c634nkv6rbga8wv4289xarghmsbbvzhvr311bnv";
    };
  };
  "pyparsing" = super.buildPythonPackage {
    name = "pyparsing-2.2.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/e2/4a7ad8f2808e03caebd3ec0a250b4afbb26d4ba063c39c3286185dd06dd1/pyparsing-2.2.2.tar.gz";
      sha256 = "02m3gk70i8npyi9m7ky4zrgx81xwc31sxbkdrxkzbwqsp5372v5w";
    };
  };
  "pyroma" = super.buildPythonPackage {
    name = "pyroma-2.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/e4/540694eb7116c1557244f3d5c656673cea48674cb40759a78bf7bbc14c47/pyroma-2.4.tar.gz";
      sha256 = "0zzfnrrpydj44d5bg47fqhbg4mi5j23v9j3ssfdzyswpfyq1r8cl";
    };
  };
  "pytest" = super.buildPythonPackage {
    name = "pytest-3.8.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."more-itertools"
      self."pluggy"
      self."py"
      self."setuptools"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bf/4f/3cc568e63e2e68de369bfb76758db3aa168e34976fcc87fdfb2c19c645d9/pytest-3.8.0.tar.gz";
      sha256 = "17grcfvd6ggvvqmprwv5y8g319nayam70hr43ssjwj40ws27z858";
    };
  };
  "pytest-cov" = super.buildPythonPackage {
    name = "pytest-cov-2.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."coverage"
      self."pytest"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/e2/58f90a316fbd94dd50bf5c826a23f3f5d079fb3cc448c1e9f0e3c33a3d2a/pytest-cov-2.6.0.tar.gz";
      sha256 = "0qnpp9y3ygx4jk4pf5ad71fh2skbvnr6gl54m7rg5qysnx4g0q73";
    };
  };
  "pytest-runner" = super.buildPythonPackage {
    name = "pytest-runner-4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/b7/fe6e8f87f9a756fd06722216f1b6698ccba4d269eac6329d9f0c441d0f93/pytest-runner-4.2.tar.gz";
      sha256 = "1gkpyphawxz38ni1gdq1fmwyqcg02m7ypzqvv46z06crwdxi2gyj";
    };
  };
  "python-dateutil" = super.buildPythonPackage {
    name = "python-dateutil-2.7.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/b0/a4e3241d2dee665fea11baec21389aec6886655cd4db7647ddf96c3fad15/python-dateutil-2.7.3.tar.gz";
      sha256 = "1f7h54lg0w2ckch7592xpjkh8dg87k2br256h0iw49zn6bg02w72";
    };
  };
  "pytz" = super.buildPythonPackage {
    name = "pytz-2018.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/50/4cdc62fc0753595fc16c8f722a89740f487c6e5670c644eb8983946777be/pytz-2018.3.tar.gz";
      sha256 = "1h4m80p36yzwmil23qwrlja1x2yxyqxx77jxlsx6y0h9chfws2s1";
    };
  };
  "pyzmq" = super.buildPythonPackage {
    name = "pyzmq-17.1.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/6a/bc9277b78f5c3236e36b8c16f4d2701a7fd4fa2eb697159d3e0a3a991573/pyzmq-17.1.2.tar.gz";
      sha256 = "1pyxxrz60f88ffm0y6vpbx3q8jcr9ybz8fcilihwzwhh36n84ax7";
    };
  };
  "qtconsole" = super.buildPythonPackage {
    name = "qtconsole-4.4.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/6d/5af06751ece05ff0892dd02ce043062bc2d8f426f91894876f669a70ef1b/qtconsole-4.4.1.tar.gz";
      sha256 = "0xp1qi7jrvg1qkbh4s8sl2rnhxfaq1im9rlyq2nb62kbdagb2w3q";
    };
  };
  "readme-renderer" = super.buildPythonPackage {
    name = "readme-renderer-22.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."bleach"
      self."cmarkgfm"
      self."docutils"
      self."future"
      self."pygments"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/aa/b6/384c1dfe9b3ac3404817ac32fa44abbe0b51c2494ba118e0ad7ff3e72efb/readme_renderer-22.0.tar.gz";
      sha256 = "1lj3k3x7wm0w5xdy82jwl0fmchqmlkdh24g41n3lka7ybxqahz13";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.18.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/e1/eab4fc3752e3d240468a8c0b284607899d2fbfb236a56b7377a329aa8d09/requests-2.18.4.tar.gz";
      sha256 = "0zi3v9nsmv9j27d0c0m1dvqyvaxz53g8m0aa1h3qanxs4irkwi4w";
    };
  };
  "requests-toolbelt" = super.buildPythonPackage {
    name = "requests-toolbelt-0.8.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/86/f9/e80fa23edca6c554f1994040064760c12b51daff54b55f9e379e899cd3d4/requests-toolbelt-0.8.0.tar.gz";
      sha256 = "1dc7l42i4080r8i4m9fj51jx367lqkai170vrv7wd93gdj9k39gn";
    };
  };
  "rfc3987" = super.buildPythonPackage {
    name = "rfc3987-1.3.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/fb/4c6eb50dcca68e8b1cbe2a550946a21223c10a8080e13f6580be5f6b5596/rfc3987-1.3.7.tar.gz";
      sha256 = "192pclzs2y0yaywqkrlvd0x73740q310kvqvm6jldhi619mq59wi";
    };
  };
  "robotframework" = super.buildPythonPackage {
    name = "robotframework-3.1a2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9b/e9/abe4a90c9bdffef89dbf7e91616714b70608ca3a86a4e4114a6f8fb846d1/robotframework-3.1a2.zip";
      sha256 = "1pxixis4ari8l7vfynwndcpdcyr9vaqicsbfczm0cp8fb5k8qk15";
    };
  };
  "robotframework-appiumlibrary" = super.buildPythonPackage {
    name = "robotframework-appiumlibrary-1.4.6";
    doCheck = false;
    propagatedBuildInputs = [
      self."Appium-Python-Client"
      self."decorator"
      self."docutils"
      self."kitchen"
      self."robotframework"
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/eb/5a/1e27a66fbc7e711c2720bb0b9a8c4fa5c4ca91171d3a245244e6efd01b3b/robotframework-appiumlibrary-1.4.6.tar.gz";
      sha256 = "1w3ipqy1kg67h20ww0n8yb7zvbr5chcnvfsxn1006facrc92sqj0";
    };
  };
  "robotframework-debuglibrary" = super.buildPythonPackage {
    name = "robotframework-debuglibrary-1.1.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."prompt-toolkit"
      self."pygments"
      self."robotframework"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/81/11c294693b9c51550fe57b62aed60ec393a40d3bbeb06da3869517cdc48c/robotframework-debuglibrary-1.1.4.tar.gz";
      sha256 = "0n96kcaspfya5dm3nk68mf1c3d7xf8pd00kvplv4skchcw69s7p9";
    };
  };
  "robotframework-faker" = super.buildPythonPackage {
    name = "robotframework-faker-4.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."faker"
      self."robotframework"
      self."wrapt"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/3f/6db0f8a180bf5a62d25f6e30288565e1d5f75e39ece5f53bafa91db5344b/robotframework-faker-4.2.0.tar.gz";
      sha256 = "08bllg496wzbfm87ymbd7qzv8qjhhs3xbqmpxik63xmcikaf0yb1";
    };
  };
  "robotframework-selenium2library" = super.buildPythonPackage {
    name = "robotframework-selenium2library-3.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework-seleniumlibrary"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c4/7d/3c07081e7f0f1844aa21fd239a0139db4da5a8dc219d1e81cb004ba1f4e2/robotframework-selenium2library-3.0.0.tar.gz";
      sha256 = "19zxf2f5f6ply2ab4q9l52cn3d6j6j5h0f9h4pnnvcc80wmr93ia";
    };
  };
  "robotframework-selenium2screenshots" = super.buildPythonPackage {
    name = "robotframework-selenium2screenshots-0.8.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."robotframework-selenium2library"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6d/65/588adf91f3ba1fcbe57fd67c1e1022fe599194fc171ec1275a0d947acbab/robotframework-selenium2screenshots-0.8.1.tar.gz";
      sha256 = "07dwqgyp8i48zpy45g1dn42z9qc1kpfj2nnhwh5ksn9zbsg6bl25";
    };
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage {
    name = "robotframework-seleniumlibrary-3.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e9/15/03f51c0ee6285dbf9ebdca176dd2bac6dfbc9cf5a2f54201c9fcdab4a078/robotframework-seleniumlibrary-3.2.0.tar.gz";
      sha256 = "1nw5nh52aprhdnk1583y0imczzw705671r8n90nk5zgvlhdf0ghi";
    };
  };
  "selenium" = super.buildPythonPackage {
    name = "selenium-3.14.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/c4/e361c5659c558edbd391d322622d8d37ae1cf011cf42470455d54956a80f/selenium-3.14.1.tar.gz";
      sha256 = "0576jvqfwvpaap69v9pl898lj4lbdk34fjzlpkx40k0n8v82q6db";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-40.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/76/f777f50a1303b481d575fcf2af7de336a23c88f17fb4b6e7894de6b602cd/setuptools-40.4.2.zip";
      sha256 = "0j6vgl2lz01w8phncbxhv9k983jncxyx0rv5gzihbqnil6w8m2b5";
    };
  };
  "setuptools-scm" = super.buildPythonPackage {
    name = "setuptools-scm-3.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/b4/d148a70543b42ff3d81d57381f33104f32b91f970ad7873f463e75bf7453/setuptools_scm-3.1.0.tar.gz";
      sha256 = "0h4bglwfz8b9prqljv8z3w9rgydfyxzaj05bm1y6zs5m6shz548i";
    };
  };
  "simplegeneric" = super.buildPythonPackage {
    name = "simplegeneric-0.8.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/57/4d9c9e3ae9a255cd4e1106bb57e24056d3d0709fc01b2e3e345898e49d5b/simplegeneric-0.8.1.zip";
      sha256 = "0wwi1c6md4vkbcsfsf8dklf3vr4mcdj4mpxkanwgb6jb1432x5yw";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.11.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/d8/bc6316cf98419719bd59c91742194c111b6f2e85abac88e496adefaf7afe/six-1.11.0.tar.gz";
      sha256 = "1scqzwc51c875z23phj48gircqjgnn3af8zy2izjwmnlxrxsgs3h";
    };
  };
  "snowballstemmer" = super.buildPythonPackage {
    name = "snowballstemmer-1.2.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/6b/d2a7cb176d4d664d94a6debf52cd8dbae1f7203c8e42426daa077051d59c/snowballstemmer-1.2.1.tar.gz";
      sha256 = "0a0idq4y5frv7qsg2x62jd7rd272749xk4x99misf5rcifk2d7wi";
    };
  };
  "sphinx" = super.buildPythonPackage {
    name = "sphinx-1.8.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."alabaster"
      self."babel"
      self."docutils"
      self."imagesize"
      self."jinja2"
      self."packaging"
      self."pygments"
      self."requests"
      self."setuptools"
      self."six"
      self."snowballstemmer"
      self."sphinxcontrib-websupport"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/e9/b1bed881847680cecc70159b8b9d5fd1cd4e85627c534712c2c7b339f8b6/Sphinx-1.8.1.tar.gz";
      sha256 = "05wz8y57jfmwnlk046m16brnsdldhsy6sjxv4ah2727icv2vhbk5";
    };
  };
  "sphinx-rtd-theme" = super.buildPythonPackage {
    name = "sphinx-rtd-theme-0.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."sphinx"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/db/37/f57c7a99827aa03fa8efc24037ff9990deb1c6a7bb2f23c388bd36b8748a/sphinx_rtd_theme-0.4.2.tar.gz";
      sha256 = "02bax2pv56wf70dpvq0k9zvf0j46smws9ir0i9svpakbdmkjmw02";
    };
  };
  "sphinxcontrib-websupport" = super.buildPythonPackage {
    name = "sphinxcontrib-websupport-1.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/7a/e74b06dce85555ffee33e1d6b7381314169ebf7e31b62c18fcb2815626b7/sphinxcontrib-websupport-1.1.0.tar.gz";
      sha256 = "1ff3ix76xi1y6m99qxhaq5161ix9swwzydilvdya07mgbcvpzr4x";
    };
  };
  "strict-rfc3339" = super.buildPythonPackage {
    name = "strict-rfc3339-0.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
  };
  "terminado" = super.buildPythonPackage {
    name = "terminado-0.8.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/67/84/ce0ebd0f60e1cbe040f8e065eef7063855d59d9cf5e6438b3f8439fc7e15/terminado-0.8.1.tar.gz";
      sha256 = "0yh69k6579g848rmjyllb5h75pkvgcy27r1l3yzgkf33wnnzkasm";
    };
  };
  "testpath" = super.buildPythonPackage {
    name = "testpath-0.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/8b/b71e9ee10e5f751e9d959bc750ab122ba04187f5aa52aabdc4e63b0e31a7/testpath-0.3.1.tar.gz";
      sha256 = "02bnmkvm6a8a1p5kcygylcd19v2s040qw3zp1n8ab3bqkj1kflqd";
    };
  };
  "text-unidecode" = super.buildPythonPackage {
    name = "text-unidecode-1.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/a2/40adaae7cbdd007fb12777e550b5ce344b56189921b9f70f37084c021ca4/text-unidecode-1.2.tar.gz";
      sha256 = "0v9r3834c82ygm21rjqk561s12gqw698vqwaa108g5m75fxpa4ss";
    };
  };
  "tornado" = super.buildPythonPackage {
    name = "tornado-5.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/78/6e7b5af12c12bdf38ca9bfe863fcaf53dc10430a312d0324e76c1e5ca426/tornado-5.1.1.tar.gz";
      sha256 = "02clqk2116jbnq8lnaqmdw3p52nqrd9ib59r4xz2ll43fpcmhlaf";
    };
  };
  "tqdm" = super.buildPythonPackage {
    name = "tqdm-4.26.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5a/53/05ac96b04b6417d5d8d4638ac22e39b39a8c8e5e2a35cda5e8d2efa275c3/tqdm-4.26.0.tar.gz";
      sha256 = "1j9885das9jmbn5n8m1ns9h6kz254aahgfqq0an6p63005jw00nz";
    };
  };
  "traitlets" = super.buildPythonPackage {
    name = "traitlets-4.3.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/98/7f5ef2fe9e9e071813aaf9cb91d1a732e0a68b6c44a32b38cb8e14c3f069/traitlets-4.3.2.tar.gz";
      sha256 = "0dbq7sx26xqz5ixs711k5nc88p8a0nqyz6162pwks5dpcz9d4jww";
    };
  };
  "twine" = super.buildPythonPackage {
    name = "twine-1.11.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."pkginfo"
      self."requests"
      self."requests-toolbelt"
      self."setuptools"
      self."tqdm"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/89/2971f240b9fc102b2e56ee8b0a9d7c9c3a7cf081b851eb02d85891de20d1/twine-1.11.0.tar.gz";
      sha256 = "09cz9v63f8mrs4znbjapjj2z3wdfryq8q364zm0wzjhbzzcs9n9g";
    };
  };
  "tzlocal" = super.buildPythonPackage {
    name = "tzlocal-1.5.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz";
      sha256 = "0kiciwiqx0bv0fbc913idxibc4ygg4cb7f8rcpd9ij2shi4bigjf";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.22";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz";
      sha256 = "0kyvc9zdlxr5r96bng5rhm9a6sfqidrbvvkz64s76qs5267dli6c";
    };
  };
  "validate-email" = super.buildPythonPackage {
    name = "validate-email-1.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/a0/cb53fb64b52123513d04f9b913b905f3eb6fda7264e639b4573cc715c29f/validate_email-1.3.tar.gz";
      sha256 = "1bxffaf5yz2cph8ki55vdvdypbwkvn2xr1firlcy62vqbzf1jivq";
    };
  };
  "vcversioner" = super.buildPythonPackage {
    name = "vcversioner-2.16.0.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/cc/33162c0a7b28a4d8c83da07bc2b12cee58c120b4a9e8bba31c41c8d35a16/vcversioner-2.16.0.0.tar.gz";
      sha256 = "16z10sm78jd7ca3jbkgc3q5i8a8q7y1h21q1li21yy3rlhbhrrns";
    };
  };
  "wcwidth" = super.buildPythonPackage {
    name = "wcwidth-0.1.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz";
      sha256 = "0pn6dflzm609m4r3i8ik5ni9ijjbb5fa3vg1n7hn6vkd49r77wrx";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "wheel" = super.buildPythonPackage {
    name = "wheel-0.31.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/fb/aefe5d5dbc3f4fe1e815bcdb05cbaab19744d201bbc9b59cfa06ec7fc789/wheel-0.31.1.tar.gz";
      sha256 = "0g78i8rj940wpvfs5s3ka48i491jgq9j5j1gblag4a06i9am8bha";
    };
  };
  "widgetsnbextension" = super.buildPythonPackage {
    name = "widgetsnbextension-3.4.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/37/ec01aac3e510645959795337bf652155cd7efb28aecc940b0773e8ba8e4d/widgetsnbextension-3.4.2.tar.gz";
      sha256 = "0rc2nivdy7k4m3vljx7wdh2jh11djapcgwhvzlbs0isl8gl8nqgs";
    };
  };
  "wrapt" = super.buildPythonPackage {
    name = "wrapt-1.10.11";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz";
      sha256 = "1ip3dwib39xhp79kblskgvz3fjzcwxgx3fs3ahdixhpjg7a61mfl";
    };
  };
  "yapf" = super.buildPythonPackage {
    name = "yapf-0.24.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/42/58da38075e4d1f2838de55619b669855ab52b6020763f6ea9a4102289105/yapf-0.24.0.tar.gz";
      sha256 = "0anwby0ydmyzcsgjc5dn1ryddwvii4dq61vck447q0n96npnzfyf";
    };
  };
  "zest.releaser" = super.buildPythonPackage {
    name = "zest.releaser-6.15.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."colorama"
      self."requests"
      self."setuptools"
      self."six"
      self."twine"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/d5/e5e45d6c50e363d66ab1588c91998d002573d58774fec44cc84d6e6fd581/zest.releaser-6.15.2.tar.gz";
      sha256 = "1yxriv97k830xbz763vnxfzsqajd4yxayrkxv2sickp9v74gbch8";
    };
  };
}
