# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Appium-Python-Client" = super.buildPythonPackage rec {
    pname = "Appium-Python-Client";
    version = "0.52";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/92/9be7026178eb023668c46454704cbe5b0ee8ef51c4872a2aaa47c0c06345/Appium-Python-Client-0.52.tar.gz";
      sha256 = "1niar6sziq3gczjsmqbvn8bnq4mrlvi70fq7pakqk3iz6iad9094";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."selenium"
    ];
  };
  "GenSON" = super.buildPythonPackage rec {
    pname = "GenSON";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/00/7aae36d5ecf483585fba2bacb7c1ccb4ceaf4fcba61f8f9846845300f93b/genson-1.2.1.tar.gz";
      sha256 = "0hlws2w3i2m54g1a3axjgbmkaysz5cq7lgb89li0y92kgyhzmf20";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "RESTinstance" = super.buildPythonPackage rec {
    pname = "RESTinstance";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/1b/213e965f138a2a429ac8898432a78748786ab940d617b60a613576ce8356/RESTinstance-1.0.2-py3-none-any.whl";
      sha256 = "0k6ll20i63pvjs4m12av6nh9ary0i44g4zp9myxfh59raxl5l7gf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."GenSON"
      self."docutils"
      self."flex"
      self."jsonpath-ng"
      self."jsonschema"
      self."pygments"
      self."pytz"
      self."requests"
      self."rfc3987"
      self."robotframework"
      self."strict-rfc3339"
      self."tzlocal"
    ];
  };
  "Send2Trash" = super.buildPythonPackage rec {
    pname = "Send2Trash";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/49/46/c3dc27481d1cc57b9385aff41c474ceb7714f7935b1247194adae45db714/Send2Trash-1.5.0-py3-none-any.whl";
      sha256 = "12w8x95c7nnj91wm7jmr014pr24xb5bynji344la2vvvawi1jsgi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "alabaster" = super.buildPythonPackage rec {
    pname = "alabaster";
    version = "0.7.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl";
      sha256 = "0nfkvlqp1mwjj0jjqk0mm7hk5c6rq5l1dpm2bva5pq50rjykhr24";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "appdirs" = super.buildPythonPackage rec {
    pname = "appdirs";
    version = "1.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl";
      sha256 = "0vhnw9ihh67n7n7zdsn355pflz1da1nn6m7czbfk838xarj4dcnq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "astroid" = super.buildPythonPackage rec {
    pname = "astroid";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/f6/880bade8329525fd9aa9051891b4b8fe2e52c7aab7412443f8743028a590/astroid-2.4.0-py3-none-any.whl";
      sha256 = "19jf0ad58hvapim2njxh25rakyzd4yzbbiv5xli1kfqan91fmv1g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."lazy-object-proxy"
      self."six"
      self."typed-ast"
      self."wrapt"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "19.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl";
      sha256 = "073xrfixypmvlimyfj4733bz9f9c9yi63ywsnm7f8x1s3ij6ra88";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "babel" = super.buildPythonPackage rec {
    pname = "babel";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/a1/522dccd23e5d2e47aed4b6a16795b8213e3272c7506e625f2425ad025a19/Babel-2.8.0-py2.py3-none-any.whl";
      sha256 = "1m2jq6g2crhvp96npmr0l96j8nsngfwbwsis5mkj7dzq205ylw6n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
  };
  "backcall" = super.buildPythonPackage rec {
    pname = "backcall";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "black" = super.buildPythonPackage rec {
    pname = "black";
    version = "19.10b0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/bb/ad34bbc93d1bea3de086d7c59e528d4a503ac8fe318bd1fa48605584c3d2/black-19.10b0-py36-none-any.whl";
      sha256 = "02sffgjf4ppy40w8h0ji8pz06szgmc45wpjnwhggryi5x6dyac0v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."appdirs"
      self."attrs"
      self."click"
      self."pathspec"
      self."regex"
      self."toml"
      self."typed-ast"
    ];
  };
  "bleach" = super.buildPythonPackage rec {
    pname = "bleach";
    version = "3.1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/bc/9c2bbd8bff5f393e3373687109117a061db4c8ccdf6b5c70b1f8834bd67a/bleach-3.1.4-py2.py3-none-any.whl";
      sha256 = "0g4h2zam05i5r99gvv3vki6hr3j5jhhiwrv3mk1mdzm1fr8a53fc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2020.4.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl";
      sha256 = "016kmf145apmfkrpxwd7434hcjchypy6djbwhi03qqvmijcpm60x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "3.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl";
      sha256 = "14b621614q2lw7ik2igdv4qdbblqgdsiglgl5fhf1l5fmvy3ycpw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "7.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl";
      sha256 = "16hv8y5lq7wl4zkirfvbf4i5xshjw7jn8q856isyxx8bv11x2ig3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "coverage" = super.buildPythonPackage rec {
    pname = "coverage";
    version = "4.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz";
      sha256 = "0p0j4di6h8k6ica7jwwj09azdcg4ycxq60i9qsskmsg94cd9yzg0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "coveralls" = super.buildPythonPackage rec {
    pname = "coveralls";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/de/449eaed85c6810bcb4b589f89e2d4dfa346f9fa4b747c236699409a85579/coveralls-2.0.0-py2.py3-none-any.whl";
      sha256 = "1fd4dcpf9xp10nqf7a913ilr0q47xpvv62lrdssxbpr10fv5gga1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."coverage"
      self."docopt"
      self."requests"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl";
      sha256 = "0q7p11gj5g158gb1igy9cna5ppxf03zkrm2gpr4acjycl3159yj1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "defusedxml" = super.buildPythonPackage rec {
    pname = "defusedxml";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/74/9b387472866358ebc08732de3da6dc48e44b0aacd2ddaa5cb85ab7e986a2/defusedxml-0.6.0-py2.py3-none-any.whl";
      sha256 = "14zglgld9yp35l89dqs9ayfdsix84yrs3dqvb2mp90s3f03ib1v6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docopt" = super.buildPythonPackage rec {
    pname = "docopt";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz";
      sha256 = "14f4hn6d1j4b99svwbaji8n2zj58qicyz19mm0x6pmhb50jsics9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docutils" = super.buildPythonPackage rec {
    pname = "docutils";
    version = "0.16";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/44/8a15e45ffa96e6cf82956dd8d7af9e666357e16b0d93b253903475ee947f/docutils-0.16-py2.py3-none-any.whl";
      sha256 = "1bxk9azs910d03ldns9kw8wj6xlybk6iam9z8caj8xppzfnphnqc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "entrypoints" = super.buildPythonPackage rec {
    pname = "entrypoints";
    version = "0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl";
      sha256 = "06bdwpdvijwfwlscrvcix9prnkiavvpxf33fpqsssf9p655qg7sq";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "faker" = super.buildPythonPackage rec {
    pname = "faker";
    version = "4.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/64/079c012bed8bc416fa0d136ceff86a7d25e765f45d7a0a97e0b803b1d506/Faker-4.0.3-py3-none-any.whl";
      sha256 = "1kns1ad7g00hnq76i0brji63ry7c10pwrfg7cqa2gbz85n52rgsk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."python-dateutil"
      self."text-unidecode"
    ];
  };
  "fancycompleter" = super.buildPythonPackage rec {
    pname = "fancycompleter";
    version = "0.9.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/ef/c08926112034d017633f693d3afc8343393a035134a29dfc12dcd71b0375/fancycompleter-0.9.1-py3-none-any.whl";
      sha256 = "103hmm2b1s957m6yyvglkvpzz22kz5gg7j2yyb3lqllxgp56n1yx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyrepl"
    ];
  };
  "flex" = super.buildPythonPackage rec {
    pname = "flex";
    version = "6.14.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/de/51/f3bf1779a12e92c3bf9f2d0ee242298775ef625adb596951090bdd24854f/flex-6.14.1.tar.gz";
      sha256 = "1sr91f5sqywj4040jm3cq4333fp8hbmmr7v6v05a3h0sgyixcbi9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."jsonpointer"
      self."pyyaml"
      self."requests"
      self."rfc3987"
      self."six"
      self."strict-rfc3339"
      self."validate-email"
    ];
  };
  "furl" = super.buildPythonPackage rec {
    pname = "furl";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/c7/e9dc30914bf048bcd06284bb93d9650d318ecac8668b684fc41e975558ff/furl-2.1.0-py2.py3-none-any.whl";
      sha256 = "0bp28vllcvl1s8m6ldjgflm1p33dfdfpjqnwgddnldww8zjz3mpl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."orderedmultidict"
      self."six"
    ];
  };
  "future" = super.buildPythonPackage rec {
    pname = "future";
    version = "0.18.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz";
      sha256 = "0zakvfj87gy6mn1nba06sdha63rn4njm7bhh0wzyrxhcny8avgmi";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl";
      sha256 = "1yk5hf2jkw1237b508mxmcdm8zqhfh26fr6rpwyxd968x8fa4s50";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "imagesize" = super.buildPythonPackage rec {
    pname = "imagesize";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/b2/b5522a0c8d11e4aff83f8342f3f0dea68c2fb25aa44403e420587f0ce204/imagesize-1.2.0-py2.py3-none-any.whl";
      sha256 = "1898hacrsc6y5jfz3rkaqdagi7q6fcjblzfaigacff90dadg2rb9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl";
      sha256 = "03yr2r83p7m0fvwv6py3v7fcrbbfgb4vsj6zy63wa30fm6x8qs1a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
  };
  "iplantuml" = super.buildPythonPackage rec {
    pname = "iplantuml";
    version = "0.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/b9/4db9b9ce81184d1d67f82284ca6131258b32f3f69376ee88aab5f7ff60a4/IPlantUML-0.1.1.tar.gz";
      sha256 = "0p1w48iik5cl137b4xy3g5x52wl5b9fayxlr97bzd5v65dqxz1hg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."plantweb"
    ];
  };
  "ipykernel" = super.buildPythonPackage rec {
    pname = "ipykernel";
    version = "5.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/5d/cf47741fa80826f8edf435d9bcf0e84eef2d6d02953ff85e0563b3ab3f0b/ipykernel-5.2.1-py3-none-any.whl";
      sha256 = "169lwzvawad33p1b5ikgcwcspzwslnf2pvhzacgx31zznqd9qg00";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
  };
  "ipython" = super.buildPythonPackage rec {
    pname = "ipython";
    version = "7.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/6f/69f1eec859ce48a86660529b166b6ea466f0f4ab98e4fc0807b835aa22c6/ipython-7.13.0-py3-none-any.whl";
      sha256 = "0cskls3xcyaqvvb2s703r9005f7p4gmgcpkva8j88rvzwdfhg3gb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."traitlets"
    ];
  };
  "ipython-genutils" = super.buildPythonPackage rec {
    pname = "ipython-genutils";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl";
      sha256 = "1f7sc4ydjj33gadcgfz8fcx02d1wm2frlqwzdik1krlr6wikgpbj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ipywidgets" = super.buildPythonPackage rec {
    pname = "ipywidgets";
    version = "7.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/a0/dbcf5881bb2f51e8db678211907f16ea0a182b232c591a6d6f276985ca95/ipywidgets-7.5.1-py2.py3-none-any.whl";
      sha256 = "05hmfyd0w52pnzl7pb4hhfrddfbr0gsj5p43wldgkh7072jfrzqk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
  };
  "isort" = super.buildPythonPackage rec {
    pname = "isort";
    version = "4.3.21";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl";
      sha256 = "1z80w75i884g0lwq2pmnqn41jkwljs3xnyj04r2l6s2r575iz0bf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jedi" = super.buildPythonPackage rec {
    pname = "jedi";
    version = "0.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/3f/67f027e18c60a800875df1a0894a2436ce9053637fa39725766e937c0a71/jedi-0.17.0-py2.py3-none-any.whl";
      sha256 = "1677mak5njzwlw8dqhixwl6ialzc1ykgjzf4ra664kclf4xwjq6d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parso"
    ];
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "2.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl";
      sha256 = "0dbhqghlha2qsgn37xz8mcwdd91scsa3sky0i5534mgr7hfn997h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
  };
  "json5" = super.buildPythonPackage rec {
    pname = "json5";
    version = "0.9.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/4b/c0b4c7e238a98165a0281d6ad52ee4a8401318580d2fc9d3844dda2ef5f7/json5-0.9.4-py2.py3-none-any.whl";
      sha256 = "13s5n6d4bwjqgwy61synhqxr41bqczf83fdkvnird0ahnmhw83sf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonpath-ng" = super.buildPythonPackage rec {
    pname = "jsonpath-ng";
    version = "1.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/24/981fa76e1e415bcceb3a9741d5be04b32c10edd42d88f6783faa750b1239/jsonpath-ng-1.5.1.tar.gz";
      sha256 = "0mffq7hg9pf6dy8qbm1h33s7kzs66lkxq75i9j90r9a48hzzkcbp";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
  };
  "jsonpointer" = super.buildPythonPackage rec {
    pname = "jsonpointer";
    version = "2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl";
      sha256 = "07hw6symim5jqbfgjqqlcyjv3gj5fxy4dv7m76simf6i46h9ydzz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl";
      sha256 = "0qyidiicwn27ya7r4q7cjbra8gna5vkwnfg1kkp7nmvg47w3qnsf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."importlib-metadata"
      self."pyrsistent"
      self."setuptools"
      self."six"
    ];
  };
  "jupyter" = super.buildPythonPackage rec {
    pname = "jupyter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
  };
  "jupyter-client" = super.buildPythonPackage rec {
    pname = "jupyter-client";
    version = "6.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/34/0b/2ebddf775f558158ca8df23b35445fb15d4b1558a9e4a03bc7e75b13476e/jupyter_client-6.1.3-py3-none-any.whl";
      sha256 = "13lcbbprnhqvvg90j9i952zx6ils79qm9bi1y8acdh9ymcxfis6d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-console" = super.buildPythonPackage rec {
    pname = "jupyter-console";
    version = "6.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0a/89/742fa5a80b552ffcb6a8922712697c6e6828aee7b91ee4ae2b79f00f8401/jupyter_console-6.1.0-py2.py3-none-any.whl";
      sha256 = "1n3hwjsl0skrapd8w7l1h2m07a8gk9s2bch3vwls71pc298ib4mk";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
  };
  "jupyter-contrib-core" = super.buildPythonPackage rec {
    pname = "jupyter-contrib-core";
    version = "0.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/8f/04a752a8b66a66e7092c035e5d87d2502ac7ec07f9fb6059059b6c0dc272/jupyter_contrib_core-0.3.3-py2.py3-none-any.whl";
      sha256 = "03z5vly0qqhwwmznbf01a28qxaimagc6qk0cdgamhn4gb8kixj0y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-core"
      self."notebook"
      self."setuptools"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-contrib-nbextensions" = super.buildPythonPackage rec {
    pname = "jupyter-contrib-nbextensions";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/33/f0/6e2c00afda860f655fbf0f795f7310bdbf12122846344dfdc803fc7455d5/jupyter_contrib_nbextensions-0.5.1-py2.py3-none-any.whl";
      sha256 = "0h7z608b239mnrnz81lzry9s8v4hcq7xqsv5dxk6ki88l851y1rc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jupyter-contrib-core"
      self."jupyter-core"
      self."jupyter-highlight-selected-word"
      self."jupyter-latex-envs"
      self."jupyter-nbextensions-configurator"
      self."lxml"
      self."nbconvert"
      self."notebook"
      self."pyyaml"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-core" = super.buildPythonPackage rec {
    pname = "jupyter-core";
    version = "4.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/0d/df2d17cdf389cea83e2efa9a4d32f7d527ba78667e0153a8e676e957b2f7/jupyter_core-4.6.3-py2.py3-none-any.whl";
      sha256 = "08dv9a2adjcj26n8zmcj8igc169manfzq5ilj5ynkr8g0qy63vm4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."traitlets"
    ];
  };
  "jupyter-highlight-selected-word" = super.buildPythonPackage rec {
    pname = "jupyter-highlight-selected-word";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/50/d7/19ab7cfd60bf268d2abbacc52d4295a40f52d74dfc0d938e4761ee5e598b/jupyter_highlight_selected_word-0.2.0-py2.py3-none-any.whl";
      sha256 = "0n1wj2sw2rqb3bv57r9phshlwad5sgf08mkrlpiynzh5rflxyicm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jupyter-latex-envs" = super.buildPythonPackage rec {
    pname = "jupyter-latex-envs";
    version = "1.4.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/15/55805de080d5542f76920364635e96e64d3b37f678befdfe3b16aa154205/jupyter_latex_envs-1.4.6.tar.gz";
      sha256 = "0wiq6jssjdnvicwrnrivbjzlg4lkqakpjn4ihflvp2645pmk22h7";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-core"
      self."nbconvert"
      self."notebook"
      self."traitlets"
    ];
  };
  "jupyter-nbextensions-configurator" = super.buildPythonPackage rec {
    pname = "jupyter-nbextensions-configurator";
    version = "0.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/a3/d72d5f2dc10c5ccf5a6f4c79f636bf071a5ce462dedd07af2f70384db6cb/jupyter_nbextensions_configurator-0.4.1.tar.gz";
      sha256 = "10sfdq3rkffpc8rgzwzyk3vrjsb9v158xc7b63xiz3l9kmfnps75";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jupyter-contrib-core"
      self."jupyter-core"
      self."notebook"
      self."pyyaml"
      self."tornado"
      self."traitlets"
    ];
  };
  "jupyter-starters" = super.buildPythonPackage rec {
    pname = "jupyter-starters";
    version = "0.2.2a0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f9/6f/a1d20698e5a25b0efb3a11e56449182f29e50c511d5099ddd7875ae6a80f/jupyter_starters-0.2.2a0-py3-none-any.whl";
      sha256 = "0wlv99x4b5lh7al303jxr3lykd81977w8zznscm3bz0j10zq5l6n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "jupyterlab" = super.buildPythonPackage rec {
    pname = "jupyterlab";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/50/c283aa1b36a1aa79ab7d490b91d11c4b86db8f88fe56e4653690cd6bea86/jupyterlab-2.1.1-py3-none-any.whl";
      sha256 = "1yn4j7jd0qc5r789jv00xpgri6y4qg87d01mnmn1hvip88m8v51n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."jupyterlab-server"
      self."notebook"
      self."tornado"
    ];
  };
  "jupyterlab-server" = super.buildPythonPackage rec {
    pname = "jupyterlab-server";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/f3/84e120dc80180fcfc59167aa8ff96969253a2fca51738a87174b6fbfb3ab/jupyterlab_server-1.1.1-py3-none-any.whl";
      sha256 = "0nf7irv1ah8n8hlk9gb7693zal7hdx7qijfn2l6civjflxzsfy7n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."jinja2"
      self."json5"
      self."jsonschema"
      self."notebook"
      self."requests"
    ];
  };
  "jupytext" = super.buildPythonPackage rec {
    pname = "jupytext";
    version = "1.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/d0/335a061c239e72e14c58b45f015a5d5065a1a029cbf5652dae6fa74589b1/jupytext-1.4.2.tar.gz";
      sha256 = "09qsxs2c2mwiw25kjhs8cvzkhdbf5f2qwdfqqazihbms92zwdd2q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."nbformat"
      self."pyyaml"
    ];
  };
  "kitchen" = super.buildPythonPackage rec {
    pname = "kitchen";
    version = "1.2.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/ca/3365cb1160533be8c8b57dbfd6502f367d35e30935ee89a003c664740714/kitchen-1.2.6.tar.gz";
      sha256 = "0g5hq2icnng9vy4www5hnr3r5srisfwp0wxw1sv5c5dxy61gak5q";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "lazy-object-proxy" = super.buildPythonPackage rec {
    pname = "lazy-object-proxy";
    version = "1.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/3f/a3d687f83c7d44970f70ff0400677746c8860b11f0c08f6b4e07205f0cdc/lazy-object-proxy-1.4.3.tar.gz";
      sha256 = "1w1aaay424ciz8fz3fkzxb0pxzfxn184f2whpyn4fx72bn50x47k";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "lunr" = super.buildPythonPackage rec {
    pname = "lunr";
    version = "0.5.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/a4/3043c019613a1d60abb6e150b7665761bdd236a0d915d447d21c4415fddd/lunr-0.5.8-py2.py3-none-any.whl";
      sha256 = "1jnn06zzsgncihhp60m5y1bdp5y3zqq7l9aa570v9ynlqj4z9cxa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."future"
      self."six"
    ];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/2b/0a66d5436f237aff76b91e68b4d8c041d145ad0a2cdeefe2c42f76ba2857/lxml-4.5.0.tar.gz";
      sha256 = "0q5v7c9k09md6czyl2z0i1xq7hkn4p691gw3850ks0hdyn0cw846";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mccabe" = super.buildPythonPackage rec {
    pname = "mccabe";
    version = "0.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl";
      sha256 = "0hhdp0srgrv4bmzlzvmk67zrqr9cvkjjzgd4gmkvd90dhrc652mb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mistune" = super.buildPythonPackage rec {
    pname = "mistune";
    version = "0.8.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/09/ec/4b43dae793655b7d8a25f76119624350b4d65eb663459eb9603d7f1f0345/mistune-0.8.4-py2.py3-none-any.whl";
      sha256 = "1m5qdckapi46npn36jqljlj2dqgzdm3qslz8xs4a5381fcc0b8c8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "more-itertools" = super.buildPythonPackage rec {
    pname = "more-itertools";
    version = "8.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/72/96/4297306cc270eef1e3461da034a3bebe7c84eff052326b130824e98fc3fb/more_itertools-8.2.0-py3-none-any.whl";
      sha256 = "0z1s746ihyp76wyz664smhqij7pkg0yx6nkdl3zi75az7vrvrn2x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nbconvert" = super.buildPythonPackage rec {
    pname = "nbconvert";
    version = "5.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/79/6c/05a569e9f703d18aacb89b7ad6075b404e8a4afde2c26b73ca77bb644b14/nbconvert-5.6.1-py2.py3-none-any.whl";
      sha256 = "1vpw4pvhv300rk61h143w7bl4325p3cizqhkm92xz5jzhw1yrmph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
  };
  "nbformat" = super.buildPythonPackage rec {
    pname = "nbformat";
    version = "4.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl";
      sha256 = "02rvfiakjpf55lzshjv7q740isjjyvbayg49z3s39c2vskdxp85r";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
  };
  "nbimporter" = super.buildPythonPackage rec {
    pname = "nbimporter";
    version = "0.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/01/95fda1a76828b1a37d071b67983a4c7dea95445aa25594b94c097c4074f4/nbimporter-0.3.2-py3-none-any.whl";
      sha256 = "0hgj6mywbb95lxjkr82a5z4dqar5wg4fldca36axgnrwm6c6jkf8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "nbsphinx" = super.buildPythonPackage rec {
    pname = "nbsphinx";
    version = "0.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/f9/10cc745742565590b125c62834ff793cb41be2728141574795fb1e4f59a7/nbsphinx-0.6.1-py3-none-any.whl";
      sha256 = "0nwr5a1zacw0qp5a4mdmkq8vba5001wsxzi07ib2b18qc4wd5v5h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."jinja2"
      self."nbconvert"
      self."nbformat"
      self."sphinx"
      self."traitlets"
    ];
  };
  "notebook" = super.buildPythonPackage rec {
    pname = "notebook";
    version = "6.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b1/f1/0a67f09ef53a342403ffa66646ee39273e0ac79ffa5de5dbe2f3e28b5bdf/notebook-6.0.3-py3-none-any.whl";
      sha256 = "104scfkry81g787q6z94nkv47h2cxbm0bbx3jhljj522d1n63p1y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Send2Trash"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
  };
  "orderedmultidict" = super.buildPythonPackage rec {
    pname = "orderedmultidict";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/16/5e95c70bda8fe6ea715005c0db8e602400bdba50ae3c72cb380eba551289/orderedmultidict-1.0.1-py2.py3-none-any.whl";
      sha256 = "1wyv9bw7rj4iywxqlryhl4n3z2jhm2hyqzf46hiddkg3gshkkj23";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "20.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/0a/34641d2bf5c917c96db0ded85ae4da25b6cd922d6b794648d4e7e07c88e5/packaging-20.3-py2.py3-none-any.whl";
      sha256 = "0ll7q18xc2qlxprrqqqxh0ii4padc1fr112sygxvmh91xsdppxw2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyparsing"
      self."six"
    ];
  };
  "pandocfilters" = super.buildPythonPackage rec {
    pname = "pandocfilters";
    version = "1.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz";
      sha256 = "1a8d9b7s48gmq9zj0pmbyv2sivn5i7m6mybgpkk4jm5vd7hp1pdk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parso" = super.buildPythonPackage rec {
    pname = "parso";
    version = "0.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b5/61/998cce9e7476de000d031874df26a18f67cb73448164fc44a98f0c55920b/parso-0.7.0-py2.py3-none-any.whl";
      sha256 = "1l4d58axifjm14ys6bvkgcm2qg03wlx664d3pi2xq4j1q07i930m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pathspec" = super.buildPythonPackage rec {
    pname = "pathspec";
    version = "0.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl";
      sha256 = "1c0j982wj7lwl6g7803la12zin6cg8a983rdgb88i5vl46fj94bx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pdbpp" = super.buildPythonPackage rec {
    pname = "pdbpp";
    version = "0.10.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3f/82/4b6c5b9128bbbad48a52c6d639c84e3c453e75953ed123b6e9338420dcec/pdbpp-0.10.2.tar.gz";
      sha256 = "1f2ysli7vka2drpw0p7rzqksr9cailrdh1977vffrq06a06j5zvk";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools-scm"
    ];
    propagatedBuildInputs = [
      self."fancycompleter"
      self."pygments"
      self."wmctrl"
    ];
  };
  "pexpect" = super.buildPythonPackage rec {
    pname = "pexpect";
    version = "4.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl";
      sha256 = "0dq9f7irmml1nm9a2rx8dd6m2dqmzjj1x40mk0rg619wrdfsaj0b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
  };
  "pickleshare" = super.buildPythonPackage rec {
    pname = "pickleshare";
    version = "0.7.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl";
      sha256 = "0mnzcb714ynl1qlv9dwnh50rv75mmj18ywaxbl8xzm3l9m0syjcn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pillow" = super.buildPythonPackage rec {
    pname = "pillow";
    version = "7.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/ef/e793f6ffe245c960c42492d0bb50f8d14e2ba223f1922a5c3c81569cec44/Pillow-7.1.2.tar.gz";
      sha256 = "1pdh1zzdwxilvsjg6rnl4q810pc2p2y16q6lx9gzzihb25h9kd50";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "plantweb" = super.buildPythonPackage rec {
    pname = "plantweb";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/6f/9ab1a1c3e33aaa0c0931983578c09336b092c75dce777ea666d3032f756e/plantweb-1.2.1-py3-none-any.whl";
      sha256 = "04va2k8fngzayr95753a6qy5h3qb7yx0br04jyyvqml3mghrqknj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docutils"
      self."requests"
      self."six"
    ];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "0.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl";
      sha256 = "0b8x12j6394w3spk8xzp991khyv8102gas1q7hn515iwv1f18v4n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
  "ply" = super.buildPythonPackage rec {
    pname = "ply";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl";
      sha256 = "1kh7m0i2ghjhrbzi6a28yw3rcnzy5r2i4srls4pvspmna21rnvq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prometheus-client" = super.buildPythonPackage rec {
    pname = "prometheus-client";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/23/41a5a24b502d35a4ad50a5bb7202a5e1d9a0364d0c12f56db3dbf7aca76d/prometheus_client-0.7.1.tar.gz";
      sha256 = "1ni2yv4ixwz32nz39ckia76lvggi7m19y5f702w5qczbnfi29kbi";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "2.0.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl";
      sha256 = "1r55ffffaq4q3dpvha7iipgxlqwvjg5cklf9izr42xj5rr226r26";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
  };
  "ptyprocess" = super.buildPythonPackage rec {
    pname = "ptyprocess";
    version = "0.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl";
      sha256 = "07yaymg8cpnh675miwk62gf20d33sddk6h567i144qz7fs6m5k6p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "py" = super.buildPythonPackage rec {
    pname = "py";
    version = "1.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/99/8d/21e1767c009211a62a8e3067280bfce76e89c9f876180308515942304d2d/py-1.8.1-py2.py3-none-any.whl";
      sha256 = "1c0k53dl6vxs8g6cmzqg73v7iqk4andfwav2zngazh6vln1xs3y2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pycodestyle" = super.buildPythonPackage rec {
    pname = "pycodestyle";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl";
      sha256 = "0mmfj4saqvrzzrfimclpnajhasy71g1lx8b28mq0abrp2afj38lm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pydocstyle" = super.buildPythonPackage rec {
    pname = "pydocstyle";
    version = "5.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/fb/0662498401c663606ef35b4ec6a0aca6b4121d6da8c3ac40a4e68f6ac521/pydocstyle-5.0.2-py3-none-any.whl";
      sha256 = "11km9l5zql4gjyra4cggaj9dhdxipw6lm33p69xk0mbk1dk32y6s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."snowballstemmer"
    ];
  };
  "pyflakes" = super.buildPythonPackage rec {
    pname = "pyflakes";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/69/5b/fd01b0c696f2f9a6d2c839883b642493b431f28fa32b29abc465ef675473/pyflakes-2.2.0-py2.py3-none-any.whl";
      sha256 = "14har5983bq70zlrh7nasdl5qbpblvwxqvab8jcpmr8rbbhf150d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl";
      sha256 = "091k8vlm6lyai7va05cvpwyb7h8w6pmn0qxdiys7lwhbhss40ypz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pylama" = super.buildPythonPackage rec {
    pname = "pylama";
    version = "7.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/a1/d94d7f5be441e1d323b0149a443038b40bbc921346c7ac5a8eecfaf49bdb/pylama-7.7.1-py2.py3-none-any.whl";
      sha256 = "05gbvmnrk2fldggrg5xc6zpj5jbpggimn8zikq0nn9fnf8cc2qgx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pydocstyle"
      self."pyflakes"
    ];
  };
  "pylint" = super.buildPythonPackage rec {
    pname = "pylint";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/9a/1c975d26b6148eb8dba4e50127382e37f9dfc2b18dafeb07e230901cbd38/pylint-2.5.0-py3-none-any.whl";
      sha256 = "1a6m7f7kr4sdj3378jm5k02ygcb08p7h0k00q0gmmxacbalnnmdx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."astroid"
      self."isort"
      self."mccabe"
      self."toml"
    ];
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "2.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl";
      sha256 = "12y8xwjb118a4jqvvfg9k90kqg03n4d3ygb5csz0l81wxy4pb7gg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrepl" = super.buildPythonPackage rec {
    pname = "pyrepl";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/1b/ea40363be0056080454cdbabe880773c3c5bd66d7b13f0c8b8b8c8da1e0c/pyrepl-0.9.0.tar.gz";
      sha256 = "0xd7h7k5cg9gd8nkqdykzkxmfasg8wwxcrmrpdqyh0jm9grp0999";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrsistent" = super.buildPythonPackage rec {
    pname = "pyrsistent";
    version = "0.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/0d/cbca4d0bbc5671822a59f270e4ce3f2195f8a899c97d0d5abb81b191efb5/pyrsistent-0.16.0.tar.gz";
      sha256 = "1lrsjgblnapfimd0alsi1as5nz2lfqv97131l7d6anbjzq2rjri8";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "5.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/e2/c19c667f42f72716a7d03e8dd4d6f63f47d39feadd44cc1ee7ca3089862c/pytest-5.4.1-py3-none-any.whl";
      sha256 = "0wmi15xz3mrvwxvdph98yjara1497px1kr8y3fwqgs04rgsk0nqf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."importlib-metadata"
      self."more-itertools"
      self."packaging"
      self."pluggy"
      self."py"
      self."wcwidth"
    ];
  };
  "pytest-runner" = super.buildPythonPackage rec {
    pname = "pytest-runner";
    version = "5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/45/81b5262c0efc08882bdf183b788e6d28e3d684863990996d8b60967d48da/pytest_runner-5.2-py2.py3-none-any.whl";
      sha256 = "0l8dqz1nkwhl6b0nrp0b1fxrb32hz2l8cy1cqbiaby9y2f5v0d2m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl";
      sha256 = "0answacgnckybm5iyfnaqsgval3mdbpak4i6fsbi2vv8x8qkzfvm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2019.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl";
      sha256 = "03ah44yp8013w30r69mylqnnal15zdh3z0ymrksy27c71rypsm8w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "5.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz";
      sha256 = "0pb4zvkfxfijkpgd1b86xjsqql97ssf1knbd1v53wkg1qm9cgsmq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyzmq" = super.buildPythonPackage rec {
    pname = "pyzmq";
    version = "19.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/4c/762c2c3063c4d45baf4a49acea7a4f561f7b78a45cd04b58d63f4c5f6b8d/pyzmq-19.0.0.tar.gz";
      sha256 = "1a30d8j2k1xw4z3kfgyggp91rc6yhqfj0kj47zcaw1xbfvjna7sy";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "qtconsole" = super.buildPythonPackage rec {
    pname = "qtconsole";
    version = "4.7.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/31/ab/269bc5300d4369a4679cf676c4705aabf2071c2f2d3a211205aca86a1fd6/qtconsole-4.7.3-py2.py3-none-any.whl";
      sha256 = "0a93iisp8pbqijzln7l07pk11r2lzpmsghryi6si1isyx7v2v277";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."pyzmq"
      self."qtpy"
      self."traitlets"
    ];
  };
  "qtpy" = super.buildPythonPackage rec {
    pname = "qtpy";
    version = "1.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/fd/9972948f02e967b691cc0ca1f26124826a3b88cb38f412a8b7935b8c3c72/QtPy-1.9.0-py2.py3-none-any.whl";
      sha256 = "1slh668ml55vwdmrl42yx6d6kh0458bdrva9dwm9ps33ndiq62zs";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "regex" = super.buildPythonPackage rec {
    pname = "regex";
    version = "2020.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/e7/eee73c42c1193fecc0e91361a163cbb8dfbea62c3db7618ad986e5b43a14/regex-2020.4.4.tar.gz";
      sha256 = "0hkiwqycyl17ja5qcsg74s5hsllw6208asx453ad5bai3bvasnr9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl";
      sha256 = "1vizszbz6mdn0fmb1i75d0n5w3jn5f4f968xmyv08ad8pwv916a3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
  };
  "rfc3987" = super.buildPythonPackage rec {
    pname = "rfc3987";
    version = "1.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/d4/f7407c3d15d5ac779c3dd34fbbc6ea2090f77bd7dd12f207ccf881551208/rfc3987-1.3.8-py2.py3-none-any.whl";
      sha256 = "0lyf5pysj3hv249nywgz9k7x4rh3bhc9n60b8r1qhrg5a4g2nw0h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "rise" = super.buildPythonPackage rec {
    pname = "rise";
    version = "5.6.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5c/f4/c226756f3e238a6109aba848ae7e1c96e5b3ed13bbd2916c5f0c6c207fe4/rise-5.6.1-py2.py3-none-any.whl";
      sha256 = "1m2swn862hp4jhsi2brc36r482im634a4lysfha81mws97jpwqz9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "robotframework" = super.buildPythonPackage rec {
    pname = "robotframework";
    version = "3.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/22/0f/1b9ffa0c4e59789b50e6034866e823b7d4a5c7eaedad7bfd0bba42f2aa9d/robotframework-3.1.2-py2.py3-none-any.whl";
      sha256 = "1w67hgqxxhvr8chxcf403xrhn36mrpjz23p3s73r8z3727vh8jyc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "robotframework-appiumlibrary" = super.buildPythonPackage rec {
    pname = "robotframework-appiumlibrary";
    version = "1.5.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/bf/00e19c7f2a683defdc068320c96f3a0aeb0e5c7b63f1cb436d91ffb50097/robotframework_appiumlibrary-1.5.0.4-py2.py3-none-any.whl";
      sha256 = "13w2y12mvs5879dlv173kh33b1w1h4f6f8pks2dr19v88lh9c2w8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Appium-Python-Client"
      self."decorator"
      self."docutils"
      self."kitchen"
      self."robotframework"
      self."selenium"
      self."six"
    ];
  };
  "robotframework-faker" = super.buildPythonPackage rec {
    pname = "robotframework-faker";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/53/27/e51e1ab454b0d207a86cd6395b663da0f524f5aba54a4126fee342cd8e47/robotframework_faker-5.0.0-py3-none-any.whl";
      sha256 = "1qrjg6sp4cl1dajvvrq81v0k74lg0qhzzb6cd72rl3dgihwvqw9l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."faker"
      self."robotframework"
      self."wrapt"
    ];
  };
  "robotframework-jupyterlibrary" = super.buildPythonPackage rec {
    pname = "robotframework-jupyterlibrary";
    version = "0.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/e9/f5ae254b5d9232c29d6f81aca3efd068663781ed5d1be4cf278e7fdc9354/robotframework_jupyterlibrary-0.2.0-py2.py3-none-any.whl";
      sha256 = "121diqa1c6dp966i00jp87bjrw74kj4xm41fcwiyx0b4svjzd566";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pillow"
      self."robotframework"
      self."robotframework-seleniumlibrary"
      self."six"
    ];
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumlibrary";
    version = "4.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/09/dd1f76346caf575ad4c301e428f719fac230e176cb8141d2b2446930e623/robotframework_seleniumlibrary-4.3.0-py2.py3-none-any.whl";
      sha256 = "01s19as8h8pr5bqd37qpcgf91parcaq9bcj1ipg6mn41dmdw2rww";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
  };
  "robotframework-seleniumscreenshots" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumscreenshots";
    version = "0.9.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1d/74/bc74ab673111c889055f2b91d99c23092ce24edd4c92f674500ddf0744c9/robotframework_seleniumscreenshots-0.9.5-py3-none-any.whl";
      sha256 = "1kay5j7mhflbv1pnvzcq5s7b88hbxa8bk6gx4dxvlhngxrcnsm39";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."robotframework"
      self."robotframework-seleniumlibrary"
      self."setuptools"
    ];
  };
  "robotframework-seleniumtestability" = super.buildPythonPackage rec {
    pname = "robotframework-seleniumtestability";
    version = "0.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/79/31/31aed738891b7ed4bcbc844cbe4dd03478e2c2b46e7243cef2464ef20160/robotframework-seleniumtestability-0.9.2.tar.gz";
      sha256 = "1qj47b3621nyg1d4zl9j8q8r5bfl06p8mzbb2ja4vi1c7ajr913l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."furl"
      self."robotframework-seleniumlibrary"
      self."wrapt"
    ];
  };
  "selenium" = super.buildPythonPackage rec {
    pname = "selenium";
    version = "3.141.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl";
      sha256 = "0g6bwadmm1757n6yxcd1ihxv04f428kayjmhv6i9jnsspkbk2w9d";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."urllib3"
    ];
  };
  "setuptools-scm" = super.buildPythonPackage rec {
    pname = "setuptools-scm";
    version = "3.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4b/c1/118ec08816737cc46b4dd93b22f7a138fbfb14b53f4b4718fd9983e70a50/setuptools_scm-3.5.0-py2.py3-none-any.whl";
      sha256 = "13z30zcwzp1g9g27xv91yrhhbsx2ljw0xkvb36vkx9708cyxn8qd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl";
      sha256 = "0v2bfai6xiqkl06hy7996wkbali2p5vxznfnygkr7xyqakid4g4g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "snowballstemmer" = super.buildPythonPackage rec {
    pname = "snowballstemmer";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/4b/cdf1113a0e88b641893b814e9c36f69a6fda28cd88b62c7f0d858cde3166/snowballstemmer-2.0.0-py2.py3-none-any.whl";
      sha256 = "1w2yrh4bx1lfz1pnzmb7zara77136vs29gdxfg5v7z9kfmyjb7r0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinx" = super.buildPythonPackage rec {
    pname = "sphinx";
    version = "3.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/ee/b1ca567be96185ccc7d352dffa46cb047eb62fbf437e643d4dee5df09619/Sphinx-3.0.3-py3-none-any.whl";
      sha256 = "10wddfalnr707qg6jsfxfknj00rd5pdrn3rqjywz74lmrxs5sl7m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."alabaster"
      self."babel"
      self."docutils"
      self."imagesize"
      self."jinja2"
      self."packaging"
      self."pygments"
      self."requests"
      self."setuptools"
      self."snowballstemmer"
      self."sphinxcontrib-applehelp"
      self."sphinxcontrib-devhelp"
      self."sphinxcontrib-htmlhelp"
      self."sphinxcontrib-jsmath"
      self."sphinxcontrib-qthelp"
      self."sphinxcontrib-serializinghtml"
    ];
  };
  "sphinx-rtd-theme" = super.buildPythonPackage rec {
    pname = "sphinx-rtd-theme";
    version = "0.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/b4/4df37087a1d36755e3a3bfd2a30263f358d2dea21938240fa02313d45f51/sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl";
      sha256 = "1m7c5fd3wz032z6kmgs3b035zsgi9h4n4z406gj5x2d70iaqkkq0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."sphinx"
    ];
  };
  "sphinxcontrib-applehelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-applehelp";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dc/47/86022665a9433d89a66f5911b558ddff69861766807ba685de2e324bd6ed/sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl";
      sha256 = "0nl8mw0kxd0544ws9c9gcplikzbv4zzfghf4kv19ggk2x7ji2qc0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-devhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-devhelp";
    version = "1.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/09/5de5ed43a521387f18bdf5f5af31d099605c992fd25372b2b9b825ce48ee/sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl";
      sha256 = "0bjafgjc3lbw9h6bq8q49hjjbwvi50fx67pygypw2p1kk8zj4rc1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-htmlhelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-htmlhelp";
    version = "1.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/62/8222554b29b3acde8420128d6d3999c5904d40922ef4b6ccb370e2be7421/sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl";
      sha256 = "0vx8rkvw46j6s9jisnq9bi4anyf8mxnysp686yn41qs15i5c42rw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-jsmath" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-jsmath";
    version = "1.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/42/4c8646762ee83602e3fb3fbe774c2fac12f317deb0b5dbeeedd2d3ba4b77/sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl";
      sha256 = "0y1i21qwi5p5f98jxds8r1n12yj12la6nrkkiq3z5wvqzgmymhif";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-qthelp" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-qthelp";
    version = "1.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/14/05f9206cf4e9cfca1afb5fd224c7cd434dcc3a433d6d9e4e0264d29c6cdb/sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl";
      sha256 = "1dps9m29ay339v0shix314qac2imh7kavjjfzm8qv2klrd5w57xx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "sphinxcontrib-serializinghtml" = super.buildPythonPackage rec {
    pname = "sphinxcontrib-serializinghtml";
    version = "1.1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/ca/bfad79b79b3821d0c6361c431f0ef4aec16ee248338b2c2013008b34d345/sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl";
      sha256 = "16jsvf8jj20qg9imp7kglvlqxqkl9mfnzwawirx62n9z88fshhpj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "strict-rfc3339" = super.buildPythonPackage rec {
    pname = "strict-rfc3339";
    version = "0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "terminado" = super.buildPythonPackage rec {
    pname = "terminado";
    version = "0.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ff/96/1d9a2c23990aea8f8e0b5c3b6627d03196a73771a17a2d9860bbe9823ab6/terminado-0.8.3-py2.py3-none-any.whl";
      sha256 = "1mslg9pgwwlz4adblm5wj3qjkm98zk1xkcc30zfq1iiv6lzcngd4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
  };
  "testpath" = super.buildPythonPackage rec {
    pname = "testpath";
    version = "0.4.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/9e/1a170feaa54f22aeb5a5d16c9015e82234275a3c8ab630b552493f9cb8a9/testpath-0.4.4-py2.py3-none-any.whl";
      sha256 = "1m453yazb4b9fnw1yklzssixs7lbjd30agh6g5sxpwsbxw8r9kxz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "text-unidecode" = super.buildPythonPackage rec {
    pname = "text-unidecode";
    version = "1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/a5/c0b6468d3824fe3fde30dbb5e1f687b291608f9473681bbf7dabbf5a87d7/text_unidecode-1.3-py2.py3-none-any.whl";
      sha256 = "1s12m0s73djhjcc1i2w8hx94ak2glqmiqwr32qj3anc9ic7g248k";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "toml" = super.buildPythonPackage rec {
    pname = "toml";
    version = "0.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl";
      sha256 = "03hhr7mq3kvkdf41acfsn6jji22aw0vxy4d8c79rjn1d57fq4mi3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tornado" = super.buildPythonPackage rec {
    pname = "tornado";
    version = "6.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/84/119a46d494f008969bf0c775cb2c6b3579d3c4cc1bb1b41a022aa93ee242/tornado-6.0.4.tar.gz";
      sha256 = "1p5n7sw4580pkybywg93p8ddqdj9lhhy72rzswfa801vlidx9qhg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "traitlets" = super.buildPythonPackage rec {
    pname = "traitlets";
    version = "4.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ca/ab/872a23e29cec3cf2594af7e857f18b687ad21039c1f9b922fac5b9b142d5/traitlets-4.3.3-py2.py3-none-any.whl";
      sha256 = "0i7ycyjad9kq6lgq5ih7j8xsm639z24250s6d17pp781v6hwdd3h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
  };
  "typed-ast" = super.buildPythonPackage rec {
    pname = "typed-ast";
    version = "1.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/09/b6a6b14bb8c5ec4a24fe0cf0160aa0b784fd55a6fd7f8da602197c5c461e/typed_ast-1.4.1.tar.gz";
      sha256 = "02y37qlynad13cgz7770a3pghdrq3aqch8mbhwqqw5sm8kcsm2lc";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tzlocal" = super.buildPythonPackage rec {
    pname = "tzlocal";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl";
      sha256 = "0j4h0dp5f9m51hlhnrvvwr1d0h33lkc9gppfw5h4nfv319pg3j8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.25.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl";
      sha256 = "05cikmgc4phnk6aidvnhj00rvyz3159aqhs889ynfvbyp076n848";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "validate-email" = super.buildPythonPackage rec {
    pname = "validate-email";
    version = "1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/a0/cb53fb64b52123513d04f9b913b905f3eb6fda7264e639b4573cc715c29f/validate_email-1.3.tar.gz";
      sha256 = "1bxffaf5yz2cph8ki55vdvdypbwkvn2xr1firlcy62vqbzf1jivq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.1.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl";
      sha256 = "1qdvs6cnb3c8p28lfkzfcn6qvcwwszff2b02cx0a02f0nf323zna";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "webencodings" = super.buildPythonPackage rec {
    pname = "webencodings";
    version = "0.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl";
      sha256 = "0y2aa53jkkcszhbbx59z817ywjvy3ah3lavym6bn88n2yc9i5bx0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "widgetsnbextension" = super.buildPythonPackage rec {
    pname = "widgetsnbextension";
    version = "3.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/7b/7ac231c20d2d33c445eaacf8a433f4e22c60677eb9776c7c5262d7ddee2d/widgetsnbextension-3.5.1-py2.py3-none-any.whl";
      sha256 = "1kcbjd8rfj1sp63277caz3d0mfkczjwwav7azyjp31a8xf64ycdx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."notebook"
    ];
  };
  "wmctrl" = super.buildPythonPackage rec {
    pname = "wmctrl";
    version = "0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/c6/001aefbde5782d6f359af0a8782990c3f4e751e29518fbd59dc8dfc58b18/wmctrl-0.3.tar.gz";
      sha256 = "04wacb7lj7rbpx5q5cnb19n9k4w85szdfa8xwfv6chsmq5dgc1nq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/82/f7/e43cefbe88c5fd371f4cf0cf5eb3feccd07515af9fd6cf7dbf1d1793a797/wrapt-1.12.1.tar.gz";
      sha256 = "1mwpkdnqxf0yxj1a0hsnl06lf287qi5ap7309wm37x45zf0zlbxn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl";
      sha256 = "02rjw1wk2bcf6xpsbhga80a8kvhnf5wms19rlrzyzdy0y07madma";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
