# Generated by pip2nix 0.8.0.dev1
# See https://github.com/johbo/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Appium-Python-Client" = super.buildPythonPackage {
    name = "Appium-Python-Client-0.46";
    doCheck = false;
    propagatedBuildInputs = [
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/98/b55d1bf7b218f41fc0cc9c251936716996a1c8eb40c3d4fa343cfffba6c5/Appium-Python-Client-0.46.tar.gz";
      sha256 = "03n78f8zpph4mgd31n1a9nap9y1gbiccnh20xcn69mjr66hdbv4d";
    };
  };
  "GenSON" = super.buildPythonPackage {
    name = "GenSON-1.0.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8d/84/0dba142f2968e517a0ac0937245e2659150b7c9612ae4589130e36cf308c/genson-1.0.2.tar.gz";
      sha256 = "1yjn9k224dsmwgfypc7ir4v8198wcdghnfbzjl7y3gqcph42wvlb";
    };
  };
  "MarkupSafe" = super.buildPythonPackage {
    name = "MarkupSafe-1.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
  };
  "PyYAML" = super.buildPythonPackage {
    name = "PyYAML-5.1.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz";
      sha256 = "1r5faspz73477hlbjgilw05xsms0glmsa371yqdd26znqsvg1b81";
    };
  };
  "RESTinstance" = super.buildPythonPackage {
    name = "RESTinstance-1.0.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."GenSON"
      self."docutils"
      self."flex"
      self."jsonpath-ng"
      self."jsonschema"
      self."pygments"
      self."pytz"
      self."requests"
      self."rfc3987"
      self."robotframework"
      self."strict-rfc3339"
      self."tzlocal"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/48/0e/366e2c3caed7dfa4722259ff951eb7b0705e693d5994ce161e3bb16579d7/RESTinstance-1.0.1.tar.gz";
      sha256 = "11kzmz4c8i0mz3kbz5l6lzx58wz0r65l8mn7y443bld4m5lh6p71";
    };
  };
  "Send2Trash" = super.buildPythonPackage {
    name = "Send2Trash-1.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/13/2e/ea40de0304bb1dc4eb309de90aeec39871b9b7c4bd30f1a3cdcb3496f5c0/Send2Trash-1.5.0.tar.gz";
      sha256 = "1ci8vcwjmjlp11ljj1ckrfmml9fkq1mclx2gr53y4zvhgp01q030";
    };
  };
  "appdirs" = super.buildPythonPackage {
    name = "appdirs-1.4.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/48/69/d87c60746b393309ca30761f8e2b49473d43450b150cb08f3c6df5c11be5/appdirs-1.4.3.tar.gz";
      sha256 = "14id6wxi12lgyw0mg3bcfnf888ad07jz9yj46gfzhn186z8rcn4y";
    };
  };
  "astroid" = super.buildPythonPackage {
    name = "astroid-2.2.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."lazy-object-proxy"
      self."six"
      self."typed-ast"
      self."wrapt"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/e3/4ec967f7db4644b1fe849e4724191346d3e3f8172631ad7266f7f17a6018/astroid-2.2.5.tar.gz";
      sha256 = "1x5c8fiqa18frwwfdsw41lpqsyff3w4lxvjx9d5ccs4zfkhy2q35";
    };
  };
  "atomicwrites" = super.buildPythonPackage {
    name = "atomicwrites-1.3.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/0f/cd484ac8820fed363b374af30049adc8fd13065720fd4f4c6be8a2309da7/atomicwrites-1.3.0.tar.gz";
      sha256 = "19ngcscdf3jsqmpcxn6zl5b6anmsajb6izp1smcd1n02midl9abm";
    };
  };
  "attrs" = super.buildPythonPackage {
    name = "attrs-19.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/d9/931a24cc5394f19383fbbe3e1147a0291276afa43a0dc3ed0d6cd9fda813/attrs-19.1.0.tar.gz";
      sha256 = "16g33zr5f449lqc5wgvzpknxryfzrfsxcr6kpgxwn7l5fkv71f7h";
    };
  };
  "backcall" = super.buildPythonPackage {
    name = "backcall-0.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz";
      sha256 = "1r01dqch3f8fdj3n6fviw8hxqrs6w5v0qw4izmvqzry1w9dxiv1q";
    };
  };
  "black" = super.buildPythonPackage {
    name = "black-19.3b0";
    doCheck = false;
    propagatedBuildInputs = [
      self."appdirs"
      self."attrs"
      self."click"
      self."toml"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/07/aebb10fb8f2ffbac672dfbebffa724643bc84cf012a57737a622d1dabddb/black-19.3b0.tar.gz";
      sha256 = "073kd5rs02lisp6n3h7yai9lix520xnaa6c7rdmp2sci9pyhz5b8";
    };
  };
  "bleach" = super.buildPythonPackage {
    name = "bleach-3.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."webencodings"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/78/5a/0df03e8735cd9c75167528299c738702437589b9c71a849489d00ffa82e8/bleach-3.1.0.tar.gz";
      sha256 = "1yhrgrhkln8bd6gn3imj69g1h4xqah9gaz9q26crqr6gmmvpzprz";
    };
  };
  "certifi" = super.buildPythonPackage {
    name = "certifi-2019.6.16";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/67/5d0548226bcc34468e23a0333978f0e23d28d0b3f0c71a151aef9c3f7680/certifi-2019.6.16.tar.gz";
      sha256 = "159nhzjk8r98agk8p2130aygjcd2qc9lw84m2dxmg7qb7ak3npll";
    };
  };
  "chardet" = super.buildPythonPackage {
    name = "chardet-3.0.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz";
      sha256 = "1bpalpia6r5x1kknbk11p1fzph56fmmnp405ds8icksd3knr5aw4";
    };
  };
  "click" = super.buildPythonPackage {
    name = "click-7.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/5c/f60e9d8a1e77005f664b76ff8aeaee5bc05d0a91798afd7f53fc998dbc47/Click-7.0.tar.gz";
      sha256 = "1mzjixd4vjbjvzb6vylki9w1556a9qmdh35kzmq6cign46av952v";
    };
  };
  "coverage" = super.buildPythonPackage {
    name = "coverage-4.5.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz";
      sha256 = "0p0j4di6h8k6ica7jwwj09azdcg4ycxq60i9qsskmsg94cd9yzg0";
    };
  };
  "coveralls" = super.buildPythonPackage {
    name = "coveralls-1.8.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."coverage"
      self."docopt"
      self."requests"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/30/379ee3a25dd7495dd671a214a183012d67c2f8c2efea958ee9a457399ee8/coveralls-1.8.2.tar.gz";
      sha256 = "13205zkf4x118ylq19ghscssfhfn2pgich978ziqsidwykgcslgv";
    };
  };
  "decorator" = super.buildPythonPackage {
    name = "decorator-4.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/19/1119fe7b1e49b9c8a9f154c930060f37074ea2e8f9f6558efc2eeaa417a2/decorator-4.4.0.tar.gz";
      sha256 = "1pi54wqj2p6ka13x7q8d5zgqg9bcf7m5d00l7x5bi204qmhn65c6";
    };
  };
  "defusedxml" = super.buildPythonPackage {
    name = "defusedxml-0.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/5f/f8aa58ca0cf01cbcee728abc9d88bfeb74e95e6cb4334cfd5bed5673ea77/defusedxml-0.6.0.tar.gz";
      sha256 = "1xbp8fivl3wlbyg2jrvs4lalaqv1xp9a9f29p75wdx2s2d6h717n";
    };
  };
  "docopt" = super.buildPythonPackage {
    name = "docopt-0.6.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz";
      sha256 = "14f4hn6d1j4b99svwbaji8n2zj58qicyz19mm0x6pmhb50jsics9";
    };
  };
  "docutils" = super.buildPythonPackage {
    name = "docutils-0.14";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz";
      sha256 = "0x22fs3pdmr42kvz6c654756wja305qv6cx1zbhwlagvxgr4xrji";
    };
  };
  "entrypoints" = super.buildPythonPackage {
    name = "entrypoints-0.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b4/ef/063484f1f9ba3081e920ec9972c96664e2edb9fdc3d8669b0e3b8fc0ad7c/entrypoints-0.3.tar.gz";
      sha256 = "0lc4si3xb7hza424414rdqdc3vng3kcrph8jbvjqb32spqddf3f7";
    };
  };
  "faker" = super.buildPythonPackage {
    name = "faker-2.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."python-dateutil"
      self."six"
      self."text-unidecode"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/f4/fced6499dd8bdb4181df08bf8d8da98da1acfee81508e9fb6792eeade8de/Faker-2.0.0.tar.gz";
      sha256 = "0isvi5byc5izkp4wxfhrliakahcvyqr53pn3s2i0j93gf017kbcn";
    };
  };
  "fancycompleter" = super.buildPythonPackage {
    name = "fancycompleter-0.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/e3/da39a6cfaffe578a01221261ac1d5d99c48d44f6377ff0de3a12dd332cec/fancycompleter-0.8.tar.gz";
      sha256 = "04lvacix99d242b1jv2qxdi6gq1djv8w1i3racliydqj6lgjylnj";
    };
  };
  "flex" = super.buildPythonPackage {
    name = "flex-6.14.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."PyYAML"
      self."click"
      self."jsonpointer"
      self."requests"
      self."rfc3987"
      self."six"
      self."strict-rfc3339"
      self."validate-email"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/6f/6680594b2d34737b8cdf871e6216cd182d251d145297cb6805ddb4fd2502/flex-6.14.0.tar.gz";
      sha256 = "0qm3ylb10dxwmibj252dh4ryx7sq23ndyga3lckx3jj6abyal6kd";
    };
  };
  "future" = super.buildPythonPackage {
    name = "future-0.17.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz";
      sha256 = "1f2rlqn9rh7adgir52dlbqz69gsab44x0mlm8gf1cs7xvhv54137";
    };
  };
  "idna" = super.buildPythonPackage {
    name = "idna-2.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/13/eb56951b6f7950cadb579ca166e448ba77f9d24efc03edd7e55fa57d04b7/idna-2.8.tar.gz";
      sha256 = "01rlkigdxg17sf9yar1jl8n18ls59367wqh59hnawlyg53vb6my3";
    };
  };
  "importlib-metadata" = super.buildPythonPackage {
    name = "importlib-metadata-0.19";
    doCheck = false;
    propagatedBuildInputs = [
      self."zipp"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/49/58d50a592d99a6bf58c4c1b02b203a48357a74e33922a9d021fda07d4ce3/importlib_metadata-0.19.tar.gz";
      sha256 = "1s34z8i79a67azv4y0sgiz2p9f6arf9rsdsm4fai7988w1rxilr3";
    };
  };
  "iplantuml" = super.buildPythonPackage {
    name = "iplantuml-0.1.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."plantweb"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/10/b9/4db9b9ce81184d1d67f82284ca6131258b32f3f69376ee88aab5f7ff60a4/IPlantUML-0.1.1.tar.gz";
      sha256 = "0p1w48iik5cl137b4xy3g5x52wl5b9fayxlr97bzd5v65dqxz1hg";
    };
  };
  "ipykernel" = super.buildPythonPackage {
    name = "ipykernel-5.1.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython"
      self."jupyter-client"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/c9/5cb348d0bde4d4f05443c23c1aaf8965d19cf106d1ec0e70195012f5cf9d/ipykernel-5.1.2.tar.gz";
      sha256 = "04jx6ihj3zpj4c7acqa14gl37mpdnbgmfm4nvv97xkjc1cz920xm";
    };
  };
  "ipython" = super.buildPythonPackage {
    name = "ipython-7.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."backcall"
      self."decorator"
      self."jedi"
      self."pexpect"
      self."pickleshare"
      self."prompt-toolkit"
      self."pygments"
      self."setuptools"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/dd/dd19a446528a6b10b1e322303916a28b73820e76f1c93c2580f05557210d/ipython-7.7.0.tar.gz";
      sha256 = "03j15blmgg2cxqrysrnwxzp731n3dnwpn7qspi8jg4qyja91cfhx";
    };
  };
  "ipython-genutils" = super.buildPythonPackage {
    name = "ipython-genutils-0.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/69/fbeffffc05236398ebfcfb512b6d2511c622871dca1746361006da310399/ipython_genutils-0.2.0.tar.gz";
      sha256 = "1a4bc9y8hnvq6cp08qs4mckgm6i6ajpndp4g496rvvzcfmp12bpb";
    };
  };
  "ipywidgets" = super.buildPythonPackage {
    name = "ipywidgets-7.5.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."nbformat"
      self."traitlets"
      self."widgetsnbextension"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/74/e92a731b6afbf493b1fb898d0af8d0cfcf23e3f5a43ba139bf40ea426bbe/ipywidgets-7.5.1.tar.gz";
      sha256 = "15sww2mvnkqlvx55gwa82v05062a8j1xpncnqna4k9sl53hgcig9";
    };
  };
  "isort" = super.buildPythonPackage {
    name = "isort-4.3.21";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/43/00/8705e8d0c05ba22f042634f791a61f4c678c32175763dcf2ca2a133f4739/isort-4.3.21.tar.gz";
      sha256 = "1cfavhcvfy2sqdkpznc0xvhv15y91syqc36dxbyc8mc98s97xnjl";
    };
  };
  "jedi" = super.buildPythonPackage {
    name = "jedi-0.15.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."parso"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/85/03/cd5a6e44a5753b4d539288d9d1f9645caac889c17dd2950292a8818f86b2/jedi-0.15.1.tar.gz";
      sha256 = "0bp4pxhsynaarbvzblsn5x32lzp29svy3sxfy8i6m5iwz9s9r1ds";
    };
  };
  "jinja2" = super.buildPythonPackage {
    name = "jinja2-2.10.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/ea/d884a06f8c7f9b7afbc8138b762e80479fb17aedbbe2b06515a12de9378d/Jinja2-2.10.1.tar.gz";
      sha256 = "04shqrs56aj04ipyqykj512rw2l0zfammvj9krawzxz7xc14yp06";
    };
  };
  "json5" = super.buildPythonPackage {
    name = "json5-0.8.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/68/e182f2c6e8d672dbf368a06640ccfc0fb64ef181f721ec29c16d9c383f98/json5-0.8.5.tar.gz";
      sha256 = "1c3k5blbhq7g2lnbap26a846ag5x19ivisd3wfzz6bzdl46hyjqj";
    };
  };
  "jsonpath-ng" = super.buildPythonPackage {
    name = "jsonpath-ng-1.4.3";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/f3/cd8f8a0bb345985b83e76721e6f64222f92f34a217a4e9720f70427a1b4c/jsonpath-ng-1.4.3.tar.gz";
      sha256 = "1gphkq565nq2bms9mha5gir9q38gzgfgnmd48mlg9cp9fyw7bz5i";
    };
  };
  "jsonpointer" = super.buildPythonPackage {
    name = "jsonpointer-2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/e7/246d9ef2366d430f0ce7bdc494ea2df8b49d7a2a41ba51f5655f68cfe85f/jsonpointer-2.0.tar.gz";
      sha256 = "0qjkjy1qlyc1nl3k95wd03ssxac0a717x8889ypgs1cfcj3bm4n1";
    };
  };
  "jsonschema" = super.buildPythonPackage {
    name = "jsonschema-3.0.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
      self."setuptools"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1f/7f/a020327823b9c405ee6f85ab3053ff171e10801b19cfe55c78bb0b3810e7/jsonschema-3.0.1.tar.gz";
      sha256 = "03g20i1xfg4qdlk4475pl4pp7y0h37g1fbgs5qhy678q9xb822hc";
    };
  };
  "jupyter" = super.buildPythonPackage {
    name = "jupyter-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipywidgets"
      self."jupyter-console"
      self."nbconvert"
      self."notebook"
      self."qtconsole"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c9/a9/371d0b8fe37dd231cf4b2cff0a9f0f25e98f3a73c3771742444be27f2944/jupyter-1.0.0.tar.gz";
      sha256 = "0pwf3pminkzyzgx5kcplvvbvwrrzd3baa7lmh96f647k30rlpp6r";
    };
  };
  "jupyter-client" = super.buildPythonPackage {
    name = "jupyter-client-5.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyter-core"
      self."python-dateutil"
      self."pyzmq"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/90/314cb3c69f25e70f82ba8528e536fbe66510daff83f22ef3f22082986a9e/jupyter_client-5.3.1.tar.gz";
      sha256 = "102qgc7isfxwq0zsj6m9apcyj2hk8c8c4fz7656lxlpmvxgazs4q";
    };
  };
  "jupyter-console" = super.buildPythonPackage {
    name = "jupyter-console-6.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython"
      self."jupyter-client"
      self."prompt-toolkit"
      self."pygments"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/c8/b7e768a3dec19b09d8ad5296a479e03c19a741a1bb4abab27c09236b8562/jupyter_console-6.0.0.tar.gz";
      sha256 = "1xdjw11cppf1fxvwkw2bk13ckkwas3bdah8baingn9296mvfi31h";
    };
  };
  "jupyter-core" = super.buildPythonPackage {
    name = "jupyter-core-4.5.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/de/ff4ca734656d17ebe0450807b59d728f45277e2e7f4b82bc9aae6cb82961/jupyter_core-4.5.0.tar.gz";
      sha256 = "1xr4pbghwk5hayn5wwnhb7z95380r45p79gf5if5pi1akwg7qvic";
    };
  };
  "jupyterlab" = super.buildPythonPackage {
    name = "jupyterlab-1.0.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."jupyterlab-server"
      self."notebook"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d4/52/d2352aa251df8007cdfbcd0eca247f778fe2a81d317232ab7fd3799e080e/jupyterlab-1.0.5.tar.gz";
      sha256 = "0q4j1jf6m5x9qdhzjbc41pnix6r9whicglnndd8qgqpfmcv0h9l9";
    };
  };
  "jupyterlab-server" = super.buildPythonPackage {
    name = "jupyterlab-server-1.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."json5"
      self."jsonschema"
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/37/ecdeace2c358a78dff7fd35de4c8b43dcc617532f55fc218698cfe6f21ec/jupyterlab_server-1.0.0.tar.gz";
      sha256 = "06hsyk0nrikcmqgv3l29bhgdmvdls1d9bfdwnl1pvxwkizp66zm7";
    };
  };
  "kitchen" = super.buildPythonPackage {
    name = "kitchen-1.2.6";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/ca/3365cb1160533be8c8b57dbfd6502f367d35e30935ee89a003c664740714/kitchen-1.2.6.tar.gz";
      sha256 = "0g5hq2icnng9vy4www5hnr3r5srisfwp0wxw1sv5c5dxy61gak5q";
    };
  };
  "lazy-object-proxy" = super.buildPythonPackage {
    name = "lazy-object-proxy-1.4.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/57/a36f682668ffc453e86ddfb5a2a49848edcb7bd04a210a5a8692a48ed9c4/lazy-object-proxy-1.4.1.tar.gz";
      sha256 = "0wbsaaj2dgsx187imwyqs7xbigbxnh3shkqapiw996ydi5h3z9sb";
    };
  };
  "lunr" = super.buildPythonPackage {
    name = "lunr-0.5.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."future"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/3b/9ad891da3ba78d43ee90104cd2126a032ec8b0088526be4327ffa06eedf5/lunr-0.5.5.tar.gz";
      sha256 = "0w3mypj8m6y5ii0vj01p6g0s492gy8ymxv2yn25klnc1cxa65yn5";
    };
  };
  "mccabe" = super.buildPythonPackage {
    name = "mccabe-0.6.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/18/fa675aa501e11d6d6ca0ae73a101b2f3571a565e0f7d38e062eec18a91ee/mccabe-0.6.1.tar.gz";
      sha256 = "07w3p1qm44hgxf3vvwz84kswpsx6s7kvaibzrsx5dzm0hli1i3fx";
    };
  };
  "mistune" = super.buildPythonPackage {
    name = "mistune-0.8.4";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2d/a4/509f6e7783ddd35482feda27bc7f72e65b5e7dc910eca4ab2164daf9c577/mistune-0.8.4.tar.gz";
      sha256 = "0vkmsh0x480rni51lhyvigfdf06b9247z868pk3bal1wnnfl58sr";
    };
  };
  "more-itertools" = super.buildPythonPackage {
    name = "more-itertools-7.2.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c2/31/45f61c8927c9550109f1c4b99ba3ca66d328d889a9c9853a808bff1c9fa0/more-itertools-7.2.0.tar.gz";
      sha256 = "0cpq8nkp6bxksa9fzq9sfprllqqi21rfr7dhjps2l1dp9n6x9720";
    };
  };
  "nbconvert" = super.buildPythonPackage {
    name = "nbconvert-5.6.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."bleach"
      self."defusedxml"
      self."entrypoints"
      self."jinja2"
      self."jupyter-core"
      self."mistune"
      self."nbformat"
      self."pandocfilters"
      self."pygments"
      self."testpath"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b8/a3/14c01be1987c989a72565584fbbd88fa96b656f99fec61c89f4ca622229d/nbconvert-5.6.0.tar.gz";
      sha256 = "15bni48nsaqwd2byi2gqq6s8q0dzbj6mfpxr56jnhzbfqa74cyj2";
    };
  };
  "nbformat" = super.buildPythonPackage {
    name = "nbformat-4.4.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipython-genutils"
      self."jsonschema"
      self."jupyter-core"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/0e/160754f7ae3e984863f585a3743b0ed1702043a81245907c8fae2d537155/nbformat-4.4.0.tar.gz";
      sha256 = "00nlf08h8yc4q73nphfvfhxrcnilaqanb8z0mdy6nxk0vzq4wjgp";
    };
  };
  "nbimporter" = super.buildPythonPackage {
    name = "nbimporter-0.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/a1/9771984f60c4ea6d0c36215b44a5c1537cfda845c08e7ee5cf748c43d7cf/nbimporter-0.3.1.tar.gz";
      sha256 = "1kvjpyjaa9qj9qw4n4q1q49g8zdk2d462ah27cwx8sd17prvmmzi";
    };
  };
  "notebook" = super.buildPythonPackage {
    name = "notebook-6.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."Send2Trash"
      self."ipykernel"
      self."ipython-genutils"
      self."jinja2"
      self."jupyter-client"
      self."jupyter-core"
      self."nbconvert"
      self."nbformat"
      self."prometheus-client"
      self."pyzmq"
      self."terminado"
      self."tornado"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/02/99/951cc76e3340af06c617079f65c65390507cce95c18cf28591659479208b/notebook-6.0.0.tar.gz";
      sha256 = "0lf9ddnkffpd2h26lpbfci7kpgdw4kxyndrnwjfv2kc2zbsdn5jw";
    };
  };
  "packaging" = super.buildPythonPackage {
    name = "packaging-19.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."attrs"
      self."pyparsing"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8b/3a/5bfe64c319be5775ed7ea3bc1a8e5667e0d57a740cc0498ce03e032eaf93/packaging-19.1.tar.gz";
      sha256 = "1zpaz9xrs6xawjs8l4xmfa0w5i66bc5f7nrfj00wr9sd563wm4f4";
    };
  };
  "pandocfilters" = super.buildPythonPackage {
    name = "pandocfilters-1.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4c/ea/236e2584af67bb6df960832731a6e5325fd4441de001767da328c33368ce/pandocfilters-1.4.2.tar.gz";
      sha256 = "1a8d9b7s48gmq9zj0pmbyv2sivn5i7m6mybgpkk4jm5vd7hp1pdk";
    };
  };
  "parso" = super.buildPythonPackage {
    name = "parso-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/21/40/615957db4d178b7504c87b1a5b85fa5945b0b4fa5f5a845e31fc7aad6018/parso-0.5.1.tar.gz";
      sha256 = "171a9ivhxwsd52h1cgsz40zgzpgzscn7yqb7sdjhy8m1lzj0wsv6";
    };
  };
  "pdbpp" = super.buildPythonPackage {
    name = "pdbpp-0.10.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."fancycompleter"
      self."pygments"
      self."wmctrl"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/c3/cf957fa98406ef25422b3324dee70b3624dacdd05602201af356234059c4/pdbpp-0.10.0.tar.gz";
      sha256 = "1pf4pcnaa4q40nvww3dyyw9zllm1pnwyspmlcsyr4bgkxh1anzpf";
    };
  };
  "pexpect" = super.buildPythonPackage {
    name = "pexpect-4.7.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/b1/362a0d4235496cb42c33d1d8732b5e2c607b0129ad5fdd76f5a583b9fcb3/pexpect-4.7.0.tar.gz";
      sha256 = "1sv2rri15zwhds85a4kamwh9pj49qcxv7m4miyr4jfpfwv81yb4y";
    };
  };
  "pickleshare" = super.buildPythonPackage {
    name = "pickleshare-0.7.5";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d8/b6/df3c1c9b616e9c0edbc4fbab6ddd09df9535849c64ba51fcb6531c32d4d8/pickleshare-0.7.5.tar.gz";
      sha256 = "1jmghg3c53yp1i8cm6pcrm280ayi8621rwyav9fac7awjr3kss47";
    };
  };
  "pillow" = super.buildPythonPackage {
    name = "pillow-6.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/fe/18125dc680720e4c3086dd3f5f95d80057c41ab98326877fc7d3ff6d0ee5/Pillow-6.1.0.tar.gz";
      sha256 = "1pnrsz0f0n0c819v1pdr8j6rm8xvhc9f3kh1fv9xpdp9n5ygf108";
    };
  };
  "plantweb" = super.buildPythonPackage {
    name = "plantweb-1.1.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."docutils"
      self."requests"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/ba/042877bae231c08aea328ac0aaf5c3f80538752a5a25c3da8d441902456b/plantweb-1.1.0.tar.gz";
      sha256 = "1974022rpmwjg1amc7k8n3274bfj0vychd5c81r6q4mm02kysksz";
    };
  };
  "pluggy" = super.buildPythonPackage {
    name = "pluggy-0.12.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/21/cdabca0144cfa282c2893dc8e07957245ac8657896ef3ea26f18b6fda710/pluggy-0.12.0.tar.gz";
      sha256 = "1z76dbn5f7prvwaf2gnknf741bd4clym9hal71i7d5q5mi9a2988";
    };
  };
  "ply" = super.buildPythonPackage {
    name = "ply-3.11";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/69/882ee5c9d017149285cab114ebeab373308ef0f874fcdac9beb90e0ac4da/ply-3.11.tar.gz";
      sha256 = "18qx113g9bi1ac4indd5phma82zcdq601lxncp3vjn43m2mc3iq0";
    };
  };
  "prometheus-client" = super.buildPythonPackage {
    name = "prometheus-client-0.7.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/23/41a5a24b502d35a4ad50a5bb7202a5e1d9a0364d0c12f56db3dbf7aca76d/prometheus_client-0.7.1.tar.gz";
      sha256 = "1ni2yv4ixwz32nz39ckia76lvggi7m19y5f702w5qczbnfi29kbi";
    };
  };
  "prompt-toolkit" = super.buildPythonPackage {
    name = "prompt-toolkit-2.0.9";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/a0/57dc47115621d9b3fcc589848cdbcbb6c4c130186e8fc4c4704766a7a699/prompt_toolkit-2.0.9.tar.gz";
      sha256 = "1hg32mayv5v9mwj5gyshfrmd2r03mlvj4dkhwz45zz9qh0fss695";
    };
  };
  "ptyprocess" = super.buildPythonPackage {
    name = "ptyprocess-0.6.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7d/2d/e4b8733cf79b7309d84c9081a4ab558c89d8c89da5961bf4ddb050ca1ce0/ptyprocess-0.6.0.tar.gz";
      sha256 = "1h4lcd3w5nrxnsk436ar7fwkiy5rfn5wj2xwy9l0r4mdqnf2jgwj";
    };
  };
  "py" = super.buildPythonPackage {
    name = "py-1.8.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/5a/87ca5909f400a2de1561f1648883af74345fe96349f34f737cdfc94eba8c/py-1.8.0.tar.gz";
      sha256 = "0lsy1gajva083pzc7csj1cvbmminb7b4l6a0prdzyb3fd829nqyw";
    };
  };
  "pycodestyle" = super.buildPythonPackage {
    name = "pycodestyle-2.5.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1c/d1/41294da5915f4cae7f4b388cea6c2cd0d6cd53039788635f6875dfe8c72f/pycodestyle-2.5.0.tar.gz";
      sha256 = "0v4prb05n21bm8650v0a01k1nyqjdmkrsm3zycfxh2j5k9n962p4";
    };
  };
  "pydocstyle" = super.buildPythonPackage {
    name = "pydocstyle-3.0.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
      self."snowballstemmer"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/e6/a0669df17a97e462915a10a7d6c567658b60eceddebf62a3fb9975c00196/pydocstyle-3.0.0.tar.gz";
      sha256 = "1m1xv9clkg9lgzyza6dnj359z04vh5g0h49nhzghv7lg81gchhap";
    };
  };
  "pyflakes" = super.buildPythonPackage {
    name = "pyflakes-2.1.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/64/87303747635c2988fcaef18af54bfdec925b6ea3b80bcd28aaca5ba41c9e/pyflakes-2.1.1.tar.gz";
      sha256 = "18pq95a1xj2dgdd0m85gyfsn40jajj4xc3lp8wfv7igqhrc86xnr";
    };
  };
  "pygments" = super.buildPythonPackage {
    name = "pygments-2.3.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz";
      sha256 = "0ji87g09jph8jqcvclgb02qvxasdnr9pzvk90rl66d90yqcxmyjz";
    };
  };
  "pylama" = super.buildPythonPackage {
    name = "pylama-7.7.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."mccabe"
      self."pycodestyle"
      self."pydocstyle"
      self."pyflakes"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/89/082aa9378e382bd8132c3a8a3ef09af71e1c8f5c00cef211583e476ba4df/pylama-7.7.1.tar.gz";
      sha256 = "13vx7daqz2918y9s8q3v2i3xaq3ah43a9p58srqi6hqskkpm7blv";
    };
  };
  "pylint" = super.buildPythonPackage {
    name = "pylint-2.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."astroid"
      self."isort"
      self."mccabe"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/8b/538911c0ebc2529f15004f4cb07e3ca562bb9aacea5df89cc25b62e01891/pylint-2.3.1.tar.gz";
      sha256 = "1wgzq0da87m7708hrc9h4bc5m4z2p7379i4xyydszasmjns3sgkj";
    };
  };
  "pyparsing" = super.buildPythonPackage {
    name = "pyparsing-2.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/24/eaa8d7003aee23eda270099eeec754d7bf4399f75c6a011ef948304f66a2/pyparsing-2.4.2.tar.gz";
      sha256 = "106xmhd2xn5bv6blsbqaa6wciwcq2c9i1pq1riw6s83y76wsg63g";
    };
  };
  "pyrsistent" = super.buildPythonPackage {
    name = "pyrsistent-0.15.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/66/b2638d96a2d128b168d0dba60fdc77b7800a9b4a5340cefcc5fc4eae6295/pyrsistent-0.15.4.tar.gz";
      sha256 = "0cv5xvhfhlj88pb0ghdwivkfcmgi6503qjwxx4r6n06nd6hpzd1l";
    };
  };
  "pytest" = super.buildPythonPackage {
    name = "pytest-5.0.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."atomicwrites"
      self."attrs"
      self."importlib-metadata"
      self."more-itertools"
      self."packaging"
      self."pluggy"
      self."py"
      self."wcwidth"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/60/23/de5604e58f4eba7a90f70486c8d4ece25f1a404bae29683903ffd2aea425/pytest-5.0.1.tar.gz";
      sha256 = "039p15zddrwz552c43adl256icpicbzrsgh1aq8rdqkwwxnx1xkf";
    };
  };
  "pytest-runner" = super.buildPythonPackage {
    name = "pytest-runner-5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/6d/4b41a74b31720e25abd4799be72d54811da4b4d0233e38b75864dcc1f7ad/pytest-runner-5.1.tar.gz";
      sha256 = "0ykfcnpp8c22winj63qzc07l5axwlc9ikl8vn05sc32gv3417815";
    };
  };
  "python-dateutil" = super.buildPythonPackage {
    name = "python-dateutil-2.8.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/99/5b2e99737edeb28c71bcbec5b5dda19d0d9ef3ca3e92e3e925e7c0bb364c/python-dateutil-2.8.0.tar.gz";
      sha256 = "17nsfhy4xdz1khrfxa61vd7pmvd5z0wa3zb6v4gb4kfnykv0b668";
    };
  };
  "pytz" = super.buildPythonPackage {
    name = "pytz-2018.9";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz";
      sha256 = "0k1pqnq3c4gvcspjxf3fschdjn71fk89i4wz801rxqh7f145xw6m";
    };
  };
  "pyzmq" = super.buildPythonPackage {
    name = "pyzmq-18.1.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/d2/1eb3a994374802b352d4911f3317313a5b4ea786bc830cc5e343dad9b06d/pyzmq-18.1.0.tar.gz";
      sha256 = "1cxybx8j9zr8s1vv7f54ylyaz80svd1hx68n780lq8v9vcwlgx4k";
    };
  };
  "qtconsole" = super.buildPythonPackage {
    name = "qtconsole-4.5.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ipykernel"
      self."ipython-genutils"
      self."jupyter-client"
      self."jupyter-core"
      self."pygments"
      self."traitlets"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ce/b6/b2b9c9ad387ef31997f844bc8c921796ef7ce9b002bae137fc240231fd4a/qtconsole-4.5.2.tar.gz";
      sha256 = "0z6d2rmzrx2dzbx94xxmsrl6vn6jjpzvb6014y2bqhwr7znbjzkn";
    };
  };
  "requests" = super.buildPythonPackage {
    name = "requests-2.21.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/52/2c/514e4ac25da2b08ca5a464c50463682126385c4272c18193876e91f4bc38/requests-2.21.0.tar.gz";
      sha256 = "13jr0wkj9c2j8c0c8iaal9iivi0bpxghnsdn6lxcpnmc657q4ajh";
    };
  };
  "rfc3987" = super.buildPythonPackage {
    name = "rfc3987-1.3.8";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/bb/f1395c4b62f251a1cb503ff884500ebd248eed593f41b469f89caa3547bd/rfc3987-1.3.8.tar.gz";
      sha256 = "0cx7bhyjaylwnf9armxrkb3r0s37vf0vqf3bhbll9mb0lmbx5i6k";
    };
  };
  "robotframework" = super.buildPythonPackage {
    name = "robotframework-3.1.2";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6c/04/2aee0fb807e14d2f2463217f81ac94c542b5b0c5809a7535f284a0bbb05c/robotframework-3.1.2.zip";
      sha256 = "1g0d4fqmws3dp7mzkqf63cwvjcdpbmmh47nxh17jm5n7r30df3gi";
    };
  };
  "robotframework-appiumlibrary" = super.buildPythonPackage {
    name = "robotframework-appiumlibrary-1.5.0.4";
    doCheck = false;
    propagatedBuildInputs = [
      self."Appium-Python-Client"
      self."decorator"
      self."docutils"
      self."kitchen"
      self."robotframework"
      self."selenium"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/2d/4875e3ca86ef0e8441ba24762dfdc74ec4b4436e0986060180dce9210bfb/robotframework-appiumlibrary-1.5.0.4.tar.gz";
      sha256 = "1l3l7ppp9g7m2pzs9ycbg3rby8c5gha023s0a1cyl55gv8hndnic";
    };
  };
  "robotframework-faker" = super.buildPythonPackage {
    name = "robotframework-faker-4.2.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."faker"
      self."robotframework"
      self."wrapt"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c1/3f/6db0f8a180bf5a62d25f6e30288565e1d5f75e39ece5f53bafa91db5344b/robotframework-faker-4.2.0.tar.gz";
      sha256 = "08bllg496wzbfm87ymbd7qzv8qjhhs3xbqmpxik63xmcikaf0yb1";
    };
  };
  "robotframework-seleniumlibrary" = super.buildPythonPackage {
    name = "robotframework-seleniumlibrary-3.3.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."selenium"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/e7/c577d9528b80d748fe7beca1b106d751caf39d0d77f8fd85e39b1ef50ded/robotframework-seleniumlibrary-3.3.1.tar.gz";
      sha256 = "03x1fbc37mb9lkm3spn21hiyij8c8gs20517sc89nkqa7yx0wfkg";
    };
  };
  "robotframework-seleniumscreenshots" = super.buildPythonPackage {
    name = "robotframework-seleniumscreenshots-0.9.5";
    doCheck = false;
    propagatedBuildInputs = [
      self."robotframework"
      self."robotframework-seleniumlibrary"
      self."setuptools"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/0a/5837061460432073da2984fa6cce6fdf14433f1107200d9ddb119ba93bfa/robotframework-seleniumscreenshots-0.9.5.tar.gz";
      sha256 = "05qv323hvjmy62h33ryrjaa9k1hyvp8hq5qnj8j1x3ap2ci3q3s0";
    };
  };
  "selenium" = super.buildPythonPackage {
    name = "selenium-3.141.0";
    doCheck = false;
    propagatedBuildInputs = [
      self."urllib3"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/9c/9030520bf6ff0b4c98988448a93c04fcbd5b13cd9520074d8ed53569ccfe/selenium-3.141.0.tar.gz";
      sha256 = "039hf9knvl4s3hp21bzwsp1g5ri9gxsh504dp48lc6nr1av35byy";
    };
  };
  "setuptools" = super.buildPythonPackage {
    name = "setuptools-41.1.0";
    doCheck = false;
    nativeBuildInputs = [
      pkgs."unzip"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/68/0c/e470db6866aedbff3c4c88faf7f81b90343d8ff32cd68b62db1b65037fb4/setuptools-41.1.0.zip";
      sha256 = "1a246z6cikg42adqmpswzjp59hkqwr7xxqs7xyags4cr556bh6f5";
    };
  };
  "setuptools-scm" = super.buildPythonPackage {
    name = "setuptools-scm-3.3.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/44/53cad68ce686585d12222e6769682c4bdb9686808d2739671f9175e2938b/setuptools_scm-3.3.3.tar.gz";
      sha256 = "19cyndx23xmpbhz4qrwmfwsmnnaczd0dw7qg977ksq2dbvxy29dx";
    };
  };
  "six" = super.buildPythonPackage {
    name = "six-1.12.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz";
      sha256 = "0wxs1q74v07ssjywbbm7x6h5v9qx209ld2yfsif4060sxi0h2sni";
    };
  };
  "snowballstemmer" = super.buildPythonPackage {
    name = "snowballstemmer-1.9.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/5e/d9ead2d57d39b3e1c1868ce84212319e5543a19c4185dce7e42a9dd968b0/snowballstemmer-1.9.0.tar.gz";
      sha256 = "1jfhwsca8lxsji7sh30g0jkqk77rmhqi84ky0kvp9l8913z9yfwz";
    };
  };
  "strict-rfc3339" = super.buildPythonPackage {
    name = "strict-rfc3339-0.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
  };
  "terminado" = super.buildPythonPackage {
    name = "terminado-0.8.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."ptyprocess"
      self."tornado"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/fc/f5c7c36ac0da236078a26da7dce5748db45c8273cd551232ae01b26043b3/terminado-0.8.2.tar.gz";
      sha256 = "1hi05knmq1y9a1vpnbqv6gqc6nb2mfbv1v2hn2c0ffiwz10y226y";
    };
  };
  "testpath" = super.buildPythonPackage {
    name = "testpath-0.4.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/30/9a7e917066d851d8b4117e85794b5f14516419ea714a8a2681ec6aa8a981/testpath-0.4.2.tar.gz";
      sha256 = "1y40hywscnnyb734pnzm55nd8r8kp1072bjxbil83gcd53cv755n";
    };
  };
  "text-unidecode" = super.buildPythonPackage {
    name = "text-unidecode-1.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/a2/40adaae7cbdd007fb12777e550b5ce344b56189921b9f70f37084c021ca4/text-unidecode-1.2.tar.gz";
      sha256 = "0v9r3834c82ygm21rjqk561s12gqw698vqwaa108g5m75fxpa4ss";
    };
  };
  "toml" = super.buildPythonPackage {
    name = "toml-0.10.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz";
      sha256 = "0p1xww2mzkhqvxkfvmfzm58bbfj812zhdz4rwdjiv94ifz2q37r2";
    };
  };
  "tornado" = super.buildPythonPackage {
    name = "tornado-6.0.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/78/2d2823598496127b21423baffaa186b668f73cd91887fcef78b6eade136b/tornado-6.0.3.tar.gz";
      sha256 = "1afpxpv75zi1zvj2b3s6d7r4s4p0z2byh7jv9h3i4sb1p8vdnif8";
    };
  };
  "traitlets" = super.buildPythonPackage {
    name = "traitlets-4.3.2";
    doCheck = false;
    propagatedBuildInputs = [
      self."decorator"
      self."ipython-genutils"
      self."six"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a5/98/7f5ef2fe9e9e071813aaf9cb91d1a732e0a68b6c44a32b38cb8e14c3f069/traitlets-4.3.2.tar.gz";
      sha256 = "0dbq7sx26xqz5ixs711k5nc88p8a0nqyz6162pwks5dpcz9d4jww";
    };
  };
  "typed-ast" = super.buildPythonPackage {
    name = "typed-ast-1.4.0";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/34/de/d0cfe2ea7ddfd8b2b8374ed2e04eeb08b6ee6e1e84081d151341bba596e5/typed_ast-1.4.0.tar.gz";
      sha256 = "0d2fnjblqfiidww29z7kf1wr71fm6zs2rww7bif9qz0np2ahyj36";
    };
  };
  "tzlocal" = super.buildPythonPackage {
    name = "tzlocal-1.5.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."pytz"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/89/e3687d3ed99bc882793f82634e9824e62499fdfdc4b1ae39e211c5b05017/tzlocal-1.5.1.tar.gz";
      sha256 = "0kiciwiqx0bv0fbc913idxibc4ygg4cb7f8rcpd9ij2shi4bigjf";
    };
  };
  "urllib3" = super.buildPythonPackage {
    name = "urllib3-1.24.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/3c/1bb7ef6c435dea026f06ed9f3ba16aa93f9f4f5d3857a51a35dfa00882f1/urllib3-1.24.3.tar.gz";
      sha256 = "1x0slqrv6kixkbcdnxbglvjliwhc1payavxjvk8fvbqjrnasd4r3";
    };
  };
  "validate-email" = super.buildPythonPackage {
    name = "validate-email-1.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/a0/cb53fb64b52123513d04f9b913b905f3eb6fda7264e639b4573cc715c29f/validate_email-1.3.tar.gz";
      sha256 = "1bxffaf5yz2cph8ki55vdvdypbwkvn2xr1firlcy62vqbzf1jivq";
    };
  };
  "wcwidth" = super.buildPythonPackage {
    name = "wcwidth-0.1.7";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/55/11/e4a2bb08bb450fdbd42cc709dd40de4ed2c472cf0ccb9e64af22279c5495/wcwidth-0.1.7.tar.gz";
      sha256 = "0pn6dflzm609m4r3i8ik5ni9ijjbb5fa3vg1n7hn6vkd49r77wrx";
    };
  };
  "webencodings" = super.buildPythonPackage {
    name = "webencodings-0.5.1";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0b/02/ae6ceac1baeda530866a85075641cec12989bd8d31af6d5ab4a3e8c92f47/webencodings-0.5.1.tar.gz";
      sha256 = "08qrgrc4hrximb2gqnl69g01s93rhf2842jfxdjljc1dbwj1qsmk";
    };
  };
  "widgetsnbextension" = super.buildPythonPackage {
    name = "widgetsnbextension-3.5.1";
    doCheck = false;
    propagatedBuildInputs = [
      self."notebook"
    ];
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/c4/b7211bfc8e998fe55764539d2b169fb200e6427dfe4e62d1d83013caa9ef/widgetsnbextension-3.5.1.tar.gz";
      sha256 = "1ismyaxbv9d56yqqqb8xl58hg0iq0bbyy014a53y1g3hfbc8g7q7";
    };
  };
  "wmctrl" = super.buildPythonPackage {
    name = "wmctrl-0.3";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/c6/001aefbde5782d6f359af0a8782990c3f4e751e29518fbd59dc8dfc58b18/wmctrl-0.3.tar.gz";
      sha256 = "04wacb7lj7rbpx5q5cnb19n9k4w85szdfa8xwfv6chsmq5dgc1nq";
    };
  };
  "wrapt" = super.buildPythonPackage {
    name = "wrapt-1.11.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz";
      sha256 = "1q81762dgsgrd12f8qc39zk8s5wll3m5xc32jdmlf6cls4gh4njn";
    };
  };
  "zipp" = super.buildPythonPackage {
    name = "zipp-0.5.2";
    doCheck = false;
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/66/ae/1d6693cde3b3e3c14e95cf3408f24d0e869ead42a79993b611d8817d929a/zipp-0.5.2.tar.gz";
      sha256 = "16l0dr3f1s2gvpig4hj4g53xrg3mblm1wfwpga2sg2afixsw6w29";
    };
  };
}
