00\ JupyterLab\ User\ Interface.html: 00\ JupyterLab\ User\ Interface.ipynb
	jupyter nbconvert \
		--to html \
		--TemplateExporter.exclude_input=True \
		--TemplateExporter.exclude_input_prompt=True \
		--TemplateExporter.exclude_output_prompt=True \
		--TemplateExporter.template_file=nbconvert.tpl \
		"00 JupyterLab User Interface.ipynb"
