#!/bin/bash
set -eux
pip install -e . -vv
python -m robotkernel.install --sys-prefix
jupyter serverextension enable --sys-prefix --py jupyter_starters

jupyter labextension install --no-build \
    @deathbeds/jupyterlab-starters@0.3.0-a0 \
    @jupyter-widgets/jupyterlab-manager

jupyter lab build --minimize=False --debug

jupyter labextension list

mkdir -p .jupyter/jupyter_notebook_config.d
cp src/robotkernel/resources/starter/robotkernel-starter.json .jupyter/jupyter_notebook_config.d
