#!/usr/bin/env bash
set -eux
python -m pip install -e . -vv
python -m robotkernel.install --sys-prefix

jupyter serverextension enable --sys-prefix --py jupyter_starters

jupyter labextension list

mkdir -p .jupyter/jupyter_notebook_config.d
cp src/robotkernel/resources/starter/robotkernel-starter.json .jupyter/jupyter_notebook_config.d
